const firebaseConfig={apiKey:"AIzaSyBeVpUqcRO_VXfQrGVL5OaSGHKFB8XEQMc",authDomain:"life-by-adichimp.firebaseapp.com",projectId:"life-by-adichimp",storageBucket:"life-by-adichimp.firebasestorage.app",messagingSenderId:"761981819700",appId:"1:761981819700:web:8e88516817ed40b9866361",measurementId:"G-Z0Q8WJDSMH"};
firebase.initializeApp(firebaseConfig);
const auth=firebase.auth(),db=firebase.firestore(),provider=new firebase.auth.GoogleAuthProvider();
provider.setCustomParameters({prompt:'select_account'});
const taskId=new URLSearchParams(location.search).get('id');
const el=id=>document.getElementById(id);
const ui={auth:el('auth-screen'),workspace:el('workspace'),title:el('task-title'),description:el('task-description'),status:el('task-status'),scratchpad:el('scratchpad'),steps:el('steps-list'),empty:el('empty-steps'),progress:el('progress-value'),ring:el('progress-ring'),bar:el('progress-bar'),state:el('save-state'),dot:el('sync-dot'),gallery:el('reference-gallery'),galleryEmpty:el('reference-empty'),toast:el('toast')};
let user=null,task=null,assets=[],taskUnsub=null,assetUnsub=null,saveTimer=null,openStepId=null,toastTimer=null;
const makeId=prefix=>`${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
const taskRef=()=>db.collection('users').doc(user.uid).collection('tasks').doc(taskId);
const assetsRef=()=>taskRef().collection('assets');

function setSaveState(text,type='') {ui.state.textContent=text;ui.dot.className=`sync-dot ${type}`.trim();}
function toast(message){ui.toast.textContent=message;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),2200)}
function cleanStep(step,index){return{id:step.id||makeId('s'),title:step.title||step.text||`Step ${index+1}`,notes:step.notes||'',status:step.status||(step.done?'Done':'Not Started'),done:Boolean(step.done||step.status==='Done')}}
function normalizedTask(data){const originalSteps=Array.isArray(data.steps)&&data.steps.length?data.steps:(data.subtasks||[]);return{...data,steps:originalSteps.map(cleanStep),scratchpad:data.scratchpad||''}}
function serializableTask(){const steps=task.steps.map((step,index)=>cleanStep(step,index));return{title:task.title||'',description:task.description||'',status:task.status||'Backlog',scratchpad:task.scratchpad||'',steps,subtasks:steps.map(step=>({text:step.title,done:step.done})),updatedAt:firebase.firestore.FieldValue.serverTimestamp()}}
function scheduleSave(){setSaveState('Saving…','saving');clearTimeout(saveTimer);saveTimer=setTimeout(saveTask,550)}
async function saveTask(){if(!user||!task)return;try{await taskRef().set(serializableTask(),{merge:true});setSaveState('Synced')}catch(error){console.error(error);setSaveState('Save failed','error');toast('Could not save changes')}}

auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);
auth.onAuthStateChanged(next=>{user=next;ui.auth.classList.toggle('is-hidden',!!next);ui.workspace.classList.toggle('is-hidden',!next);if(next)start();else stop()});
el('sign-in').addEventListener('click',async()=>{try{await auth.signInWithPopup(provider)}catch(error){el('auth-error').textContent=error.message||'Sign-in failed'}});
el('sign-out').addEventListener('click',()=>auth.signOut());
el('delete-task').addEventListener('click',async()=>{if(!task||!confirm(`Delete “${task.title||'this task'}” and all its attachments?`))return;try{setSaveState('Deleting…','saving');const snapshot=await assetsRef().get(),batch=db.batch();snapshot.docs.forEach(doc=>batch.delete(doc.ref));batch.delete(taskRef());await batch.commit();location.href='/invincible/'}catch(error){console.error(error);setSaveState('Delete failed','error');toast('Task could not be deleted')}});

async function start(){if(!taskId){toast('Task ID is missing');setTimeout(()=>location.href='/invincible/',900);return}stop();taskUnsub=taskRef().onSnapshot(snapshot=>{if(!snapshot.exists){toast('Task not found');setTimeout(()=>location.href='/invincible/',900);return}if(document.activeElement?.matches('input,textarea,select'))return;task=normalizedTask({id:snapshot.id,...snapshot.data()});render()},error=>{console.error(error);setSaveState('Sync failed','error')});assetUnsub=assetsRef().orderBy('createdAt','desc').onSnapshot(snapshot=>{assets=snapshot.docs.map(doc=>({id:doc.id,...doc.data()}));renderAssets()},error=>{console.error(error);setSaveState('Attachments failed','error')})}
function stop(){taskUnsub?.();assetUnsub?.();taskUnsub=assetUnsub=null}

function render(){ui.title.value=task.title||'';ui.description.value=task.description||'';ui.status.value=task.status||'Backlog';ui.scratchpad.value=task.scratchpad||'';renderSteps();renderProgress()}
function renderProgress(){const total=task.steps.length,done=task.steps.filter(step=>step.done).length,pct=total?Math.round(done/total*100):0;ui.progress.textContent=`${pct}%`;ui.ring.style.setProperty('--progress',pct);ui.bar.style.width=`${pct}%`}
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function renderSteps(){ui.steps.innerHTML='';ui.empty.classList.toggle('is-hidden',task.steps.length>0);task.steps.forEach((step,index)=>{const card=document.createElement('article');card.className=`step-card ${step.done?'is-done':''} ${openStepId===step.id?'is-open':''}`;card.dataset.id=step.id;card.innerHTML=`<div class="step-summary"><span class="step-number">${String(index+1).padStart(2,'0')}</span><input class="step-check" type="checkbox" ${step.done?'checked':''} aria-label="Complete step"><input class="step-name" value="${escapeHtml(step.title)}" aria-label="Step title"><button class="expand-step" type="button" aria-label="Open step">⌄</button></div><div class="step-detail"><div class="step-meta"><select class="step-status" aria-label="Step status"><option>Not Started</option><option>Working</option><option>Blocked</option><option>Done</option></select><button class="delete-step" type="button">Delete step</button></div><textarea class="step-notes" placeholder="Measurements, decisions, prompts, problems or next action…">${escapeHtml(step.notes)}</textarea><div class="step-tools"><label>＋ Image<input class="step-image" type="file" accept="image/*" hidden></label><button class="open-sketch" type="button">✎ Handwritten note</button></div><div class="step-assets"></div></div>`;card.querySelector('.step-status').value=step.status||'Not Started';bindStep(card,step);ui.steps.appendChild(card)});renderAssets()}
function bindStep(card,step){card.querySelector('.expand-step').addEventListener('click',()=>{openStepId=openStepId===step.id?null:step.id;renderSteps()});card.querySelector('.step-check').addEventListener('change',event=>{step.done=event.target.checked;step.status=step.done?'Done':(step.status==='Done'?'Not Started':step.status);scheduleSave();renderSteps();renderProgress()});card.querySelector('.step-name').addEventListener('input',event=>{step.title=event.target.value;scheduleSave()});card.querySelector('.step-notes').addEventListener('input',event=>{step.notes=event.target.value;scheduleSave()});card.querySelector('.step-status').addEventListener('change',event=>{step.status=event.target.value;step.done=step.status==='Done';scheduleSave();renderSteps();renderProgress()});card.querySelector('.delete-step').addEventListener('click',()=>{if(!confirm(`Delete “${step.title}”?`))return;task.steps=task.steps.filter(item=>item.id!==step.id);scheduleSave();renderSteps();renderProgress()});card.querySelector('.step-image').addEventListener('change',event=>uploadFiles([...event.target.files],step.id));card.querySelector('.open-sketch').addEventListener('click',()=>openSketch(step))}

['title','description','scratchpad'].forEach(key=>ui[key].addEventListener('input',event=>{task[key]=event.target.value;scheduleSave()}));
ui.status.addEventListener('change',event=>{task.status=event.target.value;scheduleSave()});
el('add-step').addEventListener('click',()=>{const step=cleanStep({id:makeId('s'),title:'New step'},task.steps.length);task.steps.push(step);openStepId=step.id;scheduleSave();renderSteps();renderProgress();requestAnimationFrame(()=>ui.steps.lastElementChild?.querySelector('.step-name')?.select())});

const importDialog=el('import-dialog');
el('open-import').addEventListener('click',()=>importDialog.showModal());
el('import-plan').addEventListener('click',event=>{event.preventDefault();const parsed=parsePlan(el('plan-input').value);if(!parsed.length){toast('No steps detected');return}task.steps.push(...parsed.map((title,index)=>cleanStep({id:makeId('s'),title},task.steps.length+index)));el('plan-input').value='';importDialog.close();scheduleSave();renderSteps();renderProgress();toast(`${parsed.length} steps created`)});
function parsePlan(input){const lines=input.split(/\r?\n/).map(line=>line.trim()).filter(Boolean);const tableRows=lines.filter(line=>/^\|.*\|$/.test(line)&&!/^\|?[\s:|-]+\|?$/.test(line));if(tableRows.length){const data=tableRows.slice(1);return data.map(row=>row.split('|').map(cell=>cell.trim()).filter(Boolean)).map(cells=>{const candidate=cells.find(cell=>!/^\d+$/.test(cell)&&!/^step$/i.test(cell)&&!/^duration$/i.test(cell));return candidate||cells[0]}).filter(Boolean)}return lines.map(line=>line.replace(/^[-*•]\s+/,'').replace(/^\d+[.)]\s+/,'').trim()).filter(line=>line&&!/^#{1,6}\s/.test(line))}

el('image-input').addEventListener('change',event=>uploadFiles([...event.target.files],null));
async function uploadFiles(files,stepId){for(const file of files){if(!file.type.startsWith('image/'))continue;try{setSaveState('Processing image…','saving');const dataUrl=await compressImage(file);await assetsRef().add({kind:'image',stepId:stepId||null,name:file.name,dataUrl,createdAt:firebase.firestore.FieldValue.serverTimestamp()});setSaveState('Synced')}catch(error){console.error(error);setSaveState('Upload failed','error');toast('Image could not be saved')}}}
function compressImage(file){return new Promise((resolve,reject)=>{const image=new Image(),reader=new FileReader();reader.onerror=reject;reader.onload=()=>image.src=reader.result;image.onerror=reject;image.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);let quality=.8,data=canvas.toDataURL('image/jpeg',quality);while(data.length>720000&&quality>.35){quality-=.1;data=canvas.toDataURL('image/jpeg',quality)}if(data.length>900000)reject(new Error('Image remains too large'));else resolve(data)};reader.readAsDataURL(file)})}
function renderAssets(){if(!task)return;const projectAssets=assets.filter(asset=>!asset.stepId);ui.gallery.innerHTML='';projectAssets.forEach(asset=>ui.gallery.appendChild(assetElement(asset)));ui.galleryEmpty.classList.toggle('is-hidden',projectAssets.length>0);document.querySelectorAll('.step-card').forEach(card=>{const wrap=card.querySelector('.step-assets'),stepAssets=assets.filter(asset=>asset.stepId===card.dataset.id);wrap.innerHTML='';stepAssets.forEach(asset=>wrap.appendChild(assetElement(asset)))})}
function assetElement(asset){const wrap=document.createElement('div');wrap.className='asset-thumb';wrap.innerHTML=`<img src="${asset.dataUrl}" alt="${escapeHtml(asset.name||'Task reference')}"><button class="remove-asset" aria-label="Delete image">×</button>`;wrap.querySelector('img').addEventListener('click',()=>window.open(asset.dataUrl,'_blank'));wrap.querySelector('button').addEventListener('click',async event=>{event.stopPropagation();if(confirm('Delete this attachment?'))await assetsRef().doc(asset.id).delete()});return wrap}

const sketchDialog=el('sketch-dialog'),canvas=el('sketch-canvas'),ctx=canvas.getContext('2d');
let sketchStep=null,strokes=[],currentStroke=null,sketchTool='pen';
function openSketch(step){sketchStep=step;el('sketch-title').textContent=step.title;sketchDialog.showModal();requestAnimationFrame(()=>{resizeCanvas();const existing=assets.find(asset=>asset.stepId===step.id&&asset.kind==='sketch');if(existing){const image=new Image();image.onload=()=>ctx.drawImage(image,0,0,canvas.clientWidth,canvas.clientHeight);image.src=existing.dataUrl}else clearCanvas(false)})}
function resizeCanvas(){const rect=canvas.parentElement.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2);const snapshot=canvas.width?canvas.toDataURL():null;canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);ctx.lineCap='round';ctx.lineJoin='round';if(snapshot){const image=new Image();image.onload=()=>ctx.drawImage(image,0,0,rect.width,rect.height);image.src=snapshot}}
function clearCanvas(reset=true){const rect=canvas.getBoundingClientRect();ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#f7faf8';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore();if(reset)strokes=[]}
function pointerPoint(event){const rect=canvas.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top}}
canvas.addEventListener('pointerdown',event=>{canvas.setPointerCapture(event.pointerId);currentStroke={tool:sketchTool,size:Number(el('brush-size').value),points:[pointerPoint(event)]};strokes.push(currentStroke)});
canvas.addEventListener('pointermove',event=>{if(!currentStroke)return;const point=pointerPoint(event),previous=currentStroke.points.at(-1);currentStroke.points.push(point);ctx.save();ctx.globalCompositeOperation='source-over';ctx.strokeStyle=currentStroke.tool==='eraser'?'#f7faf8':'#132b31';ctx.lineWidth=currentStroke.size;ctx.beginPath();ctx.moveTo(previous.x,previous.y);ctx.lineTo(point.x,point.y);ctx.stroke();ctx.restore()});
canvas.addEventListener('pointerup',()=>currentStroke=null);canvas.addEventListener('pointercancel',()=>currentStroke=null);
document.querySelectorAll('.tool[data-tool]').forEach(button=>button.addEventListener('click',()=>{sketchTool=button.dataset.tool;document.querySelectorAll('.tool[data-tool]').forEach(item=>item.classList.toggle('active',item===button))}));
el('clear-sketch').addEventListener('click',()=>clearCanvas());
el('undo-stroke').addEventListener('click',()=>{strokes.pop();clearCanvas(false);redrawStrokes()});
function redrawStrokes(){strokes.forEach(stroke=>{for(let index=1;index<stroke.points.length;index++){ctx.save();ctx.globalCompositeOperation='source-over';ctx.strokeStyle=stroke.tool==='eraser'?'#f7faf8':'#132b31';ctx.lineWidth=stroke.size;ctx.beginPath();ctx.moveTo(stroke.points[index-1].x,stroke.points[index-1].y);ctx.lineTo(stroke.points[index].x,stroke.points[index].y);ctx.stroke();ctx.restore()}})}
function closeSketch(){sketchDialog.close();sketchStep=null;strokes=[]}
el('close-sketch').addEventListener('click',closeSketch);el('cancel-sketch').addEventListener('click',closeSketch);
el('save-sketch').addEventListener('click',async()=>{if(!sketchStep)return;try{setSaveState('Saving sketch…','saving');const existing=assets.find(asset=>asset.stepId===sketchStep.id&&asset.kind==='sketch'),payload={kind:'sketch',stepId:sketchStep.id,name:`${sketchStep.title} sketch`,dataUrl:canvas.toDataURL('image/jpeg',.82),createdAt:firebase.firestore.FieldValue.serverTimestamp()};if(existing)await assetsRef().doc(existing.id).set(payload,{merge:true});else await assetsRef().add(payload);setSaveState('Synced');closeSketch();toast('Sketch saved')}catch(error){console.error(error);setSaveState('Save failed','error');toast('Sketch could not be saved')}});
window.addEventListener('resize',()=>{if(sketchDialog.open)resizeCanvas()});
