import{initializeApp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import{getAuth}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import{getFirestore,doc,onSnapshot,setDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
const config={apiKey:"AIzaSyBeVpUqcRO_VXfQrGVL5OaSGHKFB8XEQMc",authDomain:"life-by-adichimp.firebaseapp.com",projectId:"life-by-adichimp",storageBucket:"life-by-adichimp.firebasestorage.app",messagingSenderId:"761981819700",appId:"1:761981819700:web:8e88516817ed40b9866361"};
const auth=getAuth(initializeApp(config)),db=getFirestore(),$=id=>document.getElementById(id);
const stages=["Ideas","Research","Script","Record","Edit","Scheduled","Published"];
let user=null,state={items:[]},editingId="",filter="All",query="",mobileStage="Ideas";
const newId=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
const today=()=>new Date().toISOString().slice(0,10);
function esc(value){const node=document.createElement("div");node.textContent=value??"";return node.innerHTML}
function status(message,type=""){$("status").textContent=message;$("status").className="sync-status "+type}
function filtered(){return state.items.filter(item=>(filter==="All"||item.format===filter)&&(!query||[item.title,item.hook,item.series].join(" ").toLowerCase().includes(query)))}
function dateLabel(date){if(!date)return "";return new Date(date+"T00:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"short"})}
function moveButton(item,direction){const index=stages.indexOf(item.stage),next=index+direction;return '<button data-move="'+direction+'" data-id="'+item.id+'" aria-label="Move '+(direction<0?'back':'forward')+'" '+(next<0||next>=stages.length?'disabled':'')+'>'+(direction<0?'‹':'›')+'</button>'}
function card(item){const overdue=item.publishDate&&item.publishDate<today()&&item.stage!=="Published";return '<article class="content-card" draggable="true" data-id="'+item.id+'" tabindex="0"><div class="card-top"><span class="format">'+esc(item.format)+'</span><span class="due '+(overdue?'overdue':'')+'">'+(item.publishDate?dateLabel(item.publishDate):"No date")+'</span></div><h3>'+esc(item.title)+'</h3>'+(item.hook?'<p class="hook">'+esc(item.hook)+'</p>':'')+'<div class="card-bottom"><span class="series">'+esc(item.series||"General")+'</span><div class="card-actions">'+moveButton(item,-1)+moveButton(item,1)+'</div></div></article>'}
function renderMetrics(){const active=state.items.filter(x=>x.stage!=="Published"),scheduled=state.items.filter(x=>x.stage==="Scheduled"&&x.publishDate).sort((a,b)=>a.publishDate.localeCompare(b.publishDate));$("inPipeline").textContent=active.length;$("readyCount").textContent=state.items.filter(x=>x.stage==="Record").length;$("publishedCount").textContent=state.items.filter(x=>x.stage==="Published").length;$("nextRelease").textContent=scheduled[0]?dateLabel(scheduled[0].publishDate):"—";$("nextReleaseTitle").textContent=scheduled[0]?.title||"nothing scheduled"}
function render(){renderMetrics();const items=filtered();$("stageTabs").innerHTML=stages.map(stage=>'<button data-stage="'+stage+'" class="'+(mobileStage===stage?'active':'')+'">'+stage+' · '+items.filter(x=>x.stage===stage).length+'</button>').join("");$("board").innerHTML=stages.map(stage=>{const rows=items.filter(x=>x.stage===stage).sort((a,b)=>(a.publishDate||"9999").localeCompare(b.publishDate||"9999"));return '<section class="column '+(mobileStage===stage?'mobile-active':'')+'" data-stage="'+stage+'"><div class="column-head"><h2>'+stage+'</h2><span class="column-count">'+rows.length+'</span></div><div class="cards">'+(rows.length?rows.map(card).join(""):'<div class="empty">No content here</div>')+'</div></section>'}).join("");bindDrag()}
async function save(){if(!user)return;status("Saving…");try{await setDoc(doc(db,"users",user.uid,"creator","main"),{items:state.items,updatedAt:serverTimestamp()},{merge:true});status("Synced to Firebase","ok")}catch(error){status("Save failed: "+error.message,"error");throw error}}
function openDialog(item=null){editingId=item?.id||"";const form=$("contentForm");form.reset();$("dialogHeading").textContent=item?"Edit content":"New content";$("deleteContent").hidden=!item;if(item)Object.entries(item).forEach(([key,value])=>{if(form.elements[key])form.elements[key].value=value??""});else form.elements.stage.value=mobileStage;$("contentDialog").showModal();setTimeout(()=>form.elements.title.focus(),0)}
function bindDrag(){document.querySelectorAll(".content-card").forEach(cardEl=>{cardEl.ondragstart=event=>{cardEl.classList.add("dragging");event.dataTransfer.setData("text/plain",cardEl.dataset.id)};cardEl.ondragend=()=>cardEl.classList.remove("dragging")});document.querySelectorAll(".column").forEach(column=>{column.ondragover=event=>{event.preventDefault();column.classList.add("drag-over")};column.ondragleave=()=>column.classList.remove("drag-over");column.ondrop=async event=>{event.preventDefault();column.classList.remove("drag-over");const item=state.items.find(x=>x.id===event.dataTransfer.getData("text/plain"));if(item&&item.stage!==column.dataset.stage){item.stage=column.dataset.stage;render();await save()}}})}
$("stageSelect").innerHTML=stages.map(stage=>'<option>'+stage+'</option>').join("");
$("addContent").onclick=()=>openDialog();document.querySelectorAll("dialog .close").forEach(button=>button.onclick=()=>$("contentDialog").close());
$("stageTabs").onclick=event=>{const button=event.target.closest("[data-stage]");if(!button)return;mobileStage=button.dataset.stage;render()};
document.querySelector(".filter-group").onclick=event=>{const button=event.target.closest("[data-filter]");if(!button)return;filter=button.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===button));render()};
$("searchInput").oninput=event=>{query=event.target.value.trim().toLowerCase();render()};
$("board").onclick=async event=>{const move=event.target.closest("[data-move]");if(move){event.stopPropagation();const item=state.items.find(x=>x.id===move.dataset.id),next=stages.indexOf(item.stage)+Number(move.dataset.move);if(stages[next]){item.stage=stages[next];mobileStage=item.stage;render();await save()}return}const cardEl=event.target.closest(".content-card");if(cardEl)openDialog(state.items.find(x=>x.id===cardEl.dataset.id))};
$("board").onkeydown=event=>{if((event.key==="Enter"||event.key===" ")&&!event.target.closest("button")){event.preventDefault();const cardEl=event.target.closest(".content-card");if(cardEl)openDialog(state.items.find(x=>x.id===cardEl.dataset.id))}};
$("contentForm").onsubmit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget),item={id:editingId||newId(),title:data.get("title").trim(),format:data.get("format"),stage:data.get("stage"),series:data.get("series"),publishDate:data.get("publishDate"),hook:data.get("hook").trim(),script:data.get("script").trim(),notes:data.get("notes").trim()};const index=state.items.findIndex(x=>x.id===item.id);if(index>=0)state.items[index]=item;else state.items.push(item);mobileStage=item.stage;render();await save();$("contentDialog").close()};
$("deleteContent").onclick=async()=>{if(!editingId||!confirm("Delete this content item?"))return;state.items=state.items.filter(x=>x.id!==editingId);render();await save();$("contentDialog").close()};
await auth.authStateReady();user=auth.currentUser;if(user)onSnapshot(doc(db,"users",user.uid,"creator","main"),snapshot=>{state=snapshot.exists()?{items:[],...snapshot.data()}:{items:[]};render();$("app").hidden=false;status("Synced · "+(user.email||"signed in"),"ok")},error=>status(error.message,"error"));else{status("Sign in on the Dashboard first, then return to Creator Studio.","error");$("status").insertAdjacentHTML("beforeend",' <a href="/invincible/">Open Dashboard</a>')}
