import{initializeApp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import{getAuth}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import{estimateSeconds,parseSceneTable,splitVoiceoverScript}from"./scene-tools.js?v=1";
const config={apiKey:"AIzaSyBeVpUqcRO_VXfQrGVL5OaSGHKFB8XEQMc",authDomain:"life-by-adichimp.firebaseapp.com",projectId:"life-by-adichimp",storageBucket:"life-by-adichimp.firebasestorage.app",messagingSenderId:"761981819700",appId:"1:761981819700:web:8e88516817ed40b9866361"};
const auth=getAuth(initializeApp(config)),db=getFirestore(),$=id=>document.getElementById(id),projectId=new URLSearchParams(location.search).get("id");
let user=null,state={items:[]},project=null,saveTimer=null,focusState={sceneId:"",field:"voiceover"};
const focusFields=["voiceover","imagePrompt","videoPrompt"],focusLabels={voiceover:"Voiceover",imagePrompt:"Image Prompt",videoPrompt:"Video Prompt"};
const newId=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
function esc(value){const node=document.createElement("div");node.textContent=value??"";return node.innerHTML}
function status(message,type=""){$("status").textContent=message;$("status").className="sync-status "+type}
function sceneTemplate(scene,index){return '<article class="scene-card" data-id="'+scene.id+'"><div class="scene-top"><div class="scene-ident"><span class="drag-handle" draggable="true" title="Drag to reorder">⠿</span><span class="scene-number">'+String(index+1).padStart(2,"0")+'</span><label class="duration-wrap">Duration <input data-field="duration" type="number" min="1" max="60" value="'+Number(scene.duration||5)+'"> sec</label></div><div class="scene-actions"><button data-action="prompts">Build prompts</button><button data-action="up" aria-label="Move up">↑</button><button data-action="down" aria-label="Move down">↓</button><button data-action="duplicate">Duplicate</button><button data-action="collapse">Collapse</button><button data-action="delete" class="delete">Delete</button></div></div><div class="scene-body">'+field("Voiceover","voiceover",scene.voiceover,"Narration for this 5–10 second scene",true)+field("Image prompt","imagePrompt",scene.imagePrompt,"Still-image generation prompt")+field("Video prompt","videoPrompt",scene.videoPrompt,"Movement, camera and animation prompt")+'</div><div class="scene-footer"><div class="ready-checks"><label><input data-field="imageDone" type="checkbox" '+(scene.imageDone?'checked':'')+'> Image generated</label><label><input data-field="videoDone" type="checkbox" '+(scene.videoDone?'checked':'')+'> Video generated</label></div></div></article>'}
function field(label,name,value,voice=false){return '<div class="field"><div class="field-head"><label>'+label+'</label><button data-copy="'+name+'">Copy</button></div><textarea data-field="'+name+'" placeholder="'+(voice?'Narration for this 5–10 second scene':name==="imagePrompt"?'Describe composition, subject, light and style':'Describe camera, subject and environmental motion')+'">'+esc(value||"")+'</textarea></div>'}
function render(){if(!project)return;$("projectTitle").textContent=project.title||"Untitled project";document.title=(project.title||"Content Project")+" · Invincible";$("projectMeta").textContent=[project.format,project.series,project.stage].filter(Boolean).join(" · ");$("fullScript").value=project.script||"";$("visualStyle").value=project.visualStyle||"";$("aspectRatio").value=project.aspectRatio||"9:16";$("language").value=project.language||"";$("continuityNotes").value=project.continuityNotes||"";const scenes=project.scenes||[];$("sceneList").innerHTML=scenes.map(sceneTemplate).join("");$("emptyScenes").hidden=!!scenes.length;updateStats();bindDrag();document.querySelectorAll(".field textarea").forEach(autoGrow)}
function updateStats(){const scenes=project.scenes||[],ready=scenes.reduce((sum,x)=>sum+(x.imageDone?1:0)+(x.videoDone?1:0),0),possible=scenes.length*2;$("sceneCount").textContent=scenes.length;$("totalDuration").textContent=scenes.reduce((sum,x)=>sum+Number(x.duration||0),0)+"s";$("assetProgress").textContent=(possible?Math.round(ready/possible*100):0)+"%"}
async function save(){if(!user||!project)return;clearTimeout(saveTimer);status("Saving…");try{await setDoc(doc(db,"users",user.uid,"creator","main"),{items:state.items,updatedAt:serverTimestamp()},{merge:true});status("Saved to Firebase","ok")}catch(error){status("Save failed: "+error.message,"error")}}
function queueSave(){clearTimeout(saveTimer);status("Unsaved changes…");saveTimer=setTimeout(save,700)}
function autoGrow(area){area.style.height="auto";area.style.height=Math.max(96,area.scrollHeight)+"px"}
function makeScene(data={}){return{id:newId(),duration:Number(data.duration)||estimateSeconds(data.voiceover),voiceover:data.voiceover||"",imagePrompt:data.imagePrompt||"",videoPrompt:data.videoPrompt||"",imageDone:!!data.imageDone,videoDone:!!data.videoDone}}
function promptText(scene,type){const style=project.visualStyle||"clean cinematic realism",ratio=project.aspectRatio||"9:16",continuity=project.continuityNotes?" Continuity: "+project.continuityNotes:"";if(type==="image")return 'Create a '+ratio+' '+style+' visual that communicates this narration: "'+scene.voiceover+'". Clear subject, intentional composition, expressive lighting, no captions, no watermark.'+continuity;return 'Animate the supplied image for '+scene.duration+' seconds. Use natural subject and environmental motion with a controlled cinematic camera move. Preserve the exact composition, identity, clothing, colours and visual style. No morphing, no new objects, no text.'+continuity}
function moveScene(id,direction){const scenes=project.scenes,index=scenes.findIndex(x=>x.id===id),next=index+direction;if(index<0||next<0||next>=scenes.length)return;[scenes[index],scenes[next]]=[scenes[next],scenes[index]];render();save()}
function renderFocus(){const scene=project.scenes.find(x=>x.id===focusState.sceneId),sceneIndex=project.scenes.indexOf(scene);if(!scene)return closeFocus();$("focusScene").textContent="SCENE "+String(sceneIndex+1).padStart(2,"0");$("focusTitle").textContent=focusLabels[focusState.field];$("focusPosition").textContent=(sceneIndex+1)+" of "+project.scenes.length+" · "+(focusFields.indexOf(focusState.field)+1)+" of 3";$("focusTextarea").value=scene[focusState.field]||"";$("focusTabs").querySelectorAll("button").forEach(button=>button.classList.toggle("active",button.dataset.focusField===focusState.field));$("previousScene").disabled=sceneIndex===0;$("nextScene").disabled=sceneIndex===project.scenes.length-1;$("previousField").disabled=focusFields.indexOf(focusState.field)===0;$("nextField").disabled=focusFields.indexOf(focusState.field)===focusFields.length-1}
function openFocus(sceneId,field){focusState={sceneId,field};$("focusEditor").hidden=false;document.body.style.overflow="hidden";renderFocus();setTimeout(()=>$("focusTextarea").focus(),0)}
function closeFocus(){$("focusEditor").hidden=true;document.body.style.overflow="";if(project)render()}
function changeFocusField(direction){const next=focusFields.indexOf(focusState.field)+direction;if(focusFields[next]){focusState.field=focusFields[next];renderFocus();$("focusTextarea").focus()}}
function changeFocusScene(direction){const index=project.scenes.findIndex(x=>x.id===focusState.sceneId),next=project.scenes[index+direction];if(next){focusState.sceneId=next.id;renderFocus();$("focusTextarea").focus()}}
$("addScene").onclick=()=>{project.scenes.push(makeScene());render();save()};
$("splitScript").onclick=()=>{const text=$("fullScript").value.trim();if(!text)return status("Paste the full script first.","error");if(project.scenes.length&&!confirm("Replace the existing scenes with a new automatic split?"))return;project.script=text;project.scenes=splitVoiceoverScript(text,makeScene);project.scenes.forEach(scene=>{scene.imagePrompt=promptText(scene,"image");scene.videoPrompt=promptText(scene,"video")});render();save()};
$("importTable").onclick=()=>{try{const imported=parseSceneTable($("tableInput").value,makeScene),replace=$("importMode").value==="replace";if(replace&&project.scenes.length&&!confirm("Replace all existing scenes with the imported table?"))return;project.scenes=replace?imported:[...project.scenes,...imported];if(!project.script)project.script=project.scenes.map(x=>x.voiceover).filter(Boolean).join("\n\n");$("tableInput").value="";$("importFeedback").textContent=imported.length+" scenes imported and aligned successfully.";$("importFeedback").classList.add("toast");render();save()}catch(error){$("importFeedback").textContent=error.message;$("importFeedback").classList.remove("toast")}};
$("pasteClipboard").onclick=async()=>{try{$("tableInput").value=await navigator.clipboard.readText();$("importFeedback").textContent="Table pasted. Review it, then press Import table."}catch{$("importFeedback").textContent="Clipboard access was blocked. Long-press and paste into the box."}};
[$("fullScript"),$("visualStyle"),$("language"),$("continuityNotes"),$("aspectRatio")].forEach(input=>input.addEventListener("input",()=>{project[input.id==="fullScript"?"script":input.id]=input.value;queueSave()}));
$("sceneList").addEventListener("input",event=>{const card=event.target.closest(".scene-card"),scene=project.scenes.find(x=>x.id===card?.dataset.id);if(!scene||!event.target.dataset.field)return;scene[event.target.dataset.field]=event.target.type==="checkbox"?event.target.checked:event.target.dataset.field==="duration"?Number(event.target.value):event.target.value;if(event.target.tagName==="TEXTAREA")autoGrow(event.target);updateStats();queueSave()});
$("sceneList").addEventListener("focusin",event=>{if(event.target.tagName==="TEXTAREA"){const card=event.target.closest(".scene-card");openFocus(card.dataset.id,event.target.dataset.field)}});
$("sceneList").addEventListener("click",async event=>{const card=event.target.closest(".scene-card"),scene=project.scenes.find(x=>x.id===card?.dataset.id);if(!scene)return;const copy=event.target.closest("[data-copy]");if(copy){await navigator.clipboard.writeText(scene[copy.dataset.copy]||"");status("Copied to clipboard","ok");return}const action=event.target.closest("[data-action]")?.dataset.action;if(!action)return;if(action==="delete"){if(confirm("Delete this scene?")){project.scenes=project.scenes.filter(x=>x.id!==scene.id);render();save()}}else if(action==="duplicate"){const index=project.scenes.indexOf(scene);project.scenes.splice(index+1,0,makeScene(scene));render();save()}else if(action==="up")moveScene(scene.id,-1);else if(action==="down")moveScene(scene.id,1);else if(action==="collapse"){card.classList.toggle("collapsed");event.target.textContent=card.classList.contains("collapsed")?"Expand":"Collapse"}else if(action==="prompts"){scene.imagePrompt=promptText(scene,"image");scene.videoPrompt=promptText(scene,"video");render();save()}});
function bindDrag(){document.querySelectorAll(".scene-card").forEach(card=>{const handle=card.querySelector(".drag-handle");handle.ondragstart=event=>{card.classList.add("dragging");event.dataTransfer.setData("text/plain",card.dataset.id)};handle.ondragend=()=>card.classList.remove("dragging");card.ondragover=event=>{event.preventDefault();card.classList.add("drag-over")};card.ondragleave=()=>card.classList.remove("drag-over");card.ondrop=event=>{event.preventDefault();card.classList.remove("drag-over");const from=project.scenes.findIndex(x=>x.id===event.dataTransfer.getData("text/plain")),to=project.scenes.findIndex(x=>x.id===card.dataset.id);if(from>=0&&to>=0&&from!==to){const[moved]=project.scenes.splice(from,1);project.scenes.splice(to,0,moved);render();save()}}})}
$("closeFocus").onclick=closeFocus;$("previousField").onclick=()=>changeFocusField(-1);$("nextField").onclick=()=>changeFocusField(1);$("previousScene").onclick=()=>changeFocusScene(-1);$("nextScene").onclick=()=>changeFocusScene(1);$("focusTabs").onclick=event=>{const button=event.target.closest("[data-focus-field]");if(button){focusState.field=button.dataset.focusField;renderFocus();$("focusTextarea").focus()}};
$("focusTextarea").oninput=event=>{const scene=project.scenes.find(x=>x.id===focusState.sceneId);if(scene){scene[focusState.field]=event.target.value;queueSave()}};$("copyFocus").onclick=async()=>{await navigator.clipboard.writeText($("focusTextarea").value);status("Copied to clipboard","ok")};
document.addEventListener("keydown",event=>{if($("focusEditor").hidden)return;if(event.key==="Escape")closeFocus();else if(event.ctrlKey&&event.key==="ArrowLeft"){event.preventDefault();changeFocusField(-1)}else if(event.ctrlKey&&event.key==="ArrowRight"){event.preventDefault();changeFocusField(1)}else if(event.ctrlKey&&event.key==="ArrowUp"){event.preventDefault();changeFocusScene(-1)}else if(event.ctrlKey&&event.key==="ArrowDown"){event.preventDefault();changeFocusScene(1)}});
async function load(){if(!projectId){status("No project was selected.","error");return}await auth.authStateReady();user=auth.currentUser;if(!user){status("Sign in on the Dashboard first.","error");$("status").insertAdjacentHTML("beforeend",' <a href="/invincible/">Open Dashboard</a>');return}try{const snapshot=await getDoc(doc(db,"users",user.uid,"creator","main"));state=snapshot.exists()?{items:[],...snapshot.data()}:{items:[]};project=state.items.find(x=>x.id===projectId);if(!project){status("This content project was not found.","error");return}project.scenes=project.scenes||[];render();$("app").hidden=false;status("Synced · "+(user.email||"signed in"),"ok")}catch(error){status("Could not load project: "+error.message,"error")}}
load();
