import{useEffect,useMemo,useState}from'react';
import{taskSteps}from'../../task-model';
import'./today-plan.css';

export function TodayPlanCard({items,activeItemId,tasks,onAdd,onRemove,onActivate,onMove,onComplete,compact=false}){
 const[open,setOpen]=useState(false),[busy,setBusy]=useState('');
 useEffect(()=>{if(!open)return;const close=event=>event.key==='Escape'&&setOpen(false);window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open]);
 const choices=useMemo(()=>tasks.filter(task=>task.status!=='Done').flatMap(task=>{const steps=taskSteps(task).filter(step=>!step.done&&step.status!=='Done');return steps.length?steps.map(step=>({id:`${task.id}__${step.id}`,task,step,title:step.title||step.text||'Untitled step'})):[{id:`${task.id}__task`,task,step:null,title:task.title||'Untitled task'}]}).filter(choice=>!items.some(item=>item.id===choice.id)),[tasks,items]);
 const act=async(key,operation)=>{setBusy(key);try{await operation()}catch(error){console.error(error)}finally{setBusy('')}};
 return <><section className={'today-plan-card'+(compact?' is-compact':'')} aria-label="Today's plan"><header><div><small>TODAY'S PLAN</small><strong>{items.filter(item=>!item.done).length} remaining</strong></div><button type="button" onClick={()=>setOpen(true)} aria-label="Add sub-task to today's plan">＋ Add</button></header><div className="today-plan-list">{items.map((item,index)=><article key={item.id} className={(item.id===activeItemId?'is-active ':'')+(item.done?'is-done ':'')+(item.missing?'is-missing':'')}><button className="today-plan-check" type="button" disabled={item.done||item.missing||busy===item.id} aria-label={item.done?'Completed':`Complete ${item.title}`} onClick={()=>act(item.id,()=>onComplete(item.id))}>{item.done?'✓':index+1}</button><button className="today-plan-copy" type="button" disabled={item.done||item.missing} onClick={()=>onActivate(item.id)}><strong>{item.title}</strong><span>{item.projectTitle}{item.id===activeItemId?' · Active now':''}</span></button><div className="today-plan-actions"><button type="button" disabled={index===0} aria-label="Move up" onClick={()=>onMove(item.id,-1)}>↑</button><button type="button" disabled={index===items.length-1} aria-label="Move down" onClick={()=>onMove(item.id,1)}>↓</button><button type="button" aria-label="Remove from today" onClick={()=>onRemove(item.id)}>×</button></div></article>)}{!items.length&&<button className="today-plan-empty" type="button" onClick={()=>setOpen(true)}>Choose sub-tasks from any project for today.</button>}</div></section>{open&&<div className="today-plan-picker-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setOpen(false)}><section className="today-plan-picker" role="dialog" aria-modal="true" aria-labelledby="today-plan-picker-title"><header><div><small>BUILD TODAY</small><h2 id="today-plan-picker-title">Choose the next small actions</h2></div><button type="button" aria-label="Close" onClick={()=>setOpen(false)}>×</button></header><p>Select sub-tasks from different projects. The first one you activate runs the Focus timer.</p><div className="today-plan-choices">{choices.map(choice=><button key={choice.id} type="button" disabled={busy===choice.id} onClick={()=>act(choice.id,async()=>{await onAdd(choice.task.id,choice.step?.id||null,!activeItemId)})}><span><strong>{choice.title}</strong><small>{choice.task.title}</small></span><b>＋</b></button>)}{!choices.length&&<div className="today-plan-no-choices">Every available action is already in today’s plan.</div>}</div><button className="today-plan-picker-done" type="button" onClick={()=>setOpen(false)}>Done</button></section></div>}</>
}
