import{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{doc,onSnapshot,runTransaction,serverTimestamp}from'firebase/firestore';
import{db}from'../../firebase';
import{useAuth}from'../../AuthContext';
import{chooseFocusTask,stepFields,taskSteps}from'../../task-model';

export const todayPlanKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const itemId=(taskId,stepId)=>`${taskId}__${stepId||'task'}`;
const emptyPlan=dateKey=>({dateKey,items:[],activeItemId:null,initialized:true});

export function useTodayPlan(tasks=[],tasksReady=false){
 const{user}=useAuth(),dateKey=todayPlanKey(),[plan,setPlan]=useState(()=>emptyPlan(dateKey)),[ready,setReady]=useState(false),[error,setError]=useState(''),seeded=useRef(false);
 const planRef=useMemo(()=>user?doc(db,'users',user.uid,'dailyPlans',dateKey):null,[user?.uid,dateKey]);
 useEffect(()=>{setPlan(emptyPlan(dateKey));setReady(false);setError('');seeded.current=false;if(!planRef)return;return onSnapshot(planRef,snapshot=>{setPlan(snapshot.exists()?{...emptyPlan(dateKey),...snapshot.data(),items:Array.isArray(snapshot.data().items)?snapshot.data().items:[]}:emptyPlan(dateKey));setReady(true)},err=>{console.error(err);setError('Today plan could not sync.');setReady(true)})},[planRef,dateKey]);
 useEffect(()=>{if(!planRef||!ready||!tasksReady||seeded.current)return;seeded.current=true;runTransaction(db,async transaction=>{const snapshot=await transaction.get(planRef);if(snapshot.exists())return;const legacy=chooseFocusTask(tasks),step=taskSteps(legacy).find(item=>!item.done&&item.status!=='Done'),items=legacy?[{id:itemId(legacy.id,step?.id||null),taskId:legacy.id,stepId:step?.id||null,addedAt:Date.now()}]:[];transaction.set(planRef,{...emptyPlan(dateKey),items,activeItemId:items[0]?.id||null,updatedAt:serverTimestamp()})}).catch(err=>{console.error(err);setError('Today plan could not be started.')})},[planRef,ready,tasksReady,tasks,dateKey]);
 const items=useMemo(()=>plan.items.map(reference=>{const task=tasks.find(value=>value.id===reference.taskId),step=reference.stepId?taskSteps(task).find(value=>value.id===reference.stepId):null,missing=!task||Boolean(reference.stepId&&!step),done=missing?false:reference.stepId?Boolean(step.done||step.status==='Done'):task.status==='Done';return{...reference,task,step,missing,done,title:step?.title||step?.text||task?.title||'Unavailable item',projectTitle:task?.title||'Missing project'}}),[plan.items,tasks]);
 const activeItem=items.find(item=>item.id===plan.activeItemId&&!item.done&&!item.missing)||items.find(item=>!item.done&&!item.missing)||null;
 const updatePlan=useCallback(async updater=>{if(!planRef)throw Error('Sign in required');await runTransaction(db,async transaction=>{const snapshot=await transaction.get(planRef),current=snapshot.exists()?{...emptyPlan(dateKey),...snapshot.data()}:emptyPlan(dateKey),next=updater(current);transaction.set(planRef,{...next,dateKey,initialized:true,updatedAt:serverTimestamp()},{merge:true})})},[planRef,dateKey]);
 const addItem=useCallback(async(taskId,stepId=null,makeActive=true)=>{const id=itemId(taskId,stepId);await updatePlan(current=>{const items=Array.isArray(current.items)?current.items:[],exists=items.some(item=>item.id===id),nextItems=exists?items:[...items,{id,taskId,stepId:stepId||null,addedAt:Date.now()}];return{...current,items:nextItems,activeItemId:makeActive||!current.activeItemId?id:current.activeItemId}});return id},[updatePlan]);
 const completeItem=useCallback(async id=>{if(!planRef||!user)throw Error('Sign in required');const selected=items.find(item=>item.id===id);if(!selected?.task)throw Error('The original task is unavailable.');const taskRef=doc(db,'users',user.uid,'tasks',selected.taskId);await runTransaction(db,async transaction=>{const[planSnapshot,taskSnapshot]=await Promise.all([transaction.get(planRef),transaction.get(taskRef)]);if(!taskSnapshot.exists())throw Error('The original task no longer exists.');const task=taskSnapshot.data(),currentSteps=taskSteps(task);let patch;if(selected.stepId){if(!currentSteps.some(step=>step.id===selected.stepId))throw Error('The original sub-task no longer exists.');const nextSteps=currentSteps.map(step=>step.id===selected.stepId?{...step,status:'Done',done:true}:step),nextActive=nextSteps.find(step=>!step.done&&step.status!=='Done');patch={...stepFields(nextSteps),activeStepId:nextActive?.id||null,status:nextActive?(task.status==='Backlog'?'In Progress':task.status||'In Progress'):'Done'}}else patch={status:'Done'};transaction.set(taskRef,{...patch,updatedAt:serverTimestamp()},{merge:true});const current=planSnapshot.exists()?{...emptyPlan(dateKey),...planSnapshot.data()}:emptyPlan(dateKey),ordered=current.items||[],position=ordered.findIndex(item=>item.id===id),candidates=[...ordered.slice(position+1),...ordered.slice(0,position)].filter(item=>item.id!==id),activeItemId=candidates[0]?.id||null;transaction.set(planRef,{...current,activeItemId,initialized:true,updatedAt:serverTimestamp()},{merge:true})})},[planRef,user?.uid,items,dateKey]);
 return{dateKey,items,activeItem,activeItemId:activeItem?.id||null,ready,error,addItem,completeItem};
}
