// Browser integration against a controllable Firestore adapter; no production account needed.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const{chromium}=require('playwright');const root=path.resolve(__dirname,'..');
const fake=`export const db={};let listeners=[];const read=()=>JSON.parse(localStorage.getItem('test.garage')||'{}');const snapshot=()=>({exists:()=>!!localStorage.getItem('test.garage'),data:read,metadata:{hasPendingWrites:false,fromCache:false}});export const doc=(db,...parts)=>parts.join('/');export const serverTimestamp=()=>0;export function onSnapshot(ref,options,callback){listeners.push(callback);queueMicrotask(()=>callback(snapshot()));return()=>listeners=listeners.filter(fn=>fn!==callback)}export async function runTransaction(db,fn){if(window.failSave)throw{code:'permission-denied'};let next;const result=await fn({get:async()=>snapshot(),set:(ref,data)=>next=data});await new Promise(resolve=>setTimeout(resolve,20));localStorage.setItem('test.garage',JSON.stringify(next));listeners.forEach(callback=>callback(snapshot()));return result}`;
const server=http.createServer((req,res)=>{const url=req.url.split('?')[0];res.setHeader('Content-Type',url.endsWith('.js')||url.endsWith('.mjs')?'text/javascript':url.endsWith('.css')?'text/css':'text/html');if(url==='/test-firestore.mjs'){res.end(fake);return}if(url==='/invincible/shared/firebase-client.js'){res.end(`import{db}from'/test-firestore.mjs';export{db};export async function observeAuth(callback){window.testAuth=callback;queueMicrotask(()=>callback({uid:'google-once',email:'test@example.com'}));return()=>{}}export const storageError=e=>'Firebase denied access. Your change was not saved.';`);return}try{const file=path.join(root,url.replace(/^\/invincible\/?/,''));let content=fs.readFileSync(file.endsWith('/')?file+'index.html':file,'utf8');if(file.endsWith('garage.js'))content=content.replace('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js','/test-firestore.mjs');res.end(content)}catch{res.statusCode=404;res.end('Missing')}});
(async()=>{await new Promise(resolve=>server.listen(8766,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||'/root/.cache/ms-playwright/chromium_headless_shell-1161/chrome-linux/headless_shell',args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];page.on('pageerror',error=>errors.push(error.message));let confirms=0;page.on('dialog',async dialog=>{confirms++;await dialog.accept()});await page.route('https://**/*',route=>route.abort());await page.goto('http://127.0.0.1:8766/invincible/garage/index.html');await page.locator('#addVehicle:enabled').waitFor();
await page.locator('#addVehicle').click();await page.locator('#vehicleForm [name=name]').fill('Car');await page.locator('#vehicleForm [name=odometer]').fill('100');await page.locator('#vehicleForm button.primary').click();await page.locator('#vehicleDialog').waitFor({state:'hidden'});assert.equal(await page.locator('#vehicleName').innerText(),'Car');
await page.locator('#editVehicle').click();await page.locator('#vehicleForm [name=name]').fill('Edited car');await page.locator('#vehicleForm [name=odometer]').fill('125');await page.locator('#vehicleForm button.primary').click();await page.locator('#vehicleDialog').waitFor({state:'hidden'});assert.equal(await page.locator('#currentKm').innerText(),'125 km');await page.reload();await page.getByRole('heading',{name:'Edited car',exact:true}).waitFor();
await page.locator('#addService').click();await page.locator('#serviceForm [name=work]').fill('Oil change');await page.locator('#serviceForm [name=cost]').fill('500');await page.locator('#serviceForm button.primary').click();await page.locator('#serviceDialog').waitFor({state:'hidden'});await page.locator('#serviceList button.edit').click();assert.equal(await page.locator('#serviceForm [name=work]').inputValue(),'Oil change');await page.locator('#serviceForm [name=work]').fill('Oil and filter');await page.locator('#serviceForm button.primary').click();await page.locator('#serviceDialog').waitFor({state:'hidden'});assert.match(await page.locator('#serviceList').innerText(),/Oil and filter/);
await page.locator('#addReminder').click();await page.locator('#reminderForm [name=title]').fill('Insurance');await page.locator('#reminderForm button.primary').click();await page.locator('#reminderDialog').waitFor({state:'hidden'});await page.locator('#reminderList button.edit').click();assert.equal(await page.locator('#reminderForm [name=title]').inputValue(),'Insurance');await page.locator('#reminderForm [name=title]').fill('Insurance renewal');await page.locator('#reminderForm button.primary').click();await page.locator('#reminderDialog').waitFor({state:'hidden'});
await page.locator('#editVehicle').click();await page.locator('#vehicleForm [name=name]').fill('Rejected edit');await page.evaluate(()=>window.failSave=true);await page.locator('#vehicleForm button.primary').click();await page.locator('.garage-save-error').waitFor();assert.equal(await page.locator('#vehicleForm [name=name]').inputValue(),'Rejected edit');assert.equal(await page.locator('#vehicleName').innerText(),'Edited car');await page.evaluate(()=>window.failSave=false);await page.locator('#vehicleForm button.primary').click();await page.locator('#vehicleDialog').waitFor({state:'hidden'});
await page.locator('#reminderList button.delete').click();await page.locator('#reminderList button.delete').waitFor({state:'hidden'});assert.equal(confirms,1);await page.locator('#deleteVehicle').click();await page.locator('#app').waitFor({state:'hidden'});assert.equal(confirms,2);await page.reload();await page.locator('#addVehicle:enabled').waitFor();assert.equal(await page.locator('#vehicleSelect option').count(),0);
await page.evaluate(()=>window.testAuth(null));assert.equal(await page.locator('#addVehicle').isDisabled(),true);assert.match(await page.locator('#status').innerText(),/Sign in once/);assert.deepEqual(errors,[]);
// Inspect the real avatar CSS at two animation times; reduced-motion freezes it.
await page.setContent('<button class="ai-orb ai-dock-avatar" aria-label="AI"></button>');await page.addStyleTag({content:fs.readFileSync(path.join(root,'react/src/features/invincible-ai/invincible-ai-dock.css'),'utf8')});await page.waitForTimeout(100);const first=await page.locator('.ai-orb').evaluate(element=>getComputedStyle(element,'::before').transform);await page.waitForTimeout(300);const second=await page.locator('.ai-orb').evaluate(element=>getComputedStyle(element,'::before').transform);assert.notEqual(first,second);await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.ai-orb').evaluate(element=>getComputedStyle(element,'::before').animationName),'none');console.log('Garage add/edit/reload/delete, denied-write recovery, sign-out isolation, and avatar motion passed.');}finally{await browser.close();server.close()}})().catch(error=>{console.error(error);process.exitCode=1;server.close()});
