import{useEffect,useRef,useState}from'react';
import{collection,doc,onSnapshot,runTransaction,setDoc,writeBatch}from'firebase/firestore';
import{db}from'./firebase';
import{useAuth}from'./AuthContext';
import{useTasks}from'./useTasks';
import{FocusOrb}from'./FocusOrb';
import{chooseFocusTask,cleanStep,newId,stepFields,taskProgress,taskStatuses,taskSteps}from'./task-model';
const taskHref=task=>'/invincible/task/?id='+encodeURIComponent(task.id);
const formatTimer=value=>`${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`;
function Particles(){const canvas=useRef(null);useEffect(()=>{const c=canvas.current,ctx=c.getContext('2d');let frame;const points=Array.from({length:100},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.5,vy:(Math.random()-.5)*.5}));const resize=()=>{c.width=innerWidth;c.height=innerHeight};resize();const draw=()=>{ctx.clearRect(0,0,c.width,c.height);points.forEach((p,i)=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1;ctx.fillStyle='#00ffff';ctx.beginPath();ctx.arc(p.x,p.y,1.3,0,Math.PI*2);ctx.fill();for(const q of points.slice(i+1)){const distance=Math.hypot(p.x-q.x,p.y-q.y);if(distance<100){ctx.strokeStyle=`rgba(0,255,255,${1-distance/100})`;ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}});frame=requestAnimationFrame(draw)};draw();window.addEventListener('resize',resize);return()=>{cancelAnimationFrame(frame);window.removeEventListener('resize',resize)}},[]);return <canvas id="particles-js" ref={canvas}/>}
function TaskCard({task,selected,onSelect,onMove,onDropTarget}){
 const progress=taskProgress(task),position=taskStatuses.indexOf(task.status==='Today'?'Backlog':task.status),touch=useRef(null),hold=useRef(null),suppress=useRef(0);const[dragging,setDragging]=useState(false),[point,setPoint]=useState(null);
 useEffect(()=>()=>clearTimeout(hold.current),[]);
 const begin=()=>{if(!touch.current)return;touch.current.dragging=true;setDragging(true);setPoint({x:touch.current.x,y:touch.current.y});suppress.current=Date.now()+1000;navigator.vibrate?.(25)};
 const finish=event=>{clearTimeout(hold.current);const state=touch.current;touch.current=null;setDragging(false);setPoint(null);onDropTarget(null);if(!state?.dragging)return;event.preventDefault();suppress.current=Date.now()+350;const target=document.elementFromPoint(state.x,state.y)?.closest('[data-lane-status]');if(target)onMove(task.id,target.dataset.laneStatus)};
 const content=<><div className="card-nav"><button title="Move left" disabled={position<=0} onClick={event=>{event.stopPropagation();onMove(task.id,taskStatuses[position-1])}}>‹</button><button title="Move right" disabled={position>=2} onClick={event=>{event.stopPropagation();onMove(task.id,taskStatuses[position+1])}}>›</button></div><h3>{task.title||'Untitled task'}</h3><div className="subtask-count">{progress.total?`${progress.done}/${progress.total}`:'No'} subtasks</div><div className="card-progress" aria-hidden="true"><span style={{width:progress.pct+'%'}}/></div></>;
 return <><div className={'task-card '+(selected?'is-selected ':'')+(dragging?'dragging':'')} data-id={task.id} role="button" tabIndex={0} draggable={!matchMedia('(pointer: coarse)').matches} onKeyDown={event=>{if(event.key==='Enter')onSelect(task)}} onClick={event=>{if(Date.now()<suppress.current){event.preventDefault();return}onSelect(task)}} onDoubleClick={()=>onSelect(task,true)} onDragStart={event=>{event.dataTransfer.setData('text/plain',task.id);event.dataTransfer.effectAllowed='move';setDragging(true)}} onDragEnd={()=>{setDragging(false);onDropTarget(null)}} onPointerDown={event=>{if(event.pointerType==='mouse'||event.target.closest('button'))return;touch.current={x:event.clientX,y:event.clientY,startX:event.clientX,startY:event.clientY,dragging:false};event.currentTarget.setPointerCapture(event.pointerId);hold.current=setTimeout(begin,180)}} onPointerMove={event=>{const state=touch.current;if(!state)return;state.x=event.clientX;state.y=event.clientY;if(!state.dragging&&Math.hypot(state.x-state.startX,state.y-state.startY)>6)begin();if(state.dragging){event.preventDefault();setPoint({x:state.x,y:state.y});onDropTarget(document.elementFromPoint(state.x,state.y)?.closest('[data-lane-status]')?.dataset.laneStatus||null)}}} onPointerUp={finish} onPointerCancel={()=>{clearTimeout(hold.current);touch.current=null;setDragging(false);setPoint(null);onDropTarget(null)}}>{content}</div>{point&&dragging&&<div className="touch-drag-ghost task-card" style={{position:'fixed',left:point.x-100,top:point.y-40,width:200,pointerEvents:'none'}}>{task.title}</div>}</>
}
function NewTask({onSave,onClose}){const[title,setTitle]=useState(''),[description,setDescription]=useState(''),[status,setStatus]=useState('Backlog'),[steps,setSteps]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{const escape=event=>{if(event.key==='Escape'&&!busy)onClose()};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[busy,onClose]);return <div id="task-modal-overlay" className="modal-overlay open"><form className="modal" role="dialog" aria-modal="true" aria-label="New task" onSubmit={async event=>{event.preventDefault();if(busy)return;setBusy(true);try{await onSave(newId('t'),{title,description,status,...stepFields(steps)});onClose()}catch(err){setError('Task could not be saved.');setBusy(false)}}}><h2>New Task</h2><div className="modal-field"><label htmlFor="new-title">Title</label><input id="new-title" required autoFocus value={title} onChange={event=>setTitle(event.target.value)}/></div><div className="modal-field"><label htmlFor="new-description">Description</label><textarea id="new-description" rows="4" value={description} onChange={event=>setDescription(event.target.value)}/></div><div className="modal-field"><label htmlFor="new-status">Status</label><select id="new-status" value={status} onChange={event=>setStatus(event.target.value)}>{['Backlog','Today','In Progress','Done'].map(value=><option key={value}>{value}</option>)}</select></div><div className="modal-field"><label>Subtasks</label><div className="subtasks-list">{steps.map((step,i)=><div key={step.id} className="subtask-item"><input aria-label={'Step '+(i+1)+' complete'} type="checkbox" checked={step.done} onChange={event=>setSteps(items=>items.map(item=>item.id===step.id?{...item,done:event.target.checked,status:event.target.checked?'Done':'Not Started'}:item))}/><input aria-label={'Step '+(i+1)} value={step.title} onChange={event=>setSteps(items=>items.map(item=>item.id===step.id?{...item,title:event.target.value}:item))}/><button type="button" className="delete-subtask-btn" onClick={()=>setSteps(items=>items.filter(item=>item.id!==step.id))}>×</button></div>)}</div><button type="button" className="modal-button save" onClick={()=>setSteps(items=>[...items,cleanStep({id:newId('s'),title:''},items.length)])}>+ Add Subtask</button></div>{error&&<p role="alert">{error}</p>}<div className="modal-buttons"><button className="modal-button save" disabled={busy}>{busy?'Saving…':'Save'}</button><button type="button" className="modal-button close" disabled={busy} onClick={onClose}>Close</button></div></form></div>}
export function DashboardPage(){
 const{user,logout}=useAuth();const{tasks,ready,error,saveTask}=useTasks();const[selected,setSelected]=useState(null),[seconds,setSeconds]=useState(1500),[running,setRunning]=useState(false),[now,setNow]=useState(new Date()),[streaks,setStreaks]=useState({}),[creating,setCreating]=useState(false),[message,setMessage]=useState(''),[expanded,setExpanded]=useState(null),[target,setTarget]=useState(null),[desktop,setDesktop]=useState(matchMedia('(min-width:1025px)').matches),[importing,setImporting]=useState(false),[syncError,setSyncError]=useState(''),[orbTheme,setOrbTheme]=useState(()=>localStorage.getItem('invincible-orb-theme')||'gold');const toastTimer=useRef(null),resetting=useRef(new Set());
 const focus=tasks.find(task=>task.id===selected)||chooseFocusTask(tasks),progress=taskProgress(focus),steps=taskSteps(focus),next=steps.find(step=>!step.done&&step.status!=='Done'),hasDone=tasks.some(task=>task.status==='Done');
 const notify=text=>{setMessage(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setMessage(''),2400)};
 useEffect(()=>{const viewport=matchMedia('(min-width:1025px)'),resize=event=>{setDesktop(event.matches);setExpanded(null)};viewport.addEventListener('change',resize);const clock=setInterval(()=>setNow(new Date()),1000);return()=>{clearInterval(clock);clearTimeout(toastTimer.current);viewport.removeEventListener('change',resize)}},[]);
 useEffect(()=>{if(!running)return;const clock=setInterval(()=>setSeconds(value=>Math.max(0,value-1)),1000);document.body.classList.add('desktop-focus-active');return()=>{clearInterval(clock);document.body.classList.remove('desktop-focus-active')}},[running]);
 useEffect(()=>{if(running&&seconds===0){setRunning(false);notify('Focus session complete.')}},[seconds,running]);
 const focusId=focus?.id,lastFocus=useRef(focusId);useEffect(()=>{if(lastFocus.current!==focusId){setSeconds(1500);if(selected===null)setRunning(false);lastFocus.current=focusId}},[focusId,selected]);
 useEffect(()=>{if(!user)return;return onSnapshot(collection(db,'users',user.uid,'streaks'),snapshot=>{const values={};snapshot.docs.forEach(item=>{values[item.id]=item.data();const record=item.data();if(Number(record.value)&&Date.now()-Number(record.updatedAt||0)>86400000&&!resetting.current.has(item.id)){resetting.current.add(item.id);setDoc(item.ref,{value:0},{merge:true}).catch(()=>setSyncError('Streak sync failed.')).finally(()=>resetting.current.delete(item.id))}});setStreaks(values)},err=>{console.error(err);setSyncError('Streak sync failed.')})},[user?.uid]);
 const mutate=async(id,patch)=>{try{await saveTask(id,patch);return true}catch(err){console.error(err);notify('Update failed. Your saved task is unchanged.');return false}};
 const move=(id,status)=>mutate(id,{status});
 const select=(task,start=false)=>{if(!desktop){location.href=taskHref(task);return}setSelected(task.id);setRunning(start)};
 const importLegacy=async()=>{if(!confirm('Merge tasks, streaks and countdowns from the old dashboard into this account?'))return;setImporting(true);try{const response=await fetch('https://script.google.com/macros/s/AKfycbyFO00mXXPQvrq7mSNhlmaaSerOlDIfhNeMhkT0De__97vTTNZ0CKxsTDfLtkCVW_h8JA/exec',{method:'POST',body:JSON.stringify({action:'getAll',body:{}})}),json=await response.json();if(!json.ok)throw Error(json.error);const old=json.data,records=[...(old.tasks||[]).filter(item=>item.id).map(item=>({path:'tasks',id:item.id,data:item})),...(old.countdowns||[]).filter(item=>item.id).map(item=>({path:'countdowns',id:item.id,data:item}))];if(old.streaks)for(const type of ['body','mind','spirit']){const item=old.streaks[type];records.push({path:'streaks',id:type,data:{value:typeof item==='number'?item:item?.streak??item?.value??item?.count??0,updatedAt:Date.now()}})}for(let start=0;start<records.length;start+=450){const batch=writeBatch(db);records.slice(start,start+450).forEach(record=>batch.set(doc(db,'users',user.uid,record.path,record.id),record.data,{merge:true}));await batch.commit()}notify('Old dashboard data imported.')}catch(err){console.error(err);notify('Old data could not be imported.')}finally{setImporting(false)}};
 return <><Particles/><div id="dashboard"><div id="top-bar"><div id="controls-row"><div className="streaks"><div className="streak-buttons">{[['body','dumbbell'],['mind','brain'],['spirit','spa']].map(([type,icon])=><button key={type} className="streak-button" title={type} onClick={async()=>{try{await runTransaction(db,async transaction=>{const ref=doc(db,'users',user.uid,'streaks',type),snapshot=await transaction.get(ref),old=snapshot.data()||{};transaction.set(ref,{value:Date.now()-Number(old.updatedAt||0)>86400000?1:Number(old.value||0)+1,updatedAt:Date.now()},{merge:true})})}catch(err){notify('Streak could not be saved.')}}}><i className={'fas fa-'+icon}/><span className="streak-number">{Number(streaks[type]?.value||0)}</span></button>)}</div></div></div><div id="time-and-date-row"><div className="header-clock"><div className="time">{now.toLocaleTimeString([],{hour12:false})}</div><div className="date">{now.toLocaleDateString([],{weekday:'short',day:'2-digit',month:'short',year:'numeric'})}</div></div><div className="controls"><details id="user-bar" className="visible"><summary title="Cloud sync and account"><i className="fas fa-cloud"/><span>{error||syncError?'Sync error':ready?'Synced':'Loading…'}</span></summary><div className="sync-menu"><span id="user-email">{user.email}</span><button disabled={importing} onClick={importLegacy}>{importing?'Importing…':'Import old data'}</button><button onClick={logout}>Sign out</button></div></details><button className="add-task-btn" onClick={()=>setCreating(true)}>＋ New Task</button></div></div></div>{(error||syncError)&&<p className="dashboard-error" role="alert">{error||syncError}</p>}
 <div id="mission-layout"><section id="focus-panel" className="focus-panel" aria-live="polite"><div className="focus-orb-stage"><div className="hud-readout hud-next"><small>Next physical action</small><strong id="focus-next">{next?.title||next?.text||(focus?'Add the first small step in the workspace.':'Nothing queued.')}</strong></div><div className="hud-readout hud-progress"><small>Progress</small><strong id="focus-percent">{focus?progress.pct:hasDone?100:0}%</strong></div><div className="hud-readout hud-subtasks"><small>Subtasks</small><strong id="focus-subtasks">{progress.done}/{progress.total}</strong></div><div className="focus-orb"><FocusOrb theme={orbTheme}/><div className="orb-copy"><div className="focus-kicker">Current task</div><h2 className="focus-title">{!ready?'Loading your next move…':focus?.title||(hasDone?'All active tasks are clear.':'Create one clear task for today.')}</h2></div><button type="button" className={'orb-theme-button theme-'+orbTheme} aria-label={'Orb theme: '+orbTheme+'. Change theme'} title="Change orb theme" onClick={()=>setOrbTheme(value=>{const themes=['cyan','emerald','gold'],next=themes[(themes.indexOf(value)+1)%themes.length];localStorage.setItem('invincible-orb-theme',next);return next})}><span aria-hidden="true">◐</span>{orbTheme}</button></div></div>
 <div className="focus-control-cluster"><div className="focus-eyebrow-row"><div className="focus-kicker">Focus controls</div><span className="focus-state">{running?'In focus':'Ready'}</span></div><div className="focus-session"><span className="focus-timer">{formatTimer(seconds)}</span><button className={'focus-start '+(running?'is-running':'')} disabled={!focus} onClick={()=>{if(!seconds)setSeconds(1500);setRunning(value=>!value)}}>{running?'PAUSE':'START FOCUS'}</button></div><div className="focus-actions"><button className="focus-quick done" disabled={!focus} onClick={async()=>{if(await mutate(focus.id,{status:'Done',...stepFields(steps.map(step=>({...step,done:true,status:'Done'})))})){setSelected(null);notify('Task complete. Next mission selected.')}}}>Done</button><button className="focus-quick blocked" disabled={!focus} onClick={async()=>{const reason=prompt('What is blocking this task?');if(reason===null)return;if(await mutate(focus.id,{blockedReason:reason.trim(),status:'Backlog'})){setRunning(false);notify('Blocker saved.')}}}>Blocked</button><button className="focus-quick" disabled={!focus} onClick={async()=>{const note=prompt('Add a quick note for this task:','');if(!note?.trim())return;if(await mutate(focus.id,{quickNotes:[...(focus.quickNotes||[]),{text:note.trim(),createdAt:Date.now()}]}))notify('Note saved to this task.')}}>Add Note</button></div><div className="focus-links">{focus?<a className="focus-action" href={taskHref(focus)}>Continue</a>:<button className="focus-action" onClick={()=>setCreating(true)}>New Task</button>}<button className="focus-change" onClick={()=>{setRunning(false);setSeconds(1500);setSelected(null)}}>Auto pick</button></div></div></section>
 <div id="kanban-container" className={expanded?'has-expanded':''}>{taskStatuses.map((status,i)=>{const cards=tasks.filter(task=>task.id!==focus?.id&&(task.status==='Today'?'Backlog':task.status||'Backlog')===status);return <div key={status} id={['kanban-backlog','kanban-in-progress','kanban-done'][i]} data-lane-status={status} className={'kanban-column '+(expanded===status?'is-expanded ':'')+(target===status?'is-drag-target touch-drop-target':'')} onDragOver={event=>{event.preventDefault();setTarget(status)}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget))setTarget(null)}} onDrop={event=>{event.preventDefault();setTarget(null);const id=event.dataTransfer.getData('text/plain');if(id)move(id,status)}}><h2 role="button" tabIndex={0} aria-expanded={expanded===status} data-count={cards.length} onClick={()=>{if(!desktop)setExpanded(value=>value===status?null:status)}} onKeyDown={event=>{if(!desktop&&(event.key==='Enter'||event.key===' ')){event.preventDefault();setExpanded(value=>value===status?null:status)}}}>{status==='Done'?'Completed':status}</h2><div className="task-list" data-status={status}>{cards.map(task=><TaskCard key={task.id} task={task} selected={selected===task.id} onSelect={select} onMove={move} onDropTarget={setTarget}/>)}</div></div>})}</div></div></div>{creating&&<NewTask onSave={saveTask} onClose={()=>setCreating(false)}/>}<div id="dashboard-toast" className={'toast '+(message?'show':'')} role="status">{message}</div></>
}
