import{useEffect,useMemo,useState}from'react';
import{doc,getDoc,onSnapshot,serverTimestamp,setDoc}from'firebase/firestore';
import{useAuth}from'./AuthContext';
import{db}from'./firebase';
import'./finance.css';

const defaultChecklist=[['rent','Rent'],['maid','Maid'],['internet','Internet'],['electricity','Electricity'],['upi','HDFC UPI due'],['cc','Credit-card due']].map(([id,label])=>({id,label,done:false}));
const wealthSeries={cash:{label:'Cash & bank',color:'#62e5f2'},portfolio:{label:'Stock portfolio',color:'#a98bff'},mutualFunds:{label:'Mutual funds',color:'#ff8cc8'},pf:{label:'PF',color:'#ffc963'},other:{label:'Other assets',color:'#72ddb0'},liabilities:{label:'Liabilities',color:'#ff7c83'},netWorth:{label:'Net worth',color:'#fff0aa'}};
const categoryOptions=[['cash','Cash & bank'],['portfolio','Stock portfolio'],['mutualFunds','Mutual funds'],['pf','PF'],['other','Other asset'],['liabilities','Liability']];
const monthKey=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;
const newId=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const freshState=()=>({accounts:[],transactions:[],checklist:defaultChecklist.map(item=>({...item}))});
const normalizeState=data=>({accounts:Array.isArray(data?.accounts)?data.accounts:[],transactions:Array.isArray(data?.transactions)?data.transactions:[],checklist:Array.isArray(data?.checklist)?data.checklist:defaultChecklist.map(item=>({...item}))});
const accountCategory=account=>account.category||(account.type==='liability'?'liabilities':/portfolio|stock|share|zerodha|kite/i.test(account.name||'')?'portfolio':'cash');
const money=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(value)||0);
const compact=value=>{const amount=Math.abs(value);return `${value<0?'−':''}₹${amount>=1e7?(amount/1e7).toFixed(1)+'Cr':amount>=1e5?(amount/1e5).toFixed(1)+'L':amount>=1e3?Math.round(amount/1e3)+'K':Math.round(amount)}`};
function totalsFor(accounts=[]){const result={cash:0,portfolio:0,mutualFunds:0,pf:0,other:0,liabilities:0};accounts.forEach(account=>{const key=accountCategory(account);result[key]=(result[key]||0)+Number(account.balance||0)});result.assets=result.cash+result.portfolio+result.mutualFunds+result.pf+result.other;result.netWorth=result.assets-result.liabilities;return result}
function getSavedSeries(){try{const saved=JSON.parse(localStorage.getItem('invincible.wealthSeries'));if(Array.isArray(saved)&&saved.some(key=>wealthSeries[key]))return saved.filter(key=>wealthSeries[key])}catch{}return Object.keys(wealthSeries)}
function defaultTransactionDate(cursor){const today=new Date();return monthKey(today)===monthKey(cursor)?`${monthKey(today)}-${String(today.getDate()).padStart(2,'0')}`:`${monthKey(cursor)}-01`}

function FinanceModal({title,onClose,children}){return <div className="finance-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="finance-modal" role="dialog" aria-modal="true" aria-label={title}><header><div><span className="finance-eyebrow">MONTHLY FINANCE</span><h2>{title}</h2></div><button type="button" className="finance-icon-button" aria-label="Close" onClick={onClose}>×</button></header>{children}</section></div>}

function WealthTrend({history,selected,onSelected}){
 const keys=selected.filter(key=>wealthSeries[key]),width=900,height=278,padding={left:72,right:20,top:22,bottom:42};
 const values=history.flatMap(item=>keys.map(key=>Number(item[key]||0))),minimum=Math.min(0,...values),maximum=Math.max(1,...values),range=maximum-minimum||1;
 const x=index=>padding.left+(history.length===1?(width-padding.left-padding.right)/2:index*(width-padding.left-padding.right)/(history.length-1));
 const y=value=>padding.top+(maximum-value)*(height-padding.top-padding.bottom)/range;
 const presets={cash:['cash'],investments:['portfolio','mutualFunds','pf'],full:Object.keys(wealthSeries)};
 const preset=Object.entries(presets).find(([,values])=>values.length===keys.length&&values.every(key=>keys.includes(key)))?.[0];
 const choose=values=>{onSelected(values);localStorage.setItem('invincible.wealthSeries',JSON.stringify(values))};
 return <section className="finance-panel finance-wealth-panel"><div className="finance-panel-heading"><div><span className="finance-eyebrow">12-MONTH VIEW</span><h2>Wealth trend</h2><p>Select only the balances you want to compare.</p></div><div className="finance-presets" aria-label="Wealth chart presets">{Object.entries({cash:'Cash',investments:'Investments',full:'Full wealth'}).map(([key,label])=><button key={key} type="button" className={preset===key?'active':''} onClick={()=>choose(presets[key])}>{label}</button>)}</div></div>
  <div className="finance-series-picker">{Object.entries(wealthSeries).map(([key,series])=><button key={key} type="button" className={keys.includes(key)?'selected':''} style={{'--series':series.color}} onClick={()=>choose(keys.includes(key)?keys.filter(value=>value!==key):[...keys,key])}><i/>{series.label}</button>)}</div>
  {!history.length||!keys.length?<p className="finance-empty">Add balances in more than one month to build your wealth trend.</p>:<div className="finance-wealth-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Wealth trend for selected categories"><g className="finance-grid-lines">{[0,.25,.5,.75,1].map(mark=>{const value=maximum-mark*range,point=y(value);return <g key={mark}><line x1={padding.left} y1={point} x2={width-padding.right} y2={point}/><text x={padding.left-10} y={point+4} textAnchor="end">{compact(value)}</text></g>})}</g>{keys.map(key=><g key={key} className="finance-wealth-series" style={{'--line':wealthSeries[key].color}}><polyline points={history.map((item,index)=>`${x(index)},${y(item[key]||0)}`).join(' ')}/>{history.map((item,index)=><circle key={item.key} cx={x(index)} cy={y(item[key]||0)} r="4"><title>{item.label} · {wealthSeries[key].label}: {money(item[key])}</title></circle>)}</g>)}{history.map((item,index)=><text key={item.key} className="finance-month-axis" x={x(index)} y={height-13} textAnchor="middle">{item.short}</text>)}</svg></div>}
 </section>
}

export function FinancePage(){
 const{user}=useAuth(),[cursor,setCursor]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[state,setState]=useState(freshState),[history,setHistory]=useState([]),[status,setStatus]=useState('Opening this month…'),[statusType,setStatusType]=useState(''),[modal,setModal]=useState(''),[checkLabel,setCheckLabel]=useState(''),[selectedSeries,setSelectedSeries]=useState(getSavedSeries),[accountDraft,setAccountDraft]=useState({name:'',category:'cash',balance:''}),[transactionDraft,setTransactionDraft]=useState({description:'',type:'expense',amount:'',date:defaultTransactionDate(new Date())});
 const key=monthKey(cursor),monthLabel=cursor.toLocaleDateString([],{month:'long',year:'numeric'}),totals=useMemo(()=>{const balances=totalsFor(state.accounts),income=state.transactions.filter(item=>item.type==='income').reduce((sum,item)=>sum+Number(item.amount||0),0),expense=state.transactions.filter(item=>item.type==='expense').reduce((sum,item)=>sum+Number(item.amount||0),0);return{...balances,income,expense,flow:income-expense}},[state]),completed=state.checklist.filter(item=>item.done).length;
 useEffect(()=>{if(!user)return;setStatus('Loading month…');setStatusType('');const ref=doc(db,'users',user.uid,'finance',key),stop=onSnapshot(ref,async snapshot=>{setState(snapshot.exists()?normalizeState(snapshot.data()):freshState());setStatus(`Synced · ${user.email||'signed in'}`);setStatusType('ok');try{const months=Array.from({length:12},(_,index)=>new Date(cursor.getFullYear(),cursor.getMonth()-11+index,1)),snapshots=await Promise.all(months.map(date=>getDoc(doc(db,'users',user.uid,'finance',monthKey(date)))));setHistory(snapshots.map((item,index)=>{if(!item.exists())return null;const totals=totalsFor(item.data().accounts||[]),date=months[index];return{...totals,key:monthKey(date),label:date.toLocaleDateString([],{month:'long',year:'numeric'}),short:date.toLocaleDateString([],{month:'short'})}}).filter(Boolean))}catch(error){console.error(error)}},error=>{console.error(error);setStatus('Finance sync failed.');setStatusType('error')});return stop},[user,key]);
 const save=async next=>{setState(next);setStatus('Saving…');setStatusType('');try{await setDoc(doc(db,'users',user.uid,'finance',key),{...next,updatedAt:serverTimestamp()},{merge:true});setStatus('Saved to Firebase');setStatusType('ok')}catch(error){console.error(error);setStatus('Could not save this change.');setStatusType('error')}};
 const moveMonth=amount=>setCursor(value=>new Date(value.getFullYear(),value.getMonth()+amount,1));
 const openTransaction=(type='expense',description='')=>{setTransactionDraft({description,type,amount:'',date:defaultTransactionDate(cursor)});setModal('transaction')};
 const addAccount=async event=>{event.preventDefault();const account={id:newId(),name:accountDraft.name.trim(),category:accountDraft.category,type:accountDraft.category==='liabilities'?'liability':'asset',balance:Number(accountDraft.balance)};await save({...state,accounts:[...state.accounts,account]});setAccountDraft({name:'',category:'cash',balance:''});setModal('')};
 const addTransaction=async event=>{event.preventDefault();const transaction={id:newId(),description:transactionDraft.description.trim(),type:transactionDraft.type,amount:Number(transactionDraft.amount),date:transactionDraft.date};await save({...state,transactions:[...state.transactions,transaction]});setModal('')};
 const addChecklist=async event=>{event.preventDefault();const label=checkLabel.trim();if(!label)return;setCheckLabel('');await save({...state,checklist:[...state.checklist,{id:newId(),label,done:false}]})};
 const remove=(kind,id)=>save({...state,[kind]:state[kind].filter(item=>item.id!==id)});
 return <div className="finance-react"><header className="finance-hero"><div className="finance-hero-copy"><span className="finance-eyebrow">MONTHLY OPERATING CHECK</span><h1>{monthLabel} finances</h1><p>Record salary, close the bills due around month-end, and see exactly what remains.</p></div><div className="finance-month-nav"><button type="button" onClick={()=>moveMonth(-1)} aria-label="Previous month">‹</button><strong>{monthLabel}</strong><button type="button" onClick={()=>moveMonth(1)} aria-label="Next month">›</button></div><div className="finance-hero-actions"><button type="button" className="finance-secondary" onClick={()=>{setAccountDraft({name:'',category:'cash',balance:''});setModal('account')}}>+ Account</button><button type="button" className="finance-primary" onClick={()=>openTransaction('income','Salary')}>+ Salary</button><button type="button" className="finance-primary finance-cyan" onClick={()=>openTransaction()}>+ Cash flow</button></div></header>
  <div className={`finance-sync ${statusType}`}><span/><span>{status}</span></div>
  <main className="finance-main"><section className="finance-summary-grid"><article className="finance-summary asset"><span>Total assets</span><strong>{money(totals.assets)}</strong><small>Across this month’s balances</small></article><article className="finance-summary liability"><span>Total liabilities</span><strong>{money(totals.liabilities)}</strong><small>Outstanding balances</small></article><article className="finance-summary net"><span>Net worth</span><strong>{money(totals.netWorth)}</strong><small>Assets minus liabilities</small></article><article className={`finance-summary flow ${totals.flow<0?'negative':''}`}><span>Monthly cash flow</span><strong>{money(totals.flow)}</strong><small>{money(totals.income)} in · {money(totals.expense)} out</small></article></section>
   <WealthTrend history={history} selected={selectedSeries} onSelected={setSelectedSeries}/>
   <div className="finance-layout"><div className="finance-main-column"><section className="finance-panel"><div className="finance-panel-heading"><div><span className="finance-eyebrow">BALANCES</span><h2>Accounts & investments</h2></div><button type="button" className="finance-text-button" onClick={()=>{setAccountDraft({name:'',category:'cash',balance:''});setModal('account')}}>Add account</button></div>{state.accounts.length?<div className="finance-account-grid">{state.accounts.map(account=>{const key=accountCategory(account);return <article key={account.id} className={`finance-account ${key==='liabilities'?'liability':'asset'}`} style={{'--account-accent':wealthSeries[key]?.color}}><div><span className="finance-account-type">{wealthSeries[key]?.label||'Asset'}</span><button type="button" className="finance-remove" aria-label={`Remove ${account.name}`} onClick={()=>remove('accounts',account.id)}>×</button></div><h3>{account.name}</h3><strong>{money(account.balance)}</strong></article>})}</div>:<p className="finance-empty">Add bank, investment, PF, or liability balances for this month.</p>}</section>
    <section className="finance-panel"><div className="finance-panel-heading"><div><span className="finance-eyebrow">ACTIVITY</span><h2>Income & expenses</h2></div><button type="button" className="finance-text-button" onClick={()=>openTransaction()}>Add entry</button></div><div className="finance-flow-chart" aria-label="Income and expense chart"><div className="finance-bar-zone">{[['income',totals.income],['expense',totals.expense]].map(([type,value])=>{const max=Math.max(totals.income,totals.expense,1),height=Math.max(4,Math.round(value/max*150));return <div key={type} className={`finance-bar ${type}`} style={{height}}><span>{money(value)}</span><small>{type}</small></div>})}</div></div>{state.transactions.length?<div className="finance-transactions">{[...state.transactions].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(item=><article key={item.id}><div><strong>{item.description}</strong><small>{item.date} · {item.type}</small></div><div><strong className={item.type}>{item.type==='expense'?'−':'+'}{money(item.amount)}</strong><button type="button" className="finance-remove" aria-label={`Remove ${item.description}`} onClick={()=>remove('transactions',item.id)}>×</button></div></article>)}</div>:<p className="finance-empty">Add your net salary and the month’s outgoing payments.</p>}</section></div>
    <aside className="finance-panel finance-checklist-panel"><div className="finance-panel-heading"><div><span className="finance-eyebrow">MONTH-END</span><h2>Bill checklist</h2></div><span className="finance-progress">{completed}/{state.checklist.length}</span></div><div className="finance-progress-track"><span style={{width:`${state.checklist.length?completed/state.checklist.length*100:0}%`}}/></div><div className="finance-checklist">{state.checklist.map(item=><label key={item.id} className={item.done?'done':''}><input type="checkbox" checked={item.done} onChange={()=>save({...state,checklist:state.checklist.map(entry=>entry.id===item.id?{...entry,done:!entry.done}:entry)})}/><span>{item.label}</span><button type="button" className="finance-remove" aria-label={`Remove ${item.label}`} onClick={event=>{event.preventDefault();remove('checklist',item.id)}}>×</button></label>)}</div><form className="finance-inline-form" onSubmit={addChecklist}><input value={checkLabel} onChange={event=>setCheckLabel(event.target.value)} maxLength="80" placeholder="Add bill or reminder"/><button>Add</button></form></aside></div>
  </main>
  {modal==='account'&&<FinanceModal title="Add account balance" onClose={()=>setModal('')}><form className="finance-form" onSubmit={addAccount}><label>Account name<input autoFocus required maxLength="60" value={accountDraft.name} onChange={event=>setAccountDraft(value=>({...value,name:event.target.value}))} placeholder="e.g. SBI Savings"/></label><label>Category<select value={accountDraft.category} onChange={event=>setAccountDraft(value=>({...value,category:event.target.value}))}>{categoryOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Current balance<input required type="number" min="0" step="0.01" value={accountDraft.balance} onChange={event=>setAccountDraft(value=>({...value,balance:event.target.value}))} placeholder="0"/></label><div className="finance-form-actions"><button type="button" className="finance-secondary" onClick={()=>setModal('')}>Cancel</button><button className="finance-primary">Save account</button></div></form></FinanceModal>}
  {modal==='transaction'&&<FinanceModal title="Add cash-flow entry" onClose={()=>setModal('')}><form className="finance-form" onSubmit={addTransaction}><label>Description<input autoFocus required maxLength="80" value={transactionDraft.description} onChange={event=>setTransactionDraft(value=>({...value,description:event.target.value}))} placeholder="e.g. Salary or credit-card bill"/></label><label>Type<select value={transactionDraft.type} onChange={event=>setTransactionDraft(value=>({...value,type:event.target.value}))}><option value="income">Income</option><option value="expense">Expense</option></select></label><label>Amount<input required type="number" min="0.01" step="0.01" value={transactionDraft.amount} onChange={event=>setTransactionDraft(value=>({...value,amount:event.target.value}))}/></label><label>Date<input required type="date" value={transactionDraft.date} onChange={event=>setTransactionDraft(value=>({...value,date:event.target.value}))}/></label><div className="finance-form-actions"><button type="button" className="finance-secondary" onClick={()=>setModal('')}>Cancel</button><button className="finance-primary">Save entry</button></div></form></FinanceModal>}
 </div>
}
export default FinancePage;
