import {useEffect,useMemo,useRef,useState} from 'react';
import {doc,getDoc,onSnapshot,runTransaction,serverTimestamp} from 'firebase/firestore';
import {useAuth} from './AuthContext';
import {db} from './firebase';
import './finance.css';
import {mergeFinanceChange} from './finance-storage';

const defaultChecklist=[['rent','Rent'],['maid','Maid'],['internet','Internet'],['electricity','Electricity']].map(([id,label])=>({id,label,done:false}));
const wealthSeries={
 cash:{label:'Cash & bank',color:'#62e5f2'},portfolio:{label:'Stocks',color:'#a98bff'},mutualFunds:{label:'Mutual funds',color:'#ff8cc8'},nps:{label:'NPS',color:'#ffc963'},pf:{label:'PF',color:'#e7a85f'},other:{label:'Other assets',color:'#72ddb0'},liabilities:{label:'Liabilities',color:'#ff7c83'},netWorth:{label:'Net worth',color:'#fff0aa'}
};
const categoryOptions=[['cash','Cash & bank'],['portfolio','Stocks'],['mutualFunds','Mutual funds'],['nps','NPS'],['pf','PF'],['other','Other asset'],['liabilities','Liability']];
const monthKey=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;
const newId=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const freshState=()=>({accounts:[],bills:[],transactions:[],checklist:defaultChecklist.map(item=>({...item}))});
const normalizeState=data=>({accounts:Array.isArray(data?.accounts)?data.accounts:[],bills:Array.isArray(data?.bills)?data.bills:[],transactions:Array.isArray(data?.transactions)?data.transactions:[],checklist:Array.isArray(data?.checklist)?data.checklist:defaultChecklist.map(item=>({...item})),initializedFrom:data?.initializedFrom||''});
const accountCategory=account=>account.category||(account.type==='liability'?'liabilities':/portfolio|stock|share|zerodha|kite/i.test(account.name||'')?'portfolio':'cash');
const money=(value,decimals=0)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:decimals,maximumFractionDigits:decimals}).format(Number(value)||0);
const compact=value=>{const amount=Math.abs(value);return `${value<0?'−':''}₹${amount>=1e7?(amount/1e7).toFixed(1)+'Cr':amount>=1e5?(amount/1e5).toFixed(1)+'L':amount>=1e3?Math.round(amount/1e3)+'K':Math.round(amount)}`};
const itemHasNumber=value=>value!==null&&value!==''&&Number.isFinite(Number(value));

function totalsFor(accounts=[]){
 const result={cash:0,portfolio:0,mutualFunds:0,nps:0,pf:0,other:0,liabilities:0};
 accounts.forEach(account=>{const key=accountCategory(account);result[key]=(result[key]||0)+Number(account.balance||0)});
 result.assets=result.cash+result.portfolio+result.mutualFunds+result.nps+result.pf+result.other;
 result.netWorth=result.assets-result.liabilities;
 return result;
}
function carryForward(data,sourceKey){const source=normalizeState(data);return{accounts:source.accounts.map(account=>({...account,openingBalance:Number(account.balance||0)})),bills:source.bills.map(bill=>({...bill,paid:false})),transactions:[],checklist:source.checklist.map(item=>({...item,done:false})),initializedFrom:sourceKey}}
async function previousMonthTemplate(uid,cursor){for(let distance=1;distance<=24;distance+=1){const date=new Date(cursor.getFullYear(),cursor.getMonth()-distance,1),key=monthKey(date),snapshot=await getDoc(doc(db,'users',uid,'finance',key));if(snapshot.exists())return carryForward(snapshot.data(),key)}return freshState()}
function getSavedSeries(){try{const saved=JSON.parse(localStorage.getItem('invincible.wealthSeries'));if(Array.isArray(saved)&&saved.some(key=>wealthSeries[key]))return saved.filter(key=>wealthSeries[key])}catch{}return Object.keys(wealthSeries)}
function defaultTransactionDate(cursor){const today=new Date();return monthKey(today)===monthKey(cursor)?`${monthKey(today)}-${String(today.getDate()).padStart(2,'0')}`:`${monthKey(cursor)}-01`}
function FinanceModal({title,onClose,children}){return <div className="finance-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="finance-modal" role="dialog" aria-modal="true" aria-label={title}><header><div><span className="finance-eyebrow">MONTHLY FINANCE</span><h2>{title}</h2></div><button type="button" className="finance-icon-button" aria-label="Close" onClick={onClose}>×</button></header>{children}</section></div>}
function MobileFinanceSheet({eyebrow,title,onClose,children}){return <div className="finance-mobile-sheet-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="finance-mobile-sheet" role="dialog" aria-modal="true" aria-label={title}><span className="finance-mobile-sheet-grip"/><header><div><span className="finance-eyebrow">{eyebrow}</span><h2>{title}</h2></div><button type="button" className="finance-icon-button" aria-label="Close" onClick={onClose}>×</button></header><div className="finance-mobile-sheet-body">{children}</div></section></div>}

function WealthTrend({history,selected,onSelected}){
 const keys=selected.filter(key=>wealthSeries[key]),width=900,height=278,padding={left:72,right:20,top:22,bottom:42};
 const values=history.flatMap(item=>keys.map(key=>Number(item[key]||0))),minimum=Math.min(0,...values),maximum=Math.max(1,...values),range=maximum-minimum||1;
 const x=index=>padding.left+(history.length===1?(width-padding.left-padding.right)/2:index*(width-padding.left-padding.right)/(history.length-1));
 const y=value=>padding.top+(maximum-value)*(height-padding.top-padding.bottom)/range;
 const presets={cash:['cash'],investments:['portfolio','mutualFunds','nps','pf'],full:Object.keys(wealthSeries)};
 const preset=Object.entries(presets).find(([,values])=>values.length===keys.length&&values.every(key=>keys.includes(key)))?.[0];
 const choose=values=>{onSelected(values);localStorage.setItem('invincible.wealthSeries',JSON.stringify(values))};
 return <section className="finance-panel finance-wealth-panel"><div className="finance-panel-heading"><div><span className="finance-eyebrow">12-MONTH VIEW</span><h2>Wealth trend</h2><p>Select only the balances you want to compare.</p></div><div className="finance-presets" aria-label="Wealth chart presets">{Object.entries({cash:'Cash',investments:'Investments',full:'Full wealth'}).map(([key,label])=><button key={key} type="button" className={preset===key?'active':''} onClick={()=>choose(presets[key])}>{label}</button>)}</div></div><div className="finance-series-picker">{Object.entries(wealthSeries).map(([key,series])=><button key={key} type="button" className={keys.includes(key)?'selected':''} style={{'--series':series.color}} onClick={()=>choose(keys.includes(key)?keys.filter(value=>value!==key):[...keys,key])}><i/>{series.label}</button>)}</div>{!history.length||!keys.length?<p className="finance-empty">Add balances in more than one month to build your wealth trend.</p>:<div className="finance-wealth-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Wealth trend for selected categories"><g className="finance-grid-lines">{[0,.25,.5,.75,1].map(mark=>{const value=maximum-mark*range,point=y(value);return <g key={mark}><line x1={padding.left} y1={point} x2={width-padding.right} y2={point}/><text x={padding.left-10} y={point+4} textAnchor="end">{compact(value)}</text></g>})}</g>{keys.map(seriesKey=><g key={seriesKey} className="finance-wealth-series" style={{'--line':wealthSeries[seriesKey].color}}><polyline points={history.map((item,index)=>`${x(index)},${y(item[seriesKey]||0)}`).join(' ')}/>{history.map((item,index)=><circle key={item.key} cx={x(index)} cy={y(item[seriesKey]||0)} r="4"><title>{item.label} · {wealthSeries[seriesKey].label}: {money(item[seriesKey])}</title></circle>)}</g>)}{history.map((item,index)=><text key={item.key} className="finance-month-axis" x={x(index)} y={height-13} textAnchor="middle">{item.short}</text>)}</svg></div>}</section>;
}

export function FinancePage(){
 const {user}=useAuth();
 const [cursor,setCursor]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
 const [state,setState]=useState(freshState),[history,setHistory]=useState([]),[status,setStatus]=useState('Opening this month…'),[statusType,setStatusType]=useState(''),[modal,setModal]=useState(''),[mobilePanel,setMobilePanel]=useState(''),[checkLabel,setCheckLabel]=useState(''),[selectedSeries,setSelectedSeries]=useState(getSavedSeries),[importText,setImportText]=useState(''),[importError,setImportError]=useState('');
 const [accountDraft,setAccountDraft]=useState({id:'',name:'',category:'cash',openingBalance:'',balance:''});
 const [billDraft,setBillDraft]=useState({id:'',name:'',last4:'',amount:'',paid:false});
 const [transactionDraft,setTransactionDraft]=useState({description:'',type:'expense',amount:'',date:defaultTransactionDate(new Date())});
 const bootstrapping=useRef(new Set()),mobileSwipeStart=useRef(null),saveInFlight=useRef(false);
 const [loadedMonth,setLoadedMonth]=useState('');
 const key=monthKey(cursor),monthLabel=cursor.toLocaleDateString([],{month:'long',year:'numeric'});
 const totals=useMemo(()=>{const balances=totalsFor(state.accounts),income=state.transactions.filter(item=>item.type==='income').reduce((sum,item)=>sum+Number(item.amount||0),0),directExpense=state.transactions.filter(item=>item.type==='expense').reduce((sum,item)=>sum+Number(item.amount||0),0),investmentTransfers=state.transactions.filter(item=>item.type==='transfer').reduce((sum,item)=>sum+Number(item.amount||0),0),cashOutflow=directExpense+investmentTransfers,cardBills=state.bills.reduce((sum,item)=>sum+Number(item.amount||0),0),paidBills=state.bills.filter(item=>item.paid).reduce((sum,item)=>sum+Number(item.amount||0),0),openingCash=state.accounts.filter(account=>accountCategory(account)==='cash').reduce((sum,item)=>sum+Number(item.openingBalance||0),0),hasOpening=state.accounts.some(account=>accountCategory(account)==='cash'&&itemHasNumber(account.openingBalance));return{...balances,income,expense:directExpense+cardBills,directExpense,investmentTransfers,cashOutflow,cardBills,paidBills,openingCash,hasOpening,untracked:openingCash-paidBills-cashOutflow-balances.cash,flow:income-directExpense-investmentTransfers-cardBills}},[state]);
 const completed=state.checklist.filter(item=>item.done).length;

 useEffect(()=>{if(!user)return undefined;setLoadedMonth('');setStatus('Loading month…');setStatusType('');const ref=doc(db,'users',user.uid,'finance',key);let cancelled=false;const stop=onSnapshot(ref,{includeMetadataChanges:true},async snapshot=>{if(cancelled||snapshot.metadata.hasPendingWrites)return;if(!snapshot.exists()){setState(freshState());if(!bootstrapping.current.has(key)){bootstrapping.current.add(key);try{const initial=await previousMonthTemplate(user.uid,cursor);await runTransaction(db,async transaction=>{const current=await transaction.get(ref);if(!current.exists())transaction.set(ref,{...initial,updatedAt:serverTimestamp()})})}catch(error){console.error(error);setStatus('Could not prepare this month.');setStatusType('error')}finally{bootstrapping.current.delete(key)}}return}setLoadedMonth(key);setState(normalizeState(snapshot.data()));setStatus(snapshot.metadata.fromCache?'Cached · checking Firebase…':saveInFlight.current?'Saving…':'Synced');setStatusType('ok');try{const months=Array.from({length:12},(_,index)=>new Date(cursor.getFullYear(),cursor.getMonth()-11+index,1)),snapshots=await Promise.all(months.map(date=>getDoc(doc(db,'users',user.uid,'finance',monthKey(date)))));if(cancelled)return;setHistory(snapshots.map((item,index)=>{if(!item.exists())return null;const values=totalsFor(item.data().accounts||[]),date=months[index];return{...values,key:monthKey(date),label:date.toLocaleDateString([],{month:'long',year:'numeric'}),short:date.toLocaleDateString([],{month:'short'})}}).filter(Boolean))}catch(error){console.error(error)}},error=>{console.error(error);setLoadedMonth('');setStatus(error.code==='permission-denied'?'Firebase access denied. Check deployed rules.':'Finance sync failed.');setStatusType('error')});return()=>{cancelled=true;stop()}},[user,key]);

 const save=async(next,replace=false)=>{
  if(saveInFlight.current)return false;
  if(loadedMonth!==key){setStatus('Wait for this month to finish loading before saving.');setStatusType('error');return false}
  saveInFlight.current=true;setStatus('Saving…');setStatusType('');
  const before=state,ref=doc(db,'users',user.uid,'finance',key);
  try{const saved=await runTransaction(db,async transaction=>{const snapshot=await transaction.get(ref),remote=normalizeState(snapshot.data()),merged=replace?next:mergeFinanceChange(remote,before,next);transaction.set(ref,{...merged,updatedAt:serverTimestamp()},{merge:true});return merged});setState(normalizeState(saved));setStatus('Saved to Firebase');setStatusType('ok');return true}
  catch(error){console.error(error);setStatus(error.code==='permission-denied'?'Firebase denied access. Your change was not saved.':'Could not save this change. Your form is kept; retry.');setStatusType('error');return false}
  finally{saveInFlight.current=false}
 };
 const moveMonth=amount=>{if(!saveInFlight.current){setLoadedMonth('');setCursor(value=>new Date(value.getFullYear(),value.getMonth()+amount,1))}};
 const openTransaction=(type='expense',description='')=>{setTransactionDraft({description,type,amount:'',date:defaultTransactionDate(cursor)});setModal('transaction')};
 const openReconciliation=()=>{setMobilePanel('');setTransactionDraft({description:'',type:'transfer',amount:String(Math.abs(totals.untracked)),date:defaultTransactionDate(cursor)});setModal('transaction')};
 const openAccount=(account=null)=>{setAccountDraft(account?{...account,openingBalance:account.openingBalance??'',balance:account.balance??''}:{id:'',name:'',category:'cash',openingBalance:'',balance:''});setModal('account')};
 const openBill=(bill=null)=>{setBillDraft(bill?{...bill}:{id:'',name:'',last4:'',amount:'',paid:false});setModal('bill')};
 const saveAccount=async event=>{event.preventDefault();const account={...accountDraft,id:accountDraft.id||newId(),templateKey:accountDraft.templateKey||accountDraft.id||null,name:accountDraft.name.trim(),category:accountDraft.category,type:accountDraft.category==='liabilities'?'liability':'asset',openingBalance:accountDraft.openingBalance===''?null:Number(accountDraft.openingBalance),balance:Number(accountDraft.balance)},exists=state.accounts.some(item=>item.id===account.id);if(await save({...state,accounts:exists?state.accounts.map(item=>item.id===account.id?account:item):[...state.accounts,account]}))setModal('')};
 const saveBill=async event=>{event.preventDefault();const bill={...billDraft,id:billDraft.id||newId(),templateKey:billDraft.templateKey||billDraft.id||null,name:billDraft.name.trim(),last4:billDraft.last4.trim(),amount:Number(billDraft.amount),paid:Boolean(billDraft.paid)},exists=state.bills.some(item=>item.id===bill.id);if(await save({...state,bills:exists?state.bills.map(item=>item.id===bill.id?bill:item):[...state.bills,bill]}))setModal('')};
 const addTransaction=async event=>{event.preventDefault();const transaction={id:newId(),description:transactionDraft.description.trim(),type:transactionDraft.type,amount:Number(transactionDraft.amount),date:transactionDraft.date};if(await save({...state,transactions:[...state.transactions,transaction]}))setModal('')};
 const addChecklist=async event=>{event.preventDefault();const label=checkLabel.trim();if(!label)return;if(await save({...state,checklist:[...state.checklist,{id:newId(),label,done:false}]}))setCheckLabel('')};
 const importMonth=async event=>{event.preventDefault();setImportError('');try{const parsed=JSON.parse(importText);if(!parsed||!Array.isArray(parsed.accounts)||!Array.isArray(parsed.bills)||!Array.isArray(parsed.transactions))throw new Error('Missing finance arrays');if(!await save({...normalizeState(parsed),initializedFrom:''},true)){setImportError('Firebase could not save this import. Your data is kept here.');return}setImportText('');setModal('')}catch(error){console.error(error);setImportError('This is not a valid monthly finance export.')}};
 const remove=(kind,id)=>save({...state,[kind]:state[kind].filter(item=>item.id!==id)});
 const toggleBill=id=>save({...state,bills:state.bills.map(item=>item.id===id?{...item,paid:!item.paid}:item)});
 const startMobileSwipe=event=>{mobileSwipeStart.current={x:event.clientX,y:event.clientY}};
 const finishMobileSwipe=event=>{const start=mobileSwipeStart.current;mobileSwipeStart.current=null;if(!start)return;const x=event.clientX-start.x,y=event.clientY-start.y;if(start.x<34&&x>56&&Math.abs(x)>Math.abs(y))setMobilePanel('chart')};
 const finishChartSwipe=event=>{const start=mobileSwipeStart.current;mobileSwipeStart.current=null;if(!start)return;const x=event.clientX-start.x,y=event.clientY-start.y;if(x<-50&&Math.abs(x)>Math.abs(y))setMobilePanel('')};
 const cashAccounts=state.accounts.filter(account=>accountCategory(account)==='cash');
 const investmentAccounts=state.accounts.filter(account=>accountCategory(account)!=='cash'&&accountCategory(account)!=='liabilities');
 const paidBillCount=state.bills.filter(item=>item.paid).length;

 return <div className="finance-react"><div className="finance-background-art" aria-hidden="true"><svg viewBox="0 0 1200 700" preserveAspectRatio="none"><path className="finance-art-gridline" d="M0 580 C180 535 260 600 420 470 S680 440 790 315 S1030 330 1200 155"/><path className="finance-art-glow" d="M0 580 C180 535 260 600 420 470 S680 440 790 315 S1030 330 1200 155"/></svg><span className="finance-art-rupee">₹</span><span className="finance-art-coin coin-one">₹</span><span className="finance-art-coin coin-two">₹</span></div>
  <main className="finance-mobile-cockpit" onPointerDown={startMobileSwipe} onPointerUp={finishMobileSwipe} onPointerCancel={()=>{mobileSwipeStart.current=null}}>
   <header className="finance-mobile-topbar"><div className="finance-mobile-month"><button type="button" onClick={()=>moveMonth(-1)} aria-label="Previous month">‹</button><div><span>MONTHLY FINANCE</span><strong>{monthLabel}</strong></div><button type="button" onClick={()=>moveMonth(1)} aria-label="Next month">›</button></div><button type="button" className={`finance-mobile-sync ${statusType}`} title={status} aria-label={status}><i className="fas fa-cloud"/><i className={statusType==='ok'?'fas fa-check':'fas fa-ellipsis'}/></button><button type="button" className="finance-mobile-checklist-button" aria-label="Open month-end checklist" onClick={()=>setMobilePanel('checklist')}><i className="fas fa-list-check"/><span>{completed}/{state.checklist.length}</span></button></header>
   <section className="finance-mobile-balance"><span className="finance-eyebrow">CASH REMAINING</span><strong>{money(totals.cash)}</strong><small>Across {cashAccounts.length} bank {cashAccounts.length===1?'account':'accounts'}</small>{totals.hasOpening&&<div className="finance-mobile-flow"><span><b>{compact(totals.openingCash)}</b> after salary</span><i>→</i><span><b>−{compact(totals.paidBills+totals.cashOutflow)}</b> outflow</span><i>→</i><span className="current"><b>{compact(totals.cash)}</b> left</span></div>}{Math.abs(totals.untracked)>.009&&<button type="button" className="finance-mobile-untracked" onClick={openReconciliation}><i className="fas fa-triangle-exclamation"/> Explain {money(Math.abs(totals.untracked))} movement</button>}</section>
   <section className="finance-mobile-tiles" aria-label="Finance sections">
    <button type="button" className="cash" onClick={()=>setMobilePanel('accounts')}><span className="finance-mobile-tile-icon"><i className="fas fa-building-columns"/></span><span><small>BANK ACCOUNTS</small><strong>{money(totals.cash)}</strong><em>{cashAccounts.length} linked</em></span><i className="fas fa-chevron-right"/></button>
    <button type="button" className="cards" onClick={()=>setMobilePanel('bills')}><span className="finance-mobile-tile-icon"><i className="fas fa-credit-card"/></span><span><small>CREDIT CARDS</small><strong>{money(totals.cardBills)}</strong><em>{paidBillCount}/{state.bills.length} paid</em></span><i className="fas fa-chevron-right"/></button>
    <button type="button" className="wealth" onClick={()=>setMobilePanel('investments')}><span className="finance-mobile-tile-icon"><i className="fas fa-chart-pie"/></span><span><small>INVESTMENTS</small><strong>{money(totals.assets-totals.cash)}</strong><em>{investmentAccounts.length} holdings</em></span><i className="fas fa-chevron-right"/></button>
    <button type="button" className="activity" onClick={()=>setMobilePanel('activity')}><span className="finance-mobile-tile-icon"><i className="fas fa-wave-square"/></span><span><small>ACTIVITY</small><strong>{money(totals.income)}</strong><em>{state.transactions.length} entries</em></span><i className="fas fa-chevron-right"/></button>
   </section>
   <button type="button" className="finance-mobile-chart-handle" aria-label="Open wealth chart" onClick={()=>setMobilePanel('chart')}><i className="fas fa-chart-line"/><span>Trend</span></button>
   <nav className="finance-mobile-action-dock" aria-label="Finance quick actions"><button type="button" onClick={()=>openTransaction('income','Salary')}><i className="fas fa-indian-rupee-sign"/><span>Salary</span></button><button type="button" className="primary" onClick={()=>openTransaction()}><i className="fas fa-plus"/><span>Cash flow</span></button><button type="button" onClick={()=>setMobilePanel('accounts')}><i className="fas fa-pen"/><span>Update</span></button></nav>
  </main>
  <header className="finance-hero"><div className="finance-hero-copy"><span className="finance-eyebrow">MONTHLY OPERATING CHECK</span><h1>{monthLabel} finances</h1><p>Record salary, close the bills due around month-end, and see exactly what remains.</p></div><div className="finance-period-control"><div className="finance-month-nav"><button type="button" onClick={()=>moveMonth(-1)} aria-label="Previous month">‹</button><strong>{monthLabel}</strong><button type="button" onClick={()=>moveMonth(1)} aria-label="Next month">›</button></div><div className={`finance-sync ${statusType}`} title={status} aria-label={status}><i className="fas fa-cloud" aria-hidden="true"/>{statusType==='ok'?<i className="fas fa-check finance-sync-check" aria-hidden="true"/>:<span>{status}</span>}</div></div><div className="finance-hero-actions"><button type="button" className="finance-secondary" onClick={()=>openAccount()}>+ Account</button><button type="button" className="finance-primary" onClick={()=>openTransaction('income','Salary')}>+ Salary</button><button type="button" className="finance-primary finance-cyan" onClick={()=>openTransaction()}>+ Cash flow</button></div></header>
  <main className="finance-main">
   <section className="finance-summary-grid"><article className="finance-summary asset"><span>Total assets</span><strong>{money(totals.assets)}</strong><small>Bank + investments</small></article><article className="finance-summary liability"><span>Card bills</span><strong>{money(totals.cardBills)}</strong><small>{state.bills.filter(item=>item.paid).length}/{state.bills.length} marked paid</small></article><article className="finance-summary net"><span>Net worth</span><strong>{money(totals.netWorth)}</strong><small>Assets minus liabilities</small></article><article className="finance-summary flow"><span>Cash remaining</span><strong>{money(totals.cash)}</strong><small>Across bank accounts</small></article></section>
   {totals.hasOpening&&<section className="finance-panel finance-cash-journey"><div className="finance-panel-heading"><div><span className="finance-eyebrow">CASH JOURNEY</span><h2>After salary to month-end</h2></div>{Math.abs(totals.untracked)>.009&&<button type="button" className="finance-reconcile-warning" onClick={openReconciliation}>Explain {money(Math.abs(totals.untracked))}</button>}</div><div className="finance-journey-steps"><article><span>1</span><small>After salary</small><strong>{money(totals.openingCash)}</strong></article><i>→</i><article><span>2</span><small>Known outflow</small><strong>−{money(totals.paidBills+totals.cashOutflow)}</strong></article><i>→</i><article><span>3</span><small>Current bank balance</small><strong>{money(totals.cash)}</strong></article></div>{Math.abs(totals.untracked)>.009&&<p className="finance-reconcile-note">There is {money(Math.abs(totals.untracked))} of unexplained bank movement. Record an expense or investment transfer to reconcile it.</p>}</section>}
   <WealthTrend history={history} selected={selectedSeries} onSelected={setSelectedSeries}/>
   <div className="finance-layout"><div className="finance-main-column">
    <section className="finance-panel"><div className="finance-panel-heading"><div><span className="finance-eyebrow">BALANCES</span><h2>Accounts & investments</h2></div><div className="finance-panel-actions"><button type="button" className="finance-text-button" onClick={()=>{setImportError('');setImportText('');setModal('import')}}>Import month</button><button type="button" className="finance-text-button" onClick={()=>openAccount()}>Add account</button></div></div>{state.accounts.length?<div className="finance-account-grid">{state.accounts.map(account=>{const category=accountCategory(account);return <article key={account.id} className={`finance-account ${category==='liabilities'?'liability':'asset'}`} style={{'--account-accent':wealthSeries[category]?.color}}><div><span className="finance-account-type">{wealthSeries[category]?.label||'Asset'}</span><button type="button" className="finance-remove" aria-label={`Remove ${account.name}`} onClick={()=>remove('accounts',account.id)}>×</button></div><h3>{account.name}</h3><strong>{money(account.balance)}</strong>{itemHasNumber(account.openingBalance)&&category==='cash'&&<small>Started at {money(account.openingBalance)}</small>}<button type="button" className="finance-card-edit" onClick={()=>openAccount(account)}>Update</button></article>})}</div>:<p className="finance-empty">Add bank, investment, PF, or liability balances for this month.</p>}</section>
    <section className="finance-panel"><div className="finance-panel-heading"><div><span className="finance-eyebrow">CREDIT CARDS</span><h2>Monthly card bills</h2></div><button type="button" className="finance-text-button" onClick={()=>openBill()}>Add card</button></div>{state.bills.length?<div className="finance-bill-list">{state.bills.map(bill=><article key={bill.id} className={bill.paid?'paid':''}><button type="button" className="finance-paid-toggle" aria-label={`${bill.paid?'Mark unpaid':'Mark paid'} ${bill.name}`} onClick={()=>toggleBill(bill.id)}>{bill.paid?'✓':''}</button><div><strong>{bill.name}</strong><small>{bill.last4?`•••• ${bill.last4} · `:''}{bill.paid?'Paid':'Due'}</small></div><b>{money(bill.amount,2)}</b><button type="button" className="finance-card-edit" onClick={()=>openBill(bill)}>Update</button><button type="button" className="finance-remove" aria-label={`Remove ${bill.name}`} onClick={()=>remove('bills',bill.id)}>×</button></article>)}</div>:<p className="finance-empty">Add each card once. It will carry into the next month automatically.</p>}</section>
    <section className="finance-panel"><div className="finance-panel-heading"><div><span className="finance-eyebrow">ACTIVITY</span><h2>Income & other expenses</h2></div><button type="button" className="finance-text-button" onClick={()=>openTransaction()}>Add entry</button></div><div className="finance-flow-chart" aria-label="Income and expense chart"><div className="finance-bar-zone">{[['income',totals.income],['expense',totals.expense]].map(([type,value])=>{const max=Math.max(totals.income,totals.expense,1),height=Math.max(4,Math.round(value/max*150));return <div key={type} className={`finance-bar ${type}`} style={{height}}><span>{money(value)}</span><small>{type}</small></div>})}</div></div>{state.transactions.length?<div className="finance-transactions">{[...state.transactions].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(item=><article key={item.id}><div><strong>{item.description}</strong><small>{item.date} · {item.type==='transfer'?'investment transfer':item.type}</small></div><div><strong className={item.type}>{item.type==='income'?'+':'−'}{money(item.amount)}</strong><button type="button" className="finance-remove" aria-label={`Remove ${item.description}`} onClick={()=>remove('transactions',item.id)}>×</button></div></article>)}</div>:<p className="finance-empty">Card bills are already counted above. Add salary and other movements here.</p>}</section>
   </div><aside className="finance-panel finance-checklist-panel"><div className="finance-panel-heading"><div><span className="finance-eyebrow">MONTH-END</span><h2>Other checklist</h2></div><span className="finance-progress">{completed}/{state.checklist.length}</span></div><div className="finance-progress-track"><span style={{width:`${state.checklist.length?completed/state.checklist.length*100:0}%`}}/></div><div className="finance-checklist">{state.checklist.map(item=><label key={item.id} className={item.done?'done':''}><input type="checkbox" checked={item.done} onChange={()=>save({...state,checklist:state.checklist.map(entry=>entry.id===item.id?{...entry,done:!entry.done}:entry)})}/><span>{item.label}</span><button type="button" className="finance-remove" aria-label={`Remove ${item.label}`} onClick={event=>{event.preventDefault();remove('checklist',item.id)}}>×</button></label>)}</div><form className="finance-inline-form" onSubmit={addChecklist}><input value={checkLabel} onChange={event=>setCheckLabel(event.target.value)} maxLength="80" placeholder="Add bill or reminder"/><button>Add</button></form></aside></div>
  </main>
  {mobilePanel==='accounts'&&<MobileFinanceSheet eyebrow="CASH & BANK" title="Bank accounts" onClose={()=>setMobilePanel('')}><div className="finance-mobile-sheet-list">{cashAccounts.map(account=><article key={account.id}><span className="finance-mobile-row-icon cash"><i className="fas fa-building-columns"/></span><div><strong>{account.name}</strong>{itemHasNumber(account.openingBalance)&&<small>Started at {money(account.openingBalance)}</small>}</div><b>{money(account.balance)}</b><button type="button" onClick={()=>{setMobilePanel('');openAccount(account)}}>Update</button></article>)}{!cashAccounts.length&&<p className="finance-empty">No bank accounts added yet.</p>}</div><div className="finance-mobile-sheet-actions"><button type="button" onClick={()=>{setMobilePanel('');setImportError('');setImportText('');setModal('import')}}>Import</button><button type="button" className="primary" onClick={()=>{setMobilePanel('');openAccount()}}>+ Add account</button></div></MobileFinanceSheet>}
  {mobilePanel==='bills'&&<MobileFinanceSheet eyebrow="CREDIT CARDS" title={`${paidBillCount}/${state.bills.length} bills paid`} onClose={()=>setMobilePanel('')}><div className="finance-mobile-sheet-list bills">{state.bills.map(bill=><article key={bill.id} className={bill.paid?'paid':''}><button type="button" className="finance-paid-toggle" aria-label={`${bill.paid?'Mark unpaid':'Mark paid'} ${bill.name}`} onClick={()=>toggleBill(bill.id)}>{bill.paid?'✓':''}</button><div><strong>{bill.name}</strong><small>{bill.last4?`•••• ${bill.last4} · `:''}{bill.paid?'Paid':'Due'}</small></div><b>{money(bill.amount,2)}</b><button type="button" onClick={()=>{setMobilePanel('');openBill(bill)}}>Update</button></article>)}{!state.bills.length&&<p className="finance-empty">Add each card once. It will return automatically next month.</p>}</div><div className="finance-mobile-sheet-actions"><span>{money(totals.paidBills)} paid</span><button type="button" className="primary" onClick={()=>{setMobilePanel('');openBill()}}>+ Add card</button></div></MobileFinanceSheet>}
  {mobilePanel==='investments'&&<MobileFinanceSheet eyebrow="LONG-TERM WEALTH" title="Investments" onClose={()=>setMobilePanel('')}><div className="finance-mobile-wealth-total"><span>INVESTED WEALTH</span><strong>{money(totals.assets-totals.cash)}</strong><small>Net worth {money(totals.netWorth)}</small></div><div className="finance-mobile-sheet-list">{investmentAccounts.map(account=>{const category=accountCategory(account);return <article key={account.id}><span className="finance-mobile-row-icon" style={{color:wealthSeries[category]?.color}}><i className="fas fa-chart-simple"/></span><div><strong>{account.name}</strong><small>{wealthSeries[category]?.label}</small></div><b>{money(account.balance)}</b><button type="button" onClick={()=>{setMobilePanel('');openAccount(account)}}>Update</button></article>})}{!investmentAccounts.length&&<p className="finance-empty">No investments added yet.</p>}</div><div className="finance-mobile-sheet-actions"><button type="button" onClick={()=>setMobilePanel('chart')}>View trend</button><button type="button" className="primary" onClick={()=>{setMobilePanel('');openAccount()}}>+ Add investment</button></div></MobileFinanceSheet>}
  {mobilePanel==='activity'&&<MobileFinanceSheet eyebrow="CASH FLOW" title="Income & expenses" onClose={()=>setMobilePanel('')}><div className="finance-mobile-activity-summary"><span><small>INCOME</small><strong>+{money(totals.income)}</strong></span><span><small>EXPENSES</small><strong>−{money(totals.expense)}</strong></span>{totals.investmentTransfers>0&&<span><small>INVESTED</small><strong>−{money(totals.investmentTransfers)}</strong></span>}</div>{Math.abs(totals.untracked)>.009&&<button type="button" className="finance-mobile-sheet-warning" onClick={openReconciliation}><i className="fas fa-triangle-exclamation"/> Explain {money(Math.abs(totals.untracked))} bank movement</button>}<div className="finance-mobile-sheet-list activity">{[...state.transactions].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(item=><article key={item.id}><span className={`finance-mobile-row-icon ${item.type}`}><i className={`fas ${item.type==='income'?'fa-arrow-down':item.type==='transfer'?'fa-arrow-right':'fa-arrow-up'}`}/></span><div><strong>{item.description}</strong><small>{item.date} · {item.type==='transfer'?'investment transfer':item.type}</small></div><b className={item.type}>{item.type==='income'?'+':'−'}{money(item.amount)}</b><button type="button" aria-label={`Remove ${item.description}`} onClick={()=>remove('transactions',item.id)}>×</button></article>)}{!state.transactions.length&&<p className="finance-empty">No cash-flow entries this month.</p>}</div><div className="finance-mobile-sheet-actions"><button type="button" onClick={()=>{setMobilePanel('');openTransaction('income','Salary')}}>+ Salary</button><button type="button" className="primary" onClick={()=>{setMobilePanel('');openTransaction()}}>+ Cash flow</button></div></MobileFinanceSheet>}
  {mobilePanel==='checklist'&&<MobileFinanceSheet eyebrow="MONTH-END" title="Other checklist" onClose={()=>setMobilePanel('')}><div className="finance-mobile-check-progress"><span style={{width:`${state.checklist.length?completed/state.checklist.length*100:0}%`}}/></div><div className="finance-checklist finance-mobile-checklist">{state.checklist.map(item=><label key={item.id} className={item.done?'done':''}><input type="checkbox" checked={item.done} onChange={()=>save({...state,checklist:state.checklist.map(entry=>entry.id===item.id?{...entry,done:!entry.done}:entry)})}/><span>{item.label}</span><button type="button" className="finance-remove" aria-label={`Remove ${item.label}`} onClick={event=>{event.preventDefault();remove('checklist',item.id)}}>×</button></label>)}</div><form className="finance-inline-form" onSubmit={addChecklist}><input value={checkLabel} onChange={event=>setCheckLabel(event.target.value)} maxLength="80" placeholder="Add bill or reminder"/><button>Add</button></form></MobileFinanceSheet>}
  {mobilePanel==='chart'&&<div className="finance-mobile-chart-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setMobilePanel('')}><aside className="finance-mobile-chart-drawer" role="dialog" aria-modal="true" aria-label="Wealth trend" onPointerDown={startMobileSwipe} onPointerUp={finishChartSwipe} onPointerCancel={()=>{mobileSwipeStart.current=null}}><header><div><span className="finance-eyebrow">12-MONTH VIEW</span><h2>Wealth trend</h2></div><button type="button" className="finance-icon-button" aria-label="Close" onClick={()=>setMobilePanel('')}>×</button></header><div className="finance-mobile-chart-net"><small>NET WORTH</small><strong>{money(totals.netWorth)}</strong></div><WealthTrend history={history} selected={selectedSeries} onSelected={setSelectedSeries}/><small className="finance-mobile-chart-hint"><i className="fas fa-arrow-left"/> Swipe left or tap outside to close</small></aside></div>}
  {modal==='account'&&<FinanceModal title={accountDraft.id?'Update balance':'Add account balance'} onClose={()=>setModal('')}><form className="finance-form" onSubmit={saveAccount}><label>Account name<input autoFocus required maxLength="60" value={accountDraft.name} onChange={event=>setAccountDraft(value=>({...value,name:event.target.value}))} placeholder="e.g. SBI Savings"/></label><label>Category<select value={accountDraft.category} onChange={event=>setAccountDraft(value=>({...value,category:event.target.value}))}>{categoryOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{accountDraft.category==='cash'&&<label>Balance after salary / at month start<input type="number" min="0" step="0.01" value={accountDraft.openingBalance} onChange={event=>setAccountDraft(value=>({...value,openingBalance:event.target.value}))} placeholder="0"/></label>}<label>Current balance<input required type="number" min="0" step="0.01" value={accountDraft.balance} onChange={event=>setAccountDraft(value=>({...value,balance:event.target.value}))} placeholder="0"/></label>{statusType==='error'&&<p className="finance-import-error" role="alert">{status}</p>}<div className="finance-form-actions"><button type="button" className="finance-secondary" onClick={()=>setModal('')}>Cancel</button><button className="finance-primary">Save balance</button></div></form></FinanceModal>}
  {modal==='bill'&&<FinanceModal title={billDraft.id?'Update card bill':'Add credit card'} onClose={()=>setModal('')}><form className="finance-form" onSubmit={saveBill}><label>Card name<input autoFocus required maxLength="60" value={billDraft.name} onChange={event=>setBillDraft(value=>({...value,name:event.target.value}))} placeholder="e.g. Axis Flipkart"/></label><label>Last 4 digits<input inputMode="numeric" pattern="[0-9]{0,4}" maxLength="4" value={billDraft.last4} onChange={event=>setBillDraft(value=>({...value,last4:event.target.value.replace(/\D/g,'').slice(0,4)}))} placeholder="0000"/></label><label>Bill amount<input required type="number" min="0" step="0.01" value={billDraft.amount} onChange={event=>setBillDraft(value=>({...value,amount:event.target.value}))}/></label><label className="finance-paid-field"><input type="checkbox" checked={billDraft.paid} onChange={event=>setBillDraft(value=>({...value,paid:event.target.checked}))}/> Paid this month</label>{statusType==='error'&&<p className="finance-import-error" role="alert">{status}</p>}<div className="finance-form-actions"><button type="button" className="finance-secondary" onClick={()=>setModal('')}>Cancel</button><button className="finance-primary">Save bill</button></div></form></FinanceModal>}
  {modal==='import'&&<FinanceModal title="Import private month data" onClose={()=>setModal('')}><form className="finance-form" onSubmit={importMonth}><p className="finance-import-note">Paste a monthly finance JSON export. It is saved directly to your private Firebase record and is never added to the public app code.</p><label>Month data<textarea className="finance-import-text" autoFocus required value={importText} onChange={event=>setImportText(event.target.value)} placeholder='{"accounts":[],"bills":[],"transactions":[]}'/></label>{importError&&<p className="finance-import-error" role="alert">{importError}</p>}{statusType==='error'&&<p className="finance-import-error" role="alert">{status}</p>}<div className="finance-form-actions"><button type="button" className="finance-secondary" onClick={()=>setModal('')}>Cancel</button><button className="finance-primary">Import securely</button></div></form></FinanceModal>}
  {modal==='transaction'&&<FinanceModal title="Add cash-flow entry" onClose={()=>setModal('')}><form className="finance-form" onSubmit={addTransaction}><label>Description<input autoFocus required maxLength="80" value={transactionDraft.description} onChange={event=>setTransactionDraft(value=>({...value,description:event.target.value}))} placeholder="e.g. Monthly SIP or bank charge"/></label><label>Type<select value={transactionDraft.type} onChange={event=>setTransactionDraft(value=>({...value,type:event.target.value}))}><option value="income">Income</option><option value="expense">Expense</option><option value="transfer">Investment transfer</option></select></label><label>Amount<input required type="number" min="0.01" step="0.01" value={transactionDraft.amount} onChange={event=>setTransactionDraft(value=>({...value,amount:event.target.value}))}/></label><label>Date<input required type="date" value={transactionDraft.date} onChange={event=>setTransactionDraft(value=>({...value,date:event.target.value}))}/></label>{statusType==='error'&&<p className="finance-import-error" role="alert">{status}</p>}<div className="finance-form-actions"><button type="button" className="finance-secondary" onClick={()=>setModal('')}>Cancel</button><button className="finance-primary">Save entry</button></div></form></FinanceModal>}
 </div>;
}
export default FinancePage;
