import{useEffect,useRef}from'react';

// A depth-tested sphere and tilted particle orbits, rendered without a 3D framework.
function shader(gl,type,source){const value=gl.createShader(type);gl.shaderSource(value,source);gl.compileShader(value);if(!gl.getShaderParameter(value,gl.COMPILE_STATUS)){gl.deleteShader(value);throw Error('Orb shader could not compile')}return value}
function program(gl,vertex,fragment){const value=gl.createProgram(),vs=shader(gl,gl.VERTEX_SHADER,vertex),fs=shader(gl,gl.FRAGMENT_SHADER,fragment);gl.attachShader(value,vs);gl.attachShader(value,fs);gl.linkProgram(value);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(value,gl.LINK_STATUS)){gl.deleteProgram(value);throw Error('Orb program could not link')}return value}
const vertex=`attribute vec3 position; uniform mat4 projection; varying vec3 normal; void main(){normal=position;gl_Position=projection*vec4(position,1.0);}`;
const fragment=`precision mediump float; varying vec3 normal; uniform float time; void main(){vec3 n=normalize(normal);vec3 light=normalize(vec3(-0.7,0.85,1.5));float diffuse=max(dot(n,light),0.0);float rim=pow(1.0-max(n.z,0.0),2.6);float spec=pow(max(dot(n,normalize(light+vec3(0.0,0.0,1.0))),0.0),32.0);float longitude=atan(n.x,n.z)+time*0.025;float grid=pow(abs(sin(longitude*9.0)),48.0)*0.035+pow(abs(sin(asin(n.y)*9.0)),48.0)*0.025;vec3 color=vec3(0.008,0.032,0.047)+vec3(0.015,0.13,0.16)*diffuse+vec3(0.1,0.64,0.72)*rim+vec3(0.25,0.58,0.63)*spec+vec3(0.12,0.28,0.31)*grid;gl_FragColor=vec4(color,1.0);}`;
const particleVertex=`attribute vec3 position;attribute vec2 appearance;uniform mat4 projection;uniform float pixelRatio;varying float opacity;varying float gold;void main(){vec4 projected=projection*vec4(position,1.0);gl_Position=projected;gl_PointSize=appearance.x*pixelRatio*4.6/projected.w;opacity=appearance.y;gold=step(0.0,position.y);}`;
const particleFragment=`precision mediump float;varying float opacity;varying float gold;void main(){float radius=length(gl_PointCoord-vec2(0.5))*2.0;if(radius>1.0)discard;float alpha=(1.0-smoothstep(0.15,1.0,radius))*opacity;vec3 color=mix(vec3(0.3,0.9,1.0),vec3(1.0,0.79,0.38),gold);gl_FragColor=vec4(color,alpha);}`;
function perspective(aspect){const f=1/Math.tan(Math.PI/8),near=.1,far=30,distance=4.6;return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,(far+near)/(near-far)*-distance+2*far*near/(near-far),distance])}
function sphereMesh(){const vertices=[],indices=[],rows=36,columns=56;for(let row=0;row<=rows;row++){const latitude=row*Math.PI/rows;for(let column=0;column<=columns;column++){const longitude=column*2*Math.PI/columns;vertices.push(Math.sin(latitude)*Math.cos(longitude),Math.cos(latitude),Math.sin(latitude)*Math.sin(longitude))}}for(let row=0;row<rows;row++)for(let column=0;column<columns;column++){const a=row*(columns+1)+column,b=a+columns+1;indices.push(a,b,a+1,b,b+1,a+1)}return{vertices:new Float32Array(vertices),indices:new Uint16Array(indices)}}
export function orbitPosition(angle,radius,tilt,turn){const x=Math.cos(angle)*radius,y=Math.sin(angle)*radius*Math.cos(tilt),z=Math.sin(angle)*radius*Math.sin(tilt);return[x*Math.cos(turn)+z*Math.sin(turn),y,-x*Math.sin(turn)+z*Math.cos(turn)]}
export function FocusOrb(){
 const canvas=useRef(null),host=useRef(null);
 useEffect(()=>{
  const c=canvas.current,container=host.current;let gl,solid,dots,vertexBuffer,indexBuffer,particleBuffer,frame=null,resizeObserver,intersectionObserver;let disposed=false,inView=true,contextLost=false,start=performance.now(),last=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)'),mobile=matchMedia('(max-width:1024px)');
  const stop=()=>{if(frame!==null)cancelAnimationFrame(frame);frame=null};
  try{
   gl=c.getContext('webgl',{alpha:true,antialias:true,premultipliedAlpha:false,powerPreference:'low-power'});if(!gl)return;
   solid=program(gl,vertex,fragment);dots=program(gl,particleVertex,particleFragment);
   const mesh=sphereMesh();vertexBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vertexBuffer);gl.bufferData(gl.ARRAY_BUFFER,mesh.vertices,gl.STATIC_DRAW);indexBuffer=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,indexBuffer);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,mesh.indices,gl.STATIC_DRAW);particleBuffer=gl.createBuffer();
   const solidPosition=gl.getAttribLocation(solid,'position'),solidProjection=gl.getUniformLocation(solid,'projection'),solidTime=gl.getUniformLocation(solid,'time'),dotPosition=gl.getAttribLocation(dots,'position'),dotAppearance=gl.getAttribLocation(dots,'appearance'),dotProjection=gl.getUniformLocation(dots,'projection'),dotRatio=gl.getUniformLocation(dots,'pixelRatio');
   const orbits=[{radius:1.38,tilt:1.08,turn:.38,speed:.23,count:26},{radius:1.56,tilt:-.78,turn:-.63,speed:-.17,count:24},{radius:1.27,tilt:.53,turn:1.1,speed:.13,count:18}];let projection,ratio=1;
   const render=timestamp=>{
    frame=null;if(disposed||contextLost||document.hidden||!inView)return;
    const interval=mobile.matches?1000/30:1000/45;if(!reduced.matches&&timestamp-last<interval){frame=requestAnimationFrame(render);return}last=timestamp;
    const time=reduced.matches?8:(timestamp-start)/1000;
    gl.viewport(0,0,c.width,c.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.depthMask(true);gl.disable(gl.BLEND);
    gl.disableVertexAttribArray(dotAppearance);gl.useProgram(solid);gl.uniformMatrix4fv(solidProjection,false,projection);gl.uniform1f(solidTime,time);gl.bindBuffer(gl.ARRAY_BUFFER,vertexBuffer);gl.enableVertexAttribArray(solidPosition);gl.vertexAttribPointer(solidPosition,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,indexBuffer);gl.drawElements(gl.TRIANGLES,mesh.indices.length,gl.UNSIGNED_SHORT,0);
    const particles=[];for(const [index,orbit]of orbits.entries()){const count=mobile.matches?Math.ceil(orbit.count*.5):orbit.count,trails=mobile.matches?2:4;for(let dot=0;dot<count;dot++){const phase=dot*Math.PI*2/count+index*.7;for(let trail=0;trail<trails;trail++){const angle=phase+time*orbit.speed-trail*.016*Math.sign(orbit.speed),point=orbitPosition(angle,orbit.radius,orbit.tilt,orbit.turn);particles.push(...point,trail===0?5.2:3.2,(trail===0?.85:.22)*(1-trail/trails))}}}
    gl.useProgram(dots);gl.uniformMatrix4fv(dotProjection,false,projection);gl.uniform1f(dotRatio,ratio);gl.bindBuffer(gl.ARRAY_BUFFER,particleBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(particles),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(dotPosition);gl.vertexAttribPointer(dotPosition,3,gl.FLOAT,false,20,0);gl.enableVertexAttribArray(dotAppearance);gl.vertexAttribPointer(dotAppearance,2,gl.FLOAT,false,20,12);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.drawArrays(gl.POINTS,0,particles.length/5);gl.depthMask(true);
    container.dataset.ready='true';if(!reduced.matches)frame=requestAnimationFrame(render);
   };
   const resume=()=>{stop();if(!disposed&&!contextLost&&!document.hidden&&inView)frame=requestAnimationFrame(render)};
   const resize=()=>{const rect=container.getBoundingClientRect();if(!rect.width||!rect.height)return;ratio=Math.min(devicePixelRatio||1,mobile.matches?1:1.5);delete container.dataset.ready;c.width=Math.round(rect.width*ratio);c.height=Math.round(rect.height*ratio);projection=perspective(rect.width/rect.height);resume()};
   resizeObserver=new ResizeObserver(resize);resizeObserver.observe(container);
   if(typeof IntersectionObserver!=='undefined'){intersectionObserver=new IntersectionObserver(entries=>{inView=entries[0].isIntersecting;resume()});intersectionObserver.observe(container)}
   const visibility=()=>resume(),preferences=()=>resize(),lost=event=>{event.preventDefault();contextLost=true;stop();delete container.dataset.ready};
   document.addEventListener('visibilitychange',visibility);reduced.addEventListener('change',preferences);mobile.addEventListener('change',preferences);c.addEventListener('webglcontextlost',lost);resize();
   return()=>{disposed=true;stop();resizeObserver.disconnect();intersectionObserver?.disconnect();document.removeEventListener('visibilitychange',visibility);reduced.removeEventListener('change',preferences);mobile.removeEventListener('change',preferences);c.removeEventListener('webglcontextlost',lost);gl.deleteBuffer(vertexBuffer);gl.deleteBuffer(indexBuffer);gl.deleteBuffer(particleBuffer);gl.deleteProgram(solid);gl.deleteProgram(dots)};
  }catch(error){console.warn('3D orb unavailable; keeping the shaded fallback.',error);stop();resizeObserver?.disconnect();intersectionObserver?.disconnect();if(gl){if(vertexBuffer)gl.deleteBuffer(vertexBuffer);if(indexBuffer)gl.deleteBuffer(indexBuffer);if(particleBuffer)gl.deleteBuffer(particleBuffer);if(solid)gl.deleteProgram(solid);if(dots)gl.deleteProgram(dots)}}
 },[]);
 return <div ref={host} className="focus-orb-3d" aria-hidden="true"><div className="orb-3d-fallback"/><canvas ref={canvas}/></div>;
}
