import{useEffect,useMemo,useRef,useState}from'react';
import{Timestamp,addDoc,collection,deleteDoc,doc,onSnapshot,orderBy,query,runTransaction,serverTimestamp,updateDoc}from'firebase/firestore';
import{useAuth}from'./AuthContext';
import{db}from'./firebase';
import {asDate,dateKey,groupReminders,completeReminder} from './reminder-model';
const tomorrowKey=()=>{const date=new Date();date.setDate(date.getDate()+1);return dateKey(date)};
const timeText=date=>new Intl.DateTimeFormat('en-IN',{hour:'numeric',minute:'2-digit'}).format(date);
const dateLabel=date=>new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'short'}).format(date);
function ReminderCard({item,onDone,onSnooze,onEdit,onDelete}){
 const[expanded,setExpanded]=useState(false),[offset,setOffset]=useState(0),[completing,setCompleting]=useState(false),start=useRef(null),busy=useRef(false),[failure,setFailure]=useState(''),[pending,setPending]=useState(false),due=asDate(item.dueAt);
 const act=async action=>{if(busy.current)return;busy.current=true;setPending(true);setFailure('');try{await action(item)}catch{setCompleting(false);setFailure('Could not save. Try again.')}finally{busy.current=false;setPending(false)}};
 const finish=()=>{if(busy.current)return;setCompleting(true);return act(onDone)};
 return <div className={'reminder-wrap'+(offset?' is-swiping':'')}><div className="swipe-action done">✓ Done</div><div className="swipe-action snooze">Snooze 1h</div><article className={'reminder-card'+(expanded?' expanded':'')+(completing?' completing':'')} style={{transform:offset?`translateX(${offset}px)`:undefined}} onPointerDown={event=>{if(!event.target.closest('button'))start.current=event.clientX}} onPointerMove={event=>{if(start.current!==null)setOffset(Math.max(-105,Math.min(105,event.clientX-start.current)))}} onPointerUp={()=>{if(offset>72)finish();else if(offset<-72)act(onSnooze);setOffset(0);start.current=null}} onPointerCancel={()=>{start.current=null;setOffset(0)}}>
  <time className="time" dateTime={due.toISOString()}>{dateKey(due)<dateKey()&&<span className="overdue-date">{dateLabel(due)}</span>}{timeText(due)}</time><div className="copy"><strong>{item.title}</strong><div className="meta">{item.repeat==='daily'&&<span className="repeat">↻ Daily</span>}{item.snoozed&&<span>Snoozed</span>}</div></div><button className="complete-button" disabled={pending} onClick={finish} aria-label="Mark done">✓</button><button disabled={pending} className="expand" onClick={()=>setExpanded(value=>!value)} aria-label="Reminder details">⌄</button><div className="details"><button disabled={pending} onClick={()=>onEdit(item)}>Edit</button><button disabled={pending} onClick={()=>act(onSnooze)}>Snooze 1h</button><button disabled={pending} onClick={()=>act(onDelete)}>Delete</button></div>
 {failure&&<p className="reminder-error" role="alert">{failure}</p>}</article></div>
}
function QuickReminder({editing,onClose,onSave}){
 const editingDate=editing?asDate(editing.dueAt):null,editingKey=editingDate?dateKey(editingDate):dateKey(),initialDay=editingKey===dateKey()?'today':editingKey===tomorrowKey()?'tomorrow':'custom';
 const[title,setTitle]=useState(editing?.title||''),[day,setDay]=useState(initialDay),[customDate,setCustomDate]=useState(editingKey),[time,setTime]=useState(editingDate?editingDate.toTimeString().slice(0,5):'19:00'),[daily,setDaily]=useState(editing?.repeat==='daily'),[saving,setSaving]=useState(false),[failure,setFailure]=useState('');
 const preset=value=>{if(value==='tonight'){setDay('today');setTime('21:00')}if(value==='tomorrow'){setDay('tomorrow');setTime('08:00')}if(value==='daily')setDaily(true)};
 const submit=async event=>{event.preventDefault();if(!title.trim())return;const key=day==='today'?dateKey():day==='tomorrow'?tomorrowKey():customDate;if(saving)return;setSaving(true);setFailure('');try{await onSave({title:title.trim(),due:new Date(`${key}T${time||'19:00'}:00`),daily})}catch(err){console.error(err);setFailure('Reminder could not be saved. Your changes are still here.');setSaving(false)}};
 return <div className="quick-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><form className="quick-panel" onSubmit={submit}><div className="sheet-grip"/><div className="quick-top"><span>{editing?'Edit reminder':'Quick reminder'}</span><button type="button" onClick={onClose}>×</button></div><input className="reminder-title-input" autoFocus value={title} onChange={event=>setTitle(event.target.value)} placeholder="Buy Feviquick" maxLength="160" required/><div className="chips"><button type="button" onClick={()=>preset('tonight')}>Tonight</button><button type="button" onClick={()=>preset('tomorrow')}>Tomorrow morning</button><button type="button" onClick={()=>preset('daily')}>Daily</button></div><div className="when-row"><label><span>Day</span><select value={day} onChange={event=>setDay(event.target.value)}><option value="today">Today</option><option value="tomorrow">Tomorrow</option><option value="custom">Custom</option></select></label><label><span>Date</span><input type="date" value={customDate} disabled={day!=='custom'} onChange={event=>setCustomDate(event.target.value)}/></label><label><span>Time</span><input type="time" value={time} onChange={event=>setTime(event.target.value)}/></label></div><label className="repeat-toggle"><input type="checkbox" checked={daily} onChange={event=>setDaily(event.target.checked)}/><span>Repeat daily</span></label>{failure&&<p className="reminder-error" role="alert">{failure}</p>}<button className="save-reminder" disabled={saving}>{saving?'Saving…':'Save reminder'}</button></form></div>
}
export function RemindersPage(){
 const{user}=useAuth(),[items,setItems]=useState([]),[sync,setSync]=useState('Connecting to cloud…'),[syncError,setSyncError]=useState(false),[quickOpen,setQuickOpen]=useState(false),[editing,setEditing]=useState(null),[toast,setToast]=useState(''),[loading,setLoading]=useState(true),[calendarDay,setCalendarDay]=useState(dateKey());
 const toastTimer=useRef(null);useEffect(()=>()=>clearTimeout(toastTimer.current),[]);
 const notify=message=>{setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),1800)};
 useEffect(()=>{const timer=setInterval(()=>setCalendarDay(dateKey()),30000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{setItems([]);setQuickOpen(false);setEditing(null);setLoading(true);setSyncError(false);if(!user)return;setSync('Connecting to cloud…');const reminders=query(collection(db,'users',user.uid,'reminders'),orderBy('dueAt','asc'));return onSnapshot(reminders,{includeMetadataChanges:true},snapshot=>{setItems(snapshot.docs.map(item=>({id:item.id,...item.data()})));setLoading(false);setSync(snapshot.metadata?.fromCache?'Cached · connecting…':'Cloud synced');setSyncError(false)},error=>{console.error(error);setLoading(false);setSync('Cloud sync failed');setSyncError(true)})},[user?.uid]);
 const {overdue,today,upcoming:groups}=useMemo(()=>groupReminders(items),[items,calendarDay]),future=Object.values(groups).flat();
 const refFor=id=>doc(db,'users',user.uid,'reminders',id);
 const save=async({title,due,daily})=>{const data={title,dueAt:Timestamp.fromDate(due),repeat:daily?'daily':'none',completed:false,snoozed:false,updatedAt:serverTimestamp()};if(editing)await updateDoc(refFor(editing.id),data);else await addDoc(collection(db,'users',user.uid,'reminders'),{...data,createdAt:serverTimestamp()});setQuickOpen(false);setEditing(null);notify(editing?'Reminder updated':'Reminder added')};
 const complete=item=>completeReminder({db,doc,runTransaction,Timestamp,serverTimestamp},user.uid,item.id);
 const snooze=async item=>{const due=new Date(Math.max(Date.now(),asDate(item.dueAt).getTime())+3600000);await updateDoc(refFor(item.id),{dueAt:Timestamp.fromDate(due),snoozed:true,updatedAt:serverTimestamp()});notify('Snoozed for 1 hour')};
 const remove=async item=>{if(confirm(`Delete “${item.title}”?`))await deleteDoc(refFor(item.id))};
 const requestNotifications=async()=>{if(!('Notification'in window))return notify('Notifications are not supported here');const permission=await Notification.requestPermission();notify(permission==='granted'?'Notification permission enabled':'Notification permission not granted')};
 const card=item=><ReminderCard key={item.id} item={item} onDone={complete} onSnooze={snooze} onEdit={value=>{setEditing(value);setQuickOpen(true)}} onDelete={remove}/>;
 return <><div className="reminder-shell"><header className="page-head"><div><span className="date-line">{new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</span><h1>Reminders</h1><p>{today.length} {today.length===1?'thing':'things'} left</p><p className={'sync-status '+(syncError?'local':sync==='Cloud synced'?'cloud':'')}>{sync}</p></div><button className="notify-button" onClick={requestNotifications} aria-label="Enable notifications">◌</button></header>{loading&&<div className="reminder-skeletons" role="status" aria-label="Loading reminders"><span/><span/><span/></div>}{syncError&&<p className="reminder-error" role="alert">Reminders could not load. Check your connection and account access.</p>}{overdue.length>0&&<section className="overdue-block" aria-label="Overdue reminders"><div className="section-heading"><span>Overdue</span><b>{overdue.length}</b></div><div className="reminder-list">{overdue.map(card)}</div></section>}<div className="section-heading"><span>Today</span><b>{today.length}</b></div><section className="reminder-list today-list" aria-label="Today's reminders">{today.map(card)}</section>{!loading&&!syncError&&!today.length&&<section className="empty-state"><span>✓</span><h2>{overdue.length?'Nothing scheduled today':'Clear for today'}</h2><p>{overdue.length?'Your overdue reminders are listed above.':'Nothing waiting. Add only what matters.'}</p></section>}<section className="upcoming-block"><div className="section-heading"><span>Upcoming</span><b>{future.length}</b></div><div className="upcoming-list">{Object.entries(groups).map(([key,list])=><section className="date-group" key={key}><h3>{key===tomorrowKey()?'Tomorrow':dateLabel(asDate(list[0].dueAt))}</h3>{list.map(card)}</section>)}</div></section></div><button className="fab" onClick={()=>{setEditing(null);setQuickOpen(true)}} aria-label="Add reminder">+</button>{quickOpen&&<QuickReminder editing={editing} onClose={()=>{setQuickOpen(false);setEditing(null)}} onSave={save}/>}<div className={'toast'+(toast?' show':'')} role="status">{toast}</div></>
}
