import{useCallback,useEffect,useRef,useState}from'react';
import{addDoc,collection,deleteDoc,doc,onSnapshot,orderBy,query,serverTimestamp,setDoc}from'firebase/firestore';
import{db}from'./firebase';
import{useAuth}from'./AuthContext';
import{useTasks}from'./useTasks';
import{cleanStep,newId,normalizeTask,parsePlan,stepFields,taskProgress}from'./task-model';
import{TaskSketch}from'./TaskSketch';
import{TaskDialog}from'./TaskDialog';
const taskId=new URLSearchParams(location.search).get('id');
function compressImage(file){return new Promise((resolve,reject)=>{const image=new Image(),reader=new FileReader();reader.onerror=reject;reader.onload=()=>image.src=reader.result;image.onerror=reject;image.onload=()=>{const scale=Math.min(1,1400/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);let quality=.8,data=canvas.toDataURL('image/jpeg',quality);while(data.length>720000&&quality>.35){quality-=.1;data=canvas.toDataURL('image/jpeg',quality)}if(data.length>900000)reject(Error('Image remains too large'));else resolve(data)};reader.readAsDataURL(file)})}
export function TaskPage(){
 const{user,logout}=useAuth();const{tasks,ready,error,saveTask,deleteTask}=useTasks();
 const[task,setTask]=useState(null),[assets,setAssets]=useState([]),[saveState,setSaveState]=useState('Synced'),[message,setMessage]=useState(''),[importing,setImporting]=useState(false),[plan,setPlan]=useState(''),[sketch,setSketch]=useState(null),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false);
 const draft=useRef(null),pending=useRef({}),timer=useRef(null),chain=useRef(Promise.resolve()),inFlight=useRef(0),toastTimer=useRef(null);
 const notify=useCallback(text=>{setMessage(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setMessage(''),2400)},[]);
 const flush=useCallback(()=>{clearTimeout(timer.current);const patch=pending.current;if(!taskId||!Object.keys(patch).length)return chain.current;pending.current={};inFlight.current++;setSaveState('Saving…');const operation=chain.current.catch(()=>{}).then(()=>saveTask(taskId,patch));chain.current=operation;operation.then(()=>{inFlight.current--;if(!inFlight.current&&!Object.keys(pending.current).length)setSaveState('Synced')},err=>{inFlight.current--;pending.current={...Object.fromEntries(Object.keys(patch).map(key=>[key,draft.current[key]])),...pending.current};console.error(err);setSaveState('Save failed');notify('Could not save changes. Retry before leaving.')});return operation},[saveTask,notify]);
 useEffect(()=>{const source=tasks.find(item=>item.id===taskId);if(source&&!Object.keys(pending.current).length&&!inFlight.current){const normalized=normalizeTask(source);draft.current=normalized;setTask(normalized)}},[tasks]);
 useEffect(()=>{if(!user||!taskId)return;return onSnapshot(query(collection(db,'users',user.uid,'tasks',taskId,'assets'),orderBy('createdAt','desc')),snapshot=>setAssets(snapshot.docs.map(item=>({...item.data(),id:item.id}))),err=>{console.error(err);notify('Attachments could not sync.')})},[user?.uid,notify]);
 useEffect(()=>{const visibility=()=>{if(document.visibilityState==='hidden')flush().catch(()=>{})};document.addEventListener('visibilitychange',visibility);return()=>{document.removeEventListener('visibilitychange',visibility);flush().catch(()=>{});clearTimeout(toastTimer.current)}},[flush]);
 useEffect(()=>{const navigate=event=>{const link=event.target.closest?.('a[href]');if(!link||link.target==='_blank'||event.ctrlKey||event.metaKey||event.shiftKey||event.defaultPrevented||(!Object.keys(pending.current).length&&!inFlight.current))return;if(link.origin!==location.origin)return;event.preventDefault();event.stopPropagation();flush().then(()=>location.href=link.href).catch(()=>notify('Save failed. Your edits are still here.'))};document.addEventListener('click',navigate,true);return()=>document.removeEventListener('click',navigate,true)},[flush,notify]);
 const change=patch=>{draft.current={...draft.current,...patch};setTask(draft.current);pending.current={...pending.current,...patch};setSaveState('Saving…');clearTimeout(timer.current);timer.current=setTimeout(()=>flush().catch(()=>{}),500)};
 const steps=task?.steps||[],active=steps.find(item=>item.id===task?.activeStepId)||steps.find(item=>item.status==='Working')||steps.find(item=>!item.done)||steps[0],index=steps.findIndex(item=>item.id===active?.id),progress=taskProgress(task);
 const select=id=>change({activeStepId:id});
 const editStep=patch=>change(stepFields(steps.map(item=>item.id===active.id?{...item,...patch}:item)));
 const addStep=()=>{const step=cleanStep({id:newId('s'),title:'New step'},steps.length);change({...stepFields([...steps,step]),activeStepId:step.id})};
 const removeStep=()=>{if(!confirm(`Delete “${active.title}”?`))return;const remaining=steps.filter(item=>item.id!==active.id);change({...stepFields(remaining),activeStepId:remaining[Math.min(index,remaining.length-1)]?.id||null})};
 const reorder=(fromId,toId)=>{if(fromId===toId)return;const ordered=[...steps],from=ordered.findIndex(item=>item.id===fromId),to=ordered.findIndex(item=>item.id===toId);if(from<0||to<0)return;const[moved]=ordered.splice(from,1);ordered.splice(to,0,moved);change({...stepFields(ordered),activeStepId:moved.id})};
 const advance=()=>{let nextSteps=steps.map(item=>item.id===active.id?{...item,status:active.done?'Working':active.status==='Working'?'Done':'Working',done:!active.done&&active.status==='Working'}:item),nextId=active.id;const completed=nextSteps[index].done;if(completed)nextId=(nextSteps.slice(index+1).find(item=>!item.done)||nextSteps.find(item=>!item.done))?.id||active.id;change({...stepFields(nextSteps),activeStepId:nextId,status:nextSteps.every(item=>item.done)?'Done':'In Progress'});notify(completed?'Done. Next step selected.':active.done?'Step reopened':'Focus mode started')};
 const assetsPath=()=>collection(db,'users',user.uid,'tasks',taskId,'assets');
 const upload=async(event,stepId)=>{const files=[...event.target.files];event.target.value='';setBusy(true);try{for(const file of files){if(!file.type.startsWith('image/'))continue;const dataUrl=await compressImage(file);await addDoc(assetsPath(),{kind:'image',stepId:stepId||null,name:file.name,dataUrl,createdAt:serverTimestamp()})}notify('Images saved')}catch(err){console.error(err);notify('Image could not be saved.')}finally{setBusy(false)}};
 const thumbnails=list=>list.map(asset=><div className="asset-thumb" key={asset.id}><img src={asset.dataUrl} alt={asset.name||'Task reference'} onClick={()=>setPreview(asset)}/><button className="remove-asset" aria-label="Delete image" onClick={async()=>{if(!confirm('Delete this attachment?'))return;try{await deleteDoc(doc(assetsPath(),asset.id))}catch(err){notify('Attachment could not be deleted.')}}}>×</button></div>);
 const leave=async(event,href)=>{event.preventDefault();try{await flush();location.href=href}catch{notify('Save failed. Your edits are still here.')}};
 if(error)return <div className="workspace" role="alert">{error}</div>;
 if(!taskId)return <div className="workspace"><h2>Choose a task from the dashboard</h2><a href="/invincible/">Open dashboard</a></div>;
 if(!task)return <div className="workspace">{ready?'Task not found.':'Loading task…'} {ready&&<a href="/invincible/">Dashboard</a>}</div>;
 const projectAssets=assets.filter(asset=>!asset.stepId);
 return <div className="workspace" onBlur={()=>flush().catch(()=>{})}>
  <header className="workspace-header"><a className="back-link" href="/invincible/" onClick={event=>leave(event,'/invincible/')}>← <span>Dashboard</span></a><div className="sync-wrap"><span className={'sync-dot '+(saveState==='Save failed'?'error':saveState==='Synced'?'':'saving')}/><span>{saveState}</span>{saveState==='Save failed'&&<button className="ghost-button" onClick={()=>flush().catch(()=>{})}>Retry</button>}</div><button className="ghost-button danger-button" disabled={busy} onClick={async()=>{if(!confirm(`Delete “${task.title||'this task'}” and all its attachments?`))return;setBusy(true);try{await flush();clearTimeout(timer.current);pending.current={};await deleteTask(taskId);location.href='/invincible/'}catch(err){notify('Task could not be deleted.');setBusy(false)}}}>Delete task</button><button className="ghost-button" onClick={async()=>{try{await flush();await logout()}catch{notify('Save failed. Sign out cancelled.')}}}>Sign out</button></header>
  <section className="project-bar panel"><div className="project-identity"><div className="eyebrow">CURRENT PROJECT</div><input className="task-title" aria-label="Task title" value={task.title||''} onChange={event=>change({title:event.target.value})}/><textarea className="task-description" aria-label="Task description" rows="1" value={task.description||''} placeholder="Define the finished result…" onChange={event=>change({description:event.target.value})}/></div><div className="project-progress"><div className="progress-copy"><strong>{progress.pct}%</strong><span>{progress.total?`${progress.done} of ${progress.total} complete`:'Start with the first step'}</span></div><div className="progress-track"><span style={{width:progress.pct+'%'}}/></div></div><select aria-label="Project status" value={task.status||'Backlog'} onChange={event=>change({status:event.target.value})}>{['Backlog','Today','In Progress','Done'].map(value=><option key={value}>{value}</option>)}</select></section>
  <div className="focus-layout"><aside className="journey panel"><div className="journey-head"><div><div className="eyebrow">YOUR ROUTE</div><h2>Steps</h2></div><span className="step-count">{steps.length} steps</span></div><div className="route-list">{steps.map((step,i)=><button key={step.id} className={'route-step '+(step.done?'is-done ':'')+(step.id===active?.id?'is-active':'')} draggable onDragStart={event=>event.dataTransfer.setData('text/plain',step.id)} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();reorder(event.dataTransfer.getData('text/plain'),step.id)}} onClick={()=>select(step.id)}><span className="route-grip" aria-hidden="true">⋮⋮</span><span className="route-marker">{step.done?'✓':String(i+1).padStart(2,'0')}</span><span className="route-copy"><strong>{step.title}</strong><small>{step.id===active?.id?'Current focus':step.done?'Completed':step.status}</small></span><span className="route-arrow">›</span></button>)}</div>{!steps.length&&<div className="empty-state"><div className="empty-orbit">+</div><h3>No route yet</h3><p>Paste a plan to create actionable steps.</p></div>}<div className="journey-actions"><button className="secondary-button" onClick={()=>setImporting(true)}>Paste AI plan</button><button className="secondary-button" onClick={addStep}>+ Add step</button></div></aside>
   <section className="mission panel">{!active?<div className="mission-empty"><div className="mission-symbol">→</div><h2>Create your first step</h2><p>Your next action will appear here.</p><button className="primary-button" onClick={addStep}>Add first step</button></div>:<div id="mission-content"><div className="mission-topline"><div><div className="eyebrow">DO THIS NOW</div><span className="mission-index">STEP {String(index+1).padStart(2,'0')} OF {String(steps.length).padStart(2,'0')}</span></div><select className="step-status" aria-label="Current step status" value={active.status} onChange={event=>editStep({status:event.target.value,done:event.target.value==='Done'})}>{['Not Started','Working','Blocked','Done'].map(value=><option key={value}>{value}</option>)}</select></div><input className="mission-title" aria-label="Current step title" value={active.title} onChange={event=>editStep({title:event.target.value})}/><label className="mission-label" htmlFor="active-step-notes">Working notes</label><textarea id="active-step-notes" className="mission-notes" value={active.notes} placeholder="Write the exact decision, measurement or next move here…" onChange={event=>editStep({notes:event.target.value})}/><div className="focus-assets">{thumbnails(assets.filter(asset=>asset.stepId===active.id))}</div><div className="mission-tools"><label className="tool-button">＋ Add image<input type="file" accept="image/*" multiple hidden disabled={busy} onChange={event=>upload(event,active.id)}/></label><button className="tool-button" onClick={()=>setSketch(active)}>✎ Draw note</button><button className="tool-button danger-text" onClick={removeStep}>Delete step</button></div><div className="mission-nav"><button className="nav-step-button" aria-label="Previous step" disabled={index<=0} onClick={()=>select(steps[index-1].id)}>←</button><button className={'mission-cta '+(active.status==='Working'?'is-complete':'')} onClick={advance}>{active.done?'Reopen this step':active.status==='Working'?'Complete & continue':'Start this step'}<span>→</span></button><button className="nav-step-button" aria-label="Next step" disabled={index>=steps.length-1} onClick={()=>select(steps[index+1].id)}>→</button></div></div>}</section></div>
  <details className="project-vault panel"><summary><span><span className="eyebrow">PROJECT VAULT</span><strong>References & loose notes</strong></span><span className="vault-hint">Open when needed ↓</span></summary><div className="vault-grid"><section><div className="section-head"><h2>References</h2><label className="upload-button">+ Add image<input type="file" accept="image/*" multiple hidden disabled={busy} onChange={event=>upload(event,null)}/></label></div><div className="reference-gallery">{thumbnails(projectAssets)}</div>{!projectAssets.length&&<p className="muted">Store screenshots, dimensions, diagrams or inspiration here.</p>}</section><section><h2>Scratchpad</h2><textarea className="scratchpad" aria-label="Scratchpad" value={task.scratchpad} onChange={event=>change({scratchpad:event.target.value})}/>{(task.quickNotes||[]).map((note,i)=><p className="muted" key={i}>{note.text}</p>)}</section></div></details>
  {importing&&<TaskDialog label="Plan importer" onClose={()=>setImporting(false)}><div className="dialog-head"><h2>Turn a ChatGPT plan into steps</h2><button className="close-button" aria-label="Close" onClick={()=>setImporting(false)}>×</button></div><p>Paste a numbered list, bullet list, or Markdown table.</p><textarea rows="11" aria-label="AI plan" value={plan} onChange={event=>setPlan(event.target.value)}/><div className="dialog-actions"><button className="secondary-button" onClick={()=>setImporting(false)}>Cancel</button><button className="primary-button" onClick={()=>{const parsed=parsePlan(plan);if(!parsed.length){notify('No steps detected');return}const extra=parsed.map((title,i)=>cleanStep({id:newId('s'),title},steps.length+i));change({...stepFields([...steps,...extra]),activeStepId:active?.id||extra[0].id});setPlan('');setImporting(false);notify(`${extra.length} steps created`)}}>Create steps</button></div></TaskDialog>}
  {sketch&&<TaskSketch step={sketch} existing={assets.find(asset=>asset.stepId===sketch.id&&asset.kind==='sketch')} onClose={()=>setSketch(null)} onSave={async dataUrl=>{const existing=assets.find(asset=>asset.stepId===sketch.id&&asset.kind==='sketch'),payload={kind:'sketch',stepId:sketch.id,name:sketch.title+' sketch',dataUrl,createdAt:serverTimestamp()};if(existing)await setDoc(doc(assetsPath(),existing.id),payload,{merge:true});else await addDoc(assetsPath(),payload);notify('Sketch saved')}}/>}
  {preview&&<TaskDialog label="Reference image" className="image-preview" onClose={()=>setPreview(null)}><button className="close-button" aria-label="Close" onClick={()=>setPreview(null)}>×</button><img src={preview.dataUrl} alt={preview.name}/></TaskDialog>}
  <div className={'toast '+(message?'show':'')} role="status">{message}</div>
 </div>
}
