export const taskStatuses=['Backlog','In Progress','Done'];
export const newId=prefix=>`${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
export const taskSteps=task=>Array.isArray(task?.steps)&&task.steps.length?task.steps:task?.subtasks||[];
export const cleanStep=(step,index)=>({...step,id:step.id||`legacy_${index}`,title:step.title||step.text||`Step ${index+1}`,notes:step.notes||'',status:step.status||(step.done?'Done':'Not Started'),done:Boolean(step.done||step.status==='Done')});
export const normalizeTask=task=>({...task,steps:taskSteps(task).map(cleanStep),scratchpad:task.scratchpad||'',activeStepId:task.activeStepId||null});
export const stepFields=steps=>({steps:steps.map(cleanStep),subtasks:steps.map(step=>({text:step.title||step.text||'',done:Boolean(step.done||step.status==='Done')}))});
export function taskProgress(task){const steps=taskSteps(task),done=steps.filter(step=>step.done||step.status==='Done').length;return{done,total:steps.length,pct:steps.length?Math.round(done/steps.length*100):0}}
export function chooseFocusTask(tasks){const priority=status=>status==='Today'?3:status==='In Progress'?2:status==='Backlog'?1:0;return tasks.filter(task=>task.status!=='Done').sort((a,b)=>priority(b.status)-priority(a.status)||taskProgress(b).pct-taskProgress(a).pct||taskProgress(b).done-taskProgress(a).done||Number(b.updatedAt?.seconds||b.updatedAt||0)-Number(a.updatedAt?.seconds||a.updatedAt||0))[0]||null}
export function parsePlan(input){const lines=input.split(/\r?\n/).map(line=>line.trim()).filter(Boolean),rows=lines.filter(line=>/^\|.*\|$/.test(line)&&!/^\|?[\s:|-]+\|?$/.test(line));if(rows.length)return rows.slice(1).map(row=>row.split('|').map(cell=>cell.trim()).filter(Boolean)).map(cells=>cells.find(cell=>!/^\d+$/.test(cell)&&!/^step$/i.test(cell)&&!/^duration$/i.test(cell))||cells[0]).filter(Boolean);return lines.map(line=>line.replace(/^[-*•]\s+/,'').replace(/^\d+[.)]\s+/,'').trim()).filter(line=>line&&!/^#{1,6}\s/.test(line))}
