import{useEffect,useRef,useState}from'react';
import{TaskDialog}from'./TaskDialog';
export function TaskSketch({step,existing,onSave,onClose}){
 const canvas=useRef(null),base=useRef(null),strokes=useRef([]),current=useRef(null);const[tool,setTool]=useState('pen'),[size,setSize]=useState(4),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const draw=()=>{const c=canvas.current,ctx=c.getContext('2d'),ratio=c.width/c.clientWidth;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.fillStyle='#f7faf8';ctx.fillRect(0,0,c.clientWidth,c.clientHeight);if(base.current)ctx.drawImage(base.current,0,0,c.clientWidth,c.clientHeight);ctx.lineCap='round';ctx.lineJoin='round';for(const stroke of strokes.current){ctx.strokeStyle=stroke.tool==='eraser'?'#f7faf8':'#132b31';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=stroke.size;ctx.beginPath();const first=stroke.points[0];if(stroke.points.length===1){ctx.arc(first.x*c.clientWidth,first.y*c.clientHeight,stroke.size/2,0,Math.PI*2);ctx.fill()}else{ctx.moveTo(first.x*c.clientWidth,first.y*c.clientHeight);for(const p of stroke.points.slice(1))ctx.lineTo(p.x*c.clientWidth,p.y*c.clientHeight);ctx.stroke()}}};
 useEffect(()=>{const c=canvas.current;const resize=()=>{const ratio=Math.min(devicePixelRatio||1,2);c.width=Math.round(c.clientWidth*ratio);c.height=Math.round(c.clientHeight*ratio);draw()};const observer=new ResizeObserver(resize);observer.observe(c);resize();if(existing?.dataUrl){const image=new Image();image.onload=()=>{base.current=image;draw()};image.src=existing.dataUrl}return()=>observer.disconnect()},[]);
 const point=event=>{const rect=canvas.current.getBoundingClientRect();return{x:(event.clientX-rect.left)/rect.width,y:(event.clientY-rect.top)/rect.height}};
 return <TaskDialog label="Handwritten note" className="sketch-dialog" onClose={busy?undefined:onClose}><div className="dialog-head"><div><div className="eyebrow">HANDWRITTEN NOTE</div><h2>{step.title}</h2></div><button className="close-button" disabled={busy} onClick={onClose} aria-label="Close">×</button></div><div className="sketch-tools">{['pen','eraser'].map(value=><button key={value} className={'tool '+(tool===value?'active':'')} onClick={()=>setTool(value)}>{value==='pen'?'Pen':'Eraser'}</button>)}<label>Size <input type="range" min="2" max="24" value={size} onChange={event=>setSize(Number(event.target.value))}/></label><button className="tool" onClick={()=>{strokes.current.pop();draw()}}>Undo</button><button className="tool danger" onClick={()=>{base.current=null;strokes.current=[];draw()}}>Clear</button></div><div className="canvas-wrap"><canvas ref={canvas} onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);current.current={tool,size,points:[point(event)]};strokes.current.push(current.current);draw()}} onPointerMove={event=>{if(!current.current)return;current.current.points.push(point(event));draw()}} onPointerUp={()=>current.current=null} onPointerCancel={()=>current.current=null}/></div>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><button className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy} onClick={async()=>{setBusy(true);try{await onSave(canvas.current.toDataURL('image/jpeg',.82));onClose()}catch(err){console.error(err);setError('Sketch could not be saved.');setBusy(false)}}}>{busy?'Saving…':'Save sketch'}</button></div></TaskDialog>
}
