import{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{collection,doc,getDoc,getDocs,onSnapshot,query as firestoreQuery,serverTimestamp,setDoc,where}from'firebase/firestore';
import{useAuth}from'./AuthContext';
import{db}from'./firebase';
import'./workday.css';

const personalSpaceId='personal';
const blank=()=>({name:'My Workday',ownerUid:'',ownerEmail:'',editorEmails:[],tasks:[],routines:[]});
const blankDraft=()=>({action:'',subject:'',outcome:'',status:'pending',pendingReason:'',nextAction:'',updatedAtMs:0});
const workStatuses={todo:'To Do',progress:'In Progress',pending:'Pending',done:'Completed'};
const validStatus=value=>Object.hasOwn(workStatuses,value)?value:'todo';
const waitForCloud=promise=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>{const error=new Error('Cloud confirmation timed out');error.code='cloud-timeout';reject(error)},12000);promise.then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})});
const weekDates=value=>{const monday=new Date(value+'T12:00:00');monday.setDate(monday.getDate()-(monday.getDay()+6)%7);return Array.from({length:7},(_,i)=>{const day=new Date(monday);day.setDate(day.getDate()+i);return{date:localDate(day),day:day.getDate(),label:['M','T','W','T','F','S','S'][i],full:formatDate(localDate(day))}})};
function WorkStatusIcon({status}){return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/>{status==='done'?<path d="m7.5 12 3 3 6-6"/>:status==='progress'?<path fill="currentColor" stroke="none" d="M12 3a9 9 0 0 0 0 18Z"/>:null}</svg>}
const newId=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
const localDate=(date=new Date())=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,10);
const normalizeEmail=value=>(value||'').trim().toLowerCase();
const formatDate=date=>new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'short',year:'numeric'}).format(new Date(date+'T12:00:00'));
const previousDate=date=>{const value=new Date(date+'T12:00:00');value.setDate(value.getDate()-1);return localDate(value)};
const taskLabel=task=>[task.action,task.subject].filter(Boolean).join(' — ')||(task.title||task.outcome||'Untitled work').trim();
const taskDetail=task=>(task.outcome||task.progressNote||'').trim();
const cleanSentence=value=>{const text=(value||'').trim().replace(/[.]+$/,'');return text?text.charAt(0).toUpperCase()+text.slice(1)+'.':''};
const reportSentence=(task,note='')=>{const action=(task.action||'').trim(),subject=(task.subject||'').trim(),key=action.toLowerCase();let line='';if(key==='mailed')line=subject?`Mailed to ${subject}`:'Mailed';else if(key==='telephonic talk'||key==='had telephonic talk')line=subject?`Had telephonic talk with ${subject}`:'Had telephonic talk';else line=[action,subject].filter(Boolean).join(' ')||(task.title||task.outcome||'').trim();const detail=(note||taskDetail(task)).trim().replace(/[.]+$/,'');return cleanSentence(line+(detail?` — ${detail}`:''))};

function Modal({title,eyebrow,children,onClose,wide=false}){
 return <div className="wd-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className={'wd-modal'+(wide?' wide':'')} role="dialog" aria-modal="true"><header><div><span className="wd-eyebrow">{eyebrow}</span><h2>{title}</h2></div><button type="button" onClick={onClose}>×</button></header>{children}</section></div>
}

export function WorkdayPage(){
 const{user}=useAuth();
 const[spaces,setSpaces]=useState([]),[spaceId,setSpaceId]=useState(''),[work,setWork]=useState(blank),[selectedDate,setSelectedDate]=useState(localDate()),[sync,setSync]=useState('Finding workspace…'),[toast,setToast]=useState(''),[workspaceNotice,setWorkspaceNotice]=useState(''),[workspaceReady,setWorkspaceReady]=useState(false);
 const[draft,setDraft]=useState(blankDraft),[draftLoadedKey,setDraftLoadedKey]=useState(''),[adding,setAdding]=useState(false);
 const[pendingTask,setPendingTask]=useState(null),[editingTask,setEditingTask]=useState(null),[routineOpen,setRoutineOpen]=useState(false),[shareOpen,setShareOpen]=useState(false),[reportOpen,setReportOpen]=useState(false);
 const saveTimer=useRef(),draftTimer=useRef(),toastTimer=useRef(),rolling=useRef(false),selectedDateRef=useRef(selectedDate),pendingWork=useRef(null),saveChain=useRef(Promise.resolve()),latestDraft=useRef(draft),draftTask=useRef(null);
 selectedDateRef.current=selectedDate;
 latestDraft.current=draft;
 const personalRef=useMemo(()=>doc(db,'users',user.uid,'workday','main'),[user.uid]);
 const workRef=useMemo(()=>spaceId?(spaceId===personalSpaceId?personalRef:doc(db,'workdaySpaces',spaceId)):null,[personalRef,spaceId]);
 const sharingCopy=useRef(null);
 const draftKey=`invincible.workdayDraft.${user.uid}.${spaceId||'unassigned'}.${selectedDate}`,draftDoc=useMemo(()=>spaceId?doc(db,'users',user.uid,'workdayDrafts',`${spaceId}_${selectedDate}`):null,[user.uid,spaceId,selectedDate]);
 const[entryFocused,setEntryFocused]=useState(false),[workspaceRetry,setWorkspaceRetry]=useState(0),[workspaceError,setWorkspaceError]=useState('');
 const composerRef=useRef(null);
 useEffect(()=>{if(!entryFocused)return;const viewport=window.visualViewport,update=()=>{document.documentElement.style.setProperty('--wd-editor-top',(viewport?.offsetTop||0)+'px');document.documentElement.style.setProperty('--wd-editor-height',(viewport?.height||window.innerHeight)+'px')};document.body.classList.add('wd-entry-focused');update();viewport?.addEventListener('resize',update);viewport?.addEventListener('scroll',update);return()=>{document.body.classList.remove('wd-entry-focused');viewport?.removeEventListener('resize',update);viewport?.removeEventListener('scroll',update);document.documentElement.style.removeProperty('--wd-editor-top');document.documentElement.style.removeProperty('--wd-editor-height')}},[entryFocused]);
 const closeEntry=()=>{document.activeElement?.blur();setEntryFocused(false)};
 const notify=message=>{setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),2000)};

 useEffect(()=>{let cancelled=false;
  setSync('Opening your Workday…');setWorkspaceError('');setWorkspaceNotice('');setSpaceId('');setSpaces([]);setWork(blank());pendingWork.current=null;clearTimeout(saveTimer.current);
  (async()=>{
   const snapshot=await waitForCloud(getDoc(personalRef));
   const personal=snapshot.exists()?{...blank(),...snapshot.data()}:{...blank(),ownerUid:user.uid,ownerEmail:normalizeEmail(user.email),name:'My Workday',createdAt:serverTimestamp()};
   if(!snapshot.exists())await waitForCloud(setDoc(personalRef,{...personal,updatedAt:serverTimestamp()}));
   if(cancelled)return;
   setWork(personal);setSpaces([{...personal,id:personalSpaceId}]);setSpaceId(personalSpaceId);
   // Shared workspace discovery is optional and must never block personal saving.
   const owned=firestoreQuery(collection(db,'workdaySpaces'),where('ownerUid','==',user.uid));
   const shared=firestoreQuery(collection(db,'workdaySpaces'),where('editorEmails','array-contains',normalizeEmail(user.email)));
   const results=await Promise.allSettled([waitForCloud(getDocs(owned)),waitForCloud(getDocs(shared))]),map=new Map();
   results.filter(result=>result.status==='fulfilled').forEach(result=>result.value.docs.forEach(item=>map.set(item.id,{...item.data(),id:item.id})));
   if(cancelled)return;
   setSpaces(current=>[current.find(space=>space.id===personalSpaceId)||{...personal,id:personalSpaceId},...[...map.values()].filter(space=>space.id!==personalSpaceId)]);
   if(results.some(result=>result.status==='rejected'))setWorkspaceNotice('Shared workspaces are unavailable. You can use My Workday.');
   else if(map.size)setWorkspaceNotice('Your earlier workspaces are available in the workspace selector.');
  })().catch(error=>{if(cancelled)return;console.error(error);setSync('Could not open Workday');setWorkspaceError(error.code==='permission-denied'?'Account storage access denied. Your entry stays on this device.':error.code==='cloud-timeout'||error.code==='unavailable'?'Connection unavailable. Your entry stays on this device.':'Workday could not load ('+(error.code||'unknown error')+'). Your entry stays on this device.')});
  return()=>{cancelled=true};
 },[personalRef,user.uid,user.email,workspaceRetry]);


 useEffect(()=>{setWorkspaceReady(false);if(!workRef)return;setSync('Syncing workspace…');return onSnapshot(workRef,snapshot=>{
  if(!snapshot.exists()){setWorkspaceError('This workspace no longer exists. Choose My Workday.');return}
  let next={...blank(),...snapshot.data(),tasks:snapshot.data().tasks||[],routines:snapshot.data().routines||[],editorEmails:snapshot.data().editorEmails||[]};
  if(!rolling.current&&selectedDateRef.current===localDate()){
   const today=localDate(),existing=new Set(next.tasks.filter(task=>task.date===today&&task.carryFromId).map(task=>task.carryFromId)),latest=new Map();
   next.tasks.filter(task=>task.date<today&&!task.archived&&task.status!=='done'&&!task.rolledForward).sort((a,b)=>b.date.localeCompare(a.date)).forEach(task=>{const key=task.chainId||task.id;if(!latest.has(key))latest.set(key,task)});
   const carry=[...latest.values()].filter(task=>!existing.has(task.id));
   if(carry.length){rolling.current=true;const sourceIds=new Set(carry.map(task=>task.id));next={...next,tasks:[...next.tasks.map(task=>sourceIds.has(task.id)?{...task,rolledForward:true}:task),...carry.map(task=>({...task,id:newId(),date:today,status:validStatus(task.status),carryFromId:task.id,chainId:task.chainId||task.id,rolledForward:false,createdAt:Date.now(),completedAt:null}))]};setDoc(workRef,{...next,updatedAt:serverTimestamp()},{merge:true}).catch(error=>{console.error(error);setSync('Save failed');notify('Could not carry work forward. Retry when connected.')}).finally(()=>{rolling.current=false});notify(`${carry.length} unfinished ${carry.length===1?'task':'tasks'} carried forward`)}
  }
  setWork(next);setWorkspaceReady(true);setSpaces(current=>current.map(space=>space.id===spaceId?{id:spaceId,...next}:space));setSync(snapshot.metadata?.hasPendingWrites?'Awaiting cloud confirmation':pendingWork.current?'Saving…':'Cloud synced');
 },error=>{console.error(error);setSync('Sync failed');setWorkspaceError('This workspace could not sync. Your entry stays on this device.')})},[workRef,spaceId]);

 useEffect(()=>{if(!draftKey)return;let cancelled=false;setDraftLoadedKey('');let local=blankDraft();try{local={...local,...JSON.parse(localStorage.getItem(draftKey)||localStorage.getItem(`invincible.workdayDraft.${user.uid}.unassigned.${selectedDate}`)||'{}')}}catch{}setDraft(local);if(!draftDoc){setDraftLoadedKey(draftKey);return}waitForCloud(getDoc(draftDoc)).then(snapshot=>{if(cancelled)return;const remote=snapshot.exists()?{...blankDraft(),...snapshot.data()}:blankDraft(),next=Number(remote.updatedAtMs||0)>Number(local.updatedAtMs||0)?remote:local;setDraft({...blankDraft(),action:next.action||'',subject:next.subject||'',outcome:next.outcome||'',status:validStatus(next.status)==='todo'?'pending':validStatus(next.status),pendingReason:next.pendingReason||'',nextAction:next.nextAction||'',updatedAtMs:Number(next.updatedAtMs||0)});setDraftLoadedKey(draftKey)}).catch(error=>{console.error(error);if(!cancelled)setDraftLoadedKey(draftKey)});return()=>{cancelled=true}},[draftDoc,draftKey]);
 useEffect(()=>{if(draftLoadedKey!==draftKey)return;const payload={...draft,updatedAtMs:Date.now()};localStorage.setItem(draftKey,JSON.stringify(payload));clearTimeout(draftTimer.current);if(!draftDoc)return;draftTimer.current=setTimeout(()=>setDoc(draftDoc,{...payload,updatedAt:serverTimestamp()},{merge:true}).catch(error=>{console.error(error);setSync('Draft sync failed')}),400);return()=>clearTimeout(draftTimer.current)},[draft,draftDoc,draftKey,draftLoadedKey]);

 const persist=useCallback((next,immediate=false)=>{if(!workRef)return Promise.resolve(false);clearTimeout(saveTimer.current);pendingWork.current=next;const execute=()=>{const target=next;setSync('Saving…');const operation=saveChain.current.catch(()=>{}).then(async()=>{try{const write=setDoc(workRef,{...target,updatedAt:serverTimestamp()},{merge:true});write.then(()=>{if(pendingWork.current===target){pendingWork.current=null;setSync('Saved')}},()=>{});await waitForCloud(write);return true}catch(error){console.error(error);if(error.code==='cloud-timeout'){setSync('Awaiting cloud confirmation');notify('Connection is slow. Your draft is kept; retry when connected.')}else{setSync('Save failed');notify('Could not save changes. Your draft is kept.')}return false}});saveChain.current=operation;return operation};if(immediate)return execute();saveTimer.current=setTimeout(execute,220)},[workRef]);
 const switchSpace=async id=>{if(adding)return;if(pendingWork.current&&!await persist(pendingWork.current,true))return;clearTimeout(saveTimer.current);pendingWork.current=null;setWorkspaceError('');setWorkspaceReady(false);setWork({...blank(),...spaces.find(space=>space.id===id)});setSpaceId(id)};
 useEffect(()=>{const flush=()=>{if(pendingWork.current)persist(pendingWork.current,true);if(draftDoc&&draftLoadedKey===draftKey){const payload={...latestDraft.current,updatedAtMs:Date.now()};localStorage.setItem(draftKey,JSON.stringify(payload));setDoc(draftDoc,{...payload,updatedAt:serverTimestamp()},{merge:true}).catch(()=>{})}};const visibility=()=>document.visibilityState==='hidden'&&flush();document.addEventListener('visibilitychange',visibility);window.addEventListener('pagehide',flush);return()=>{document.removeEventListener('visibilitychange',visibility);window.removeEventListener('pagehide',flush)}},[persist,draftDoc,draftKey,draftLoadedKey]);
 const updateWork=(updater,immediate=false)=>setWork(current=>{const next=typeof updater==='function'?updater(current):updater;persist(next,immediate);return next});
 const tasks=useMemo(()=>work.tasks.filter(task=>task.date===selectedDate&&!task.archived),[work.tasks,selectedDate]);
 const groups=useMemo(()=>({todo:tasks.filter(task=>task.status==='todo'),progress:tasks.filter(task=>task.status==='progress'),pending:tasks.filter(task=>task.status==='pending'),done:tasks.filter(task=>task.status==='done')}),[tasks]);
 const isOwner=work.ownerUid===user.uid;
 const shiftDay=amount=>{const date=new Date(selectedDate+'T12:00:00');date.setDate(date.getDate()+amount);setSelectedDate(localDate(date))};

 const addTask=async event=>{
  event.preventDefault();if(adding||!workspaceReady||!draftDoc||!draftKey||draftLoadedKey!==draftKey)return;
  const action=draft.action.trim(),subject=draft.subject.trim(),outcome=draft.outcome.trim(),status=validStatus(draft.status);
  if(!action&&!subject&&!outcome)return notify('Write at least one part of the work');
  const title=[action,subject].filter(Boolean).join(' — ')||outcome,fingerprint=JSON.stringify([draftKey,action,subject,outcome,status,draft.pendingReason,draft.nextAction]);
  if(!draftTask.current){try{draftTask.current=JSON.parse(localStorage.getItem(draftKey+'.task')||'null')}catch{}}
  if(draftTask.current?.fingerprint!==fingerprint)draftTask.current={fingerprint,id:newId()};
  localStorage.setItem(draftKey+'.task',JSON.stringify(draftTask.current));
  const task={id:draftTask.current.id,chainId:'',title,action,subject,outcome,date:selectedDate,status,progressNote:'',pendingReason:status==='pending'?draft.pendingReason.trim():'',nextAction:status==='pending'?draft.nextAction.trim():'',createdAt:Date.now(),completedAt:status==='done'?Date.now():null,rolledForward:false},next={...work,tasks:[...work.tasks.filter(item=>item.id!==task.id),task]};
  setAdding(true);clearTimeout(draftTimer.current);
  try{const saved=await persist(next,true);if(!saved)return;setWork(next);const cleared=blankDraft(),payload={...cleared,updatedAtMs:Date.now()};setDraft(cleared);localStorage.setItem(draftKey,JSON.stringify(payload));draftTask.current=null;localStorage.removeItem(draftKey+'.task');localStorage.removeItem(`invincible.workdayDraft.${user.uid}.unassigned.${selectedDate}`);setDoc(draftDoc,{...payload,updatedAt:serverTimestamp()},{merge:true}).catch(error=>console.error(error));notify('Work saved as '+workStatuses[status]);closeEntry()}catch(error){console.error(error);notify('Could not finish saving. Your draft is kept.')}finally{setAdding(false)}
 };
 const changeStatus=(task,status)=>{if(status==='pending')return setPendingTask(task);updateWork(current=>({...current,tasks:current.tasks.map(item=>item.id===task.id?{...item,status,completedAt:status==='done'?Date.now():null,pendingReason:'',nextAction:''}:item)}))};
 const savePending=event=>{event.preventDefault();const data=new FormData(event.currentTarget);updateWork(current=>({...current,tasks:current.tasks.map(item=>item.id===pendingTask.id?{...item,status:'pending',pendingReason:data.get('pendingReason').trim(),nextAction:data.get('nextAction').trim(),completedAt:null}:item)}));setPendingTask(null)};
 const saveEdit=event=>{event.preventDefault();const data=new FormData(event.currentTarget),nextAction=data.get('action').trim(),nextSubject=data.get('subject').trim(),nextOutcome=data.get('outcome').trim(),status=validStatus(data.get('status'));if(!nextAction&&!nextSubject&&!nextOutcome)return notify('Keep at least one field');updateWork(current=>({...current,tasks:current.tasks.map(item=>item.id===editingTask.id?{...item,action:nextAction,subject:nextSubject,outcome:nextOutcome,title:[nextAction,nextSubject].filter(Boolean).join(' — ')||nextOutcome,progressNote:'',status,completedAt:status==='done'?(item.completedAt||Date.now()):null,pendingReason:status==='pending'?data.get('pendingReason').trim():'',nextAction:status==='pending'?data.get('nextAction').trim():''}:item)}));setEditingTask(null)};
 const deleteTask=()=>{if(!confirm(`Delete “${editingTask.title}”?`))return;updateWork(current=>({...current,tasks:current.tasks.filter(item=>item.id!==editingTask.id)}));setEditingTask(null)};

 const addRoutine=title=>updateWork(current=>({...current,routines:[...current.routines,{id:newId(),title}]}));
 const deleteRoutine=id=>updateWork(current=>({...current,routines:current.routines.filter(item=>item.id!==id)}));
 const loadRoutines=()=>{const existing=new Set(tasks.map(task=>task.title.toLowerCase())),fresh=work.routines.filter(item=>!existing.has(item.title.toLowerCase()));if(!fresh.length)return work.routines.length?notify('Today’s routine is already added'):setRoutineOpen(true);updateWork(current=>({...current,tasks:[...current.tasks,...fresh.map(item=>({id:newId(),chainId:'',title:item.title,date:selectedDate,status:'todo',progressNote:'',pendingReason:'',nextAction:'',createdAt:Date.now(),completedAt:null,rolledForward:false,routineId:item.id}))]}));notify(`${fresh.length} routine ${fresh.length===1?'task':'tasks'} added`)};
 const invite=async email=>{
  const value=normalizeEmail(email);if(!value||value===work.ownerEmail||work.editorEmails.includes(value))return false;
  const next={...work,editorEmails:[...work.editorEmails,value]};
  if(spaceId===personalSpaceId){
   if(pendingWork.current&&!await persist(pendingWork.current,true))return false;
   const id=sharingCopy.current||(sharingCopy.current=newId());
   try{await waitForCloud(setDoc(doc(db,'workdaySpaces',id),{...next,name:'Shared Workday',createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));setSpaces(current=>[...current.filter(space=>space.id!==id),{...next,id,name:'Shared Workday'}]);pendingWork.current=null;clearTimeout(saveTimer.current);setWork({...next,name:'Shared Workday'});setSpaceId(id);sharingCopy.current=null;setWorkspaceNotice('Shared copy opened. Your personal Workday is kept separately.');notify('Shared copy created for '+value);return true}
   catch(error){console.error(error);notify('Sharing unavailable. Your personal work is still saved.');return false}
  }
  if(!await persist(next,true))return false;setWork(next);notify('Workspace shared with '+value);return true;
 };
 const removeEditor=async value=>{const next={...work,editorEmails:work.editorEmails.filter(email=>email!==value)};if(await persist(next,true)){setWork(next);notify('Access removed')}};


 const report=useMemo(()=>{const section=(title,list,note)=>list.length?`${title}\n${list.map(task=>`• ${reportSentence(task,note(task))}`).join('\n')}\n\n`:'';let text=`Daily Work Report — ${new Intl.DateTimeFormat('en-GB').format(new Date(selectedDate+'T12:00:00'))}\n\n`;text+=section('✅ Jobs Completed',groups.done,()=>'');text+=section('🔄 Jobs In Progress',groups.progress,()=>'');text+=section('⏳ Pending / Backlog',[...groups.pending,...groups.todo],task=>task.pendingReason||'');const next=tasks.filter(task=>task.status!=='done').map(task=>task.nextAction||(task.status==='progress'?`Finish ${taskLabel(task)}`:`Complete ${taskLabel(task)}`));if(next.length)text+=`📌 Next Working Day\n${next.map(value=>`• ${cleanSentence(value)}`).join('\n')}\n`;return text.trim()},[tasks,groups,selectedDate]);
 const copyReport=async()=>{try{await navigator.clipboard.writeText(report);notify('Report copied — ready for WhatsApp')}catch{notify('Clipboard access was blocked')}};

 return <div className="workday-shell">
  <header className="wd-hero"><div><span className="wd-eyebrow">Workday</span><h1>{new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'short'}).format(new Date(selectedDate+'T12:00:00'))}</h1><p>One action at a time.</p></div><div className="wd-space-actions"><select value={spaceId} disabled={adding} onChange={event=>switchSpace(event.target.value)}>{spaces.map(space=><option key={space.id} value={space.id}>{space.name||'Workday'}{space.ownerUid===user.uid?'':' · shared with me'}</option>)}</select>{isOwner&&<button className="wd-ghost" disabled={!workspaceReady} onClick={()=>setShareOpen(true)}>Share</button>}</div></header>
  <div className={'wd-connection '+(sync==='Cloud synced'||sync==='Saved'?'ok':sync.includes('failed')||sync.includes('Could not')?'error':'')}>{sync}{workspaceNotice&&<span className="wd-hint">{' · '+workspaceNotice}</span>}{workspaceError&&<><span className="wd-workspace-error">{workspaceError}</span><button type="button" className="wd-retry" onClick={()=>setWorkspaceRetry(value=>value+1)}>Retry</button></>}</div>
  <div className="wd-week" aria-label="Work week">{weekDates(selectedDate).map(day=><button type="button" key={day.date} className={day.date===selectedDate?'selected':''} disabled={day.date>localDate()} aria-label={day.full} aria-pressed={day.date===selectedDate} onClick={()=>setSelectedDate(day.date)}><span>{day.label}</span><strong>{day.day}</strong></button>)}</div><section className="wd-day-strip"><div className="wd-date-control"><button onClick={()=>shiftDay(-1)}>‹</button><label><strong>{selectedDate===localDate()?'Today':selectedDate===previousDate(localDate())?'Yesterday':formatDate(selectedDate).split(',')[0]}</strong><span>{formatDate(selectedDate)}</span><input type="date" value={selectedDate} max={localDate()} onChange={event=>setSelectedDate(event.target.value)}/></label><button disabled={selectedDate>=localDate()} onClick={()=>shiftDay(1)}>›</button></div><div className="wd-metrics">{[['done',groups.done.length,'Completed'],['progress',groups.progress.length,'In Progress'],['pending',groups.pending.length+groups.todo.length,'Pending']].map(([status,count,label])=><span key={status} className={status} aria-label={count+' '+label}><WorkStatusIcon status={status}/><strong>{count}</strong><small>{label}</small></span>)}</div></section>
  <form ref={composerRef} className={'wd-composer'+(entryFocused?' is-editing':'')} onFocusCapture={event=>{if(window.matchMedia('(max-width:700px)').matches&&event.target.matches('input,select,textarea'))setEntryFocused(true)}} onKeyDown={event=>{if(event.key==='Escape')closeEntry()}} onSubmit={addTask}><div className="wd-composer-head"><div><span className="wd-eyebrow">NEW WORK</span><strong>What did you do?</strong></div><span className="wd-draft-state">{draftLoadedKey===draftKey?'Draft kept':'Restoring…'}</span><button className="wd-entry-close" type="button" onClick={closeEntry}>Done typing</button></div>{workspaceError&&<div className="wd-entry-error" role="status">{workspaceError}<button type="button" onClick={()=>setWorkspaceRetry(value=>value+1)}>Retry</button></div>}<div className="wd-task-builder"><label><span>Action</span><input value={draft.action} onChange={event=>setDraft(current=>({...current,action:event.target.value}))} placeholder="Reviewed, mailed, called…"/></label><label><span>For</span><input value={draft.subject} onChange={event=>setDraft(current=>({...current,subject:event.target.value}))} placeholder="ABC Pvt Ltd, PF challan…"/></label><label><span>Result</span><input value={draft.outcome} onChange={event=>setDraft(current=>({...current,outcome:event.target.value}))} placeholder="Confirmed, awaiting data, call tomorrow…"/></label></div><div className="wd-action-chips">{['Reviewed','Mailed','Telephonic talk','Confirmed','Processed'].map(value=><button type="button" key={value} onClick={()=>setDraft(current=>({...current,action:value}))}>{value}</button>)}</div><div className="wd-entry-status"><div className="wd-status-picker" role="group" aria-label="New work status">{['pending','progress','done'].map(status=><button key={status} type="button" data-status={status} aria-label={workStatuses[status]} title={workStatuses[status]} aria-pressed={draft.status===status||(status==='pending'&&draft.status==='todo')} disabled={adding} onClick={()=>setDraft(current=>({...current,status}))}><WorkStatusIcon status={status}/></button>)}</div><button className="wd-entry-save" type="submit" disabled={adding||!workspaceReady||!spaceId||draftLoadedKey!==draftKey}>{adding?'Saving…':'Save work'}</button></div>{draft.status==='pending'&&<details className="wd-pending-details"><summary>Pending details <span>optional</span></summary><div><label>Why pending?<input value={draft.pendingReason} onChange={event=>setDraft(current=>({...current,pendingReason:event.target.value}))} placeholder="Waiting for documents"/></label><label>Next action<input value={draft.nextAction} onChange={event=>setDraft(current=>({...current,nextAction:event.target.value}))} placeholder="Follow up tomorrow"/></label></div></details>}<p className="wd-save-hint">Choose the current status, then Save work. Completed work goes straight into the daily report.</p></form>
  <section className="wd-utility"><h2>Today’s log</h2><button className="wd-ghost" onClick={loadRoutines}>Add routine</button><button className="wd-text" onClick={()=>setRoutineOpen(true)}>Recurring work</button><span/><button className="wd-primary" onClick={()=>setReportOpen(true)}>Generate daily report</button></section>
  {tasks.length?<section className="wd-board">{['todo','progress','pending','done'].map(status=><article className="wd-lane" data-lane={status} key={status}><header><i/><h2>{{todo:'To Do',progress:'In Progress',pending:'Pending',done:'Done'}[status]}</h2><b>{groups[status].length}</b></header><div>{groups[status].sort((a,b)=>(a.order||a.createdAt||0)-(b.order||b.createdAt||0)).map(task=><article className={'wd-task-card'+(task.carryFromId?' carried':'')} key={task.id}><div className="wd-task-top"><div>{task.action&&<span className="wd-task-action">{task.action}</span>}<p>{task.subject||(!task.action?task.title:'')}</p></div><button type="button" aria-label={'Edit '+taskLabel(task)} onClick={()=>setEditingTask(task)}>•••</button></div>{task.status==='pending'&&(task.pendingReason||task.nextAction)?<div className="wd-task-note">{task.pendingReason&&<strong>{task.pendingReason}</strong>}{task.nextAction&&<span>Next: {task.nextAction}</span>}</div>:taskDetail(task)&&taskDetail(task)!==taskLabel(task)?<div className="wd-task-outcome">{taskDetail(task)}</div>:null}<div className="wd-status-actions">{[['todo','○'],['progress','▶'],['pending','Ⅱ'],['done','✓']].map(([value,icon])=><button key={value} className={task.status===value?'active':''} data-status={value} aria-label={'Mark '+({todo:'To Do',progress:'In Progress',pending:'Pending',done:'Done'}[value])} title={{todo:'To Do',progress:'In Progress',pending:'Pending',done:'Done'}[value]} onClick={()=>changeStatus(task,value)}>{icon}</button>)}</div></article>)}</div></article>)}</section>:<section className="wd-empty"><p>Nothing logged yet. Saved work shows up here.</p></section>}
  <button className="wd-primary wd-mobile-report" onClick={()=>setReportOpen(true)}>Generate daily report</button>
  {pendingTask&&<Modal eyebrow="BLOCKER NOTE" title="What is holding this up?" onClose={()=>setPendingTask(null)}><p className="wd-dialog-task">{taskLabel(pendingTask)}</p><form className="wd-form" onSubmit={savePending}><label>Why pending? <small>optional</small><textarea name="pendingReason" defaultValue={pendingTask.pendingReason||''} rows="3" placeholder="Waiting for client data"/></label><label>Next action <small>optional</small><textarea name="nextAction" defaultValue={pendingTask.nextAction||''} rows="2" placeholder="Complete once data is received"/></label><footer><button type="button" className="wd-ghost" onClick={()=>setPendingTask(null)}>Cancel</button><button type="submit" className="wd-primary">Save pending</button></footer></form></Modal>}
  {editingTask&&<Modal eyebrow="TASK DETAILS" title="Edit work" onClose={()=>setEditingTask(null)}><form className="wd-form" onSubmit={saveEdit}><label>Action <small>optional</small><input name="action" defaultValue={editingTask.action||''}/></label><label>To whom / what <small>optional</small><input name="subject" defaultValue={editingTask.subject||editingTask.title||''}/></label><label>Outcome / further action <small>optional</small><textarea name="outcome" defaultValue={taskDetail(editingTask)} rows="3"/></label><label>Status<select name="status" defaultValue={editingTask.status}>{Object.entries(workStatuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Pending reason <small>optional; saved for Pending work</small><input name="pendingReason" defaultValue={editingTask.pendingReason||''}/></label><label>Next action <small>optional; saved for Pending work</small><input name="nextAction" defaultValue={editingTask.nextAction||''}/></label><footer className="split"><button type="button" className="wd-danger" onClick={deleteTask}>Delete</button><span/><button type="button" className="wd-ghost" onClick={()=>setEditingTask(null)}>Cancel</button><button className="wd-primary">Save</button></footer></form></Modal>}
  {routineOpen&&<RoutineModal routines={work.routines} onAdd={addRoutine} onDelete={deleteRoutine} onClose={()=>setRoutineOpen(false)}/>}
  {shareOpen&&<ShareModal personal={spaceId===personalSpaceId} emails={work.editorEmails} onInvite={invite} onRemove={removeEditor} onClose={()=>setShareOpen(false)}/>}
  {reportOpen&&<Modal eyebrow="READY TO SEND" title="Daily report" wide onClose={()=>setReportOpen(false)}><textarea className="wd-report" readOnly value={report}/><footer className="wd-modal-actions"><button className="wd-ghost" onClick={()=>setReportOpen(false)}>Close</button><button className="wd-primary" onClick={copyReport}>Copy report</button></footer></Modal>}
  <div className={'wd-toast'+(toast?' show':'')}>{toast}</div>
 </div>
}

function RoutineModal({routines,onAdd,onDelete,onClose}){
 const[title,setTitle]=useState('');
 return <Modal eyebrow="REUSABLE LIST" title="Recurring work" onClose={onClose}><div className="wd-list">{routines.length?routines.map(item=><div key={item.id}><span>{item.title}</span><button onClick={()=>onDelete(item.id)}>Delete</button></div>):<p>No recurring work saved yet.</p>}</div><form className="wd-inline-form" onSubmit={event=>{event.preventDefault();if(!title.trim())return;onAdd(title.trim());setTitle('')}}><input value={title} onChange={event=>setTitle(event.target.value)} placeholder="Attendance verification"/><button className="wd-primary">Add</button></form><p className="wd-hint">Save routine jobs once, then add all of them to any workday in one tap.</p></Modal>
}
function ShareModal({personal=false,emails,onInvite,onRemove,onClose}){
 const[email,setEmail]=useState(''),[inviting,setInviting]=useState(false);
 return <Modal eyebrow="WORKSPACE ACCESS" title="Share Workday" onClose={onClose}><p className="wd-hint">{personal?'Inviting someone creates a shared copy of this Workday. Your personal work stays separate.':'Editors can add and update work, but cannot change access.'}</p><form className="wd-inline-form" onSubmit={async event=>{event.preventDefault();if(inviting)return;setInviting(true);try{if(await onInvite(email))setEmail('')}finally{setInviting(false)}}}><input type="email" required value={email} onChange={event=>setEmail(event.target.value)} placeholder="name@gmail.com"/><button className="wd-primary" disabled={inviting}>{inviting?'Inviting…':'Invite'}</button></form><div className="wd-list">{emails.length?emails.map(value=><div key={value}><span>{value}</span><button onClick={()=>onRemove(value)}>Remove</button></div>):<p>Only you have access.</p>}</div></Modal>
}
