import{initializeApp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import{getAuth,GoogleAuthProvider,signInWithPopup}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import{getFirestore,collection,doc,addDoc,updateDoc,deleteDoc,onSnapshot,query,orderBy,serverTimestamp,Timestamp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";

const config={apiKey:"AIzaSyBeVpUqcRO_VXfQrGVL5OaSGHKFB8XEQMc",authDomain:"life-by-adichimp.firebaseapp.com",projectId:"life-by-adichimp",storageBucket:"life-by-adichimp.firebasestorage.app",messagingSenderId:"761981819700",appId:"1:761981819700:web:8e88516817ed40b9866361"};
const auth=getAuth(initializeApp(config)),db=getFirestore(),$=id=>document.getElementById(id),todayKey=(d=new Date())=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
let user,items=[],unsubscribe,registration,editingId="",knownIds=new Set(),firstLoad=true;
const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return todayKey(d)};
const esc=v=>{const e=document.createElement("div");e.textContent=v||"";return e.innerHTML};
const toast=m=>{$("toast").textContent=m;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),1800)};
const dt=value=>value?.toDate?value.toDate():new Date(value);
const timeText=d=>new Intl.DateTimeFormat("en-IN",{hour:"numeric",minute:"2-digit"}).format(d);
const dateLabel=d=>new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"numeric",month:"short"}).format(d);

function card(item,isNew=false){const due=dt(item.dueAt);return `<div class="reminder-wrap" data-id="${item.id}"><div class="swipe-action done">✓ Done</div><div class="swipe-action snooze">Snooze 1h</div><article class="reminder-card ${isNew?"enter":""}"><time class="time">${timeText(due)}</time><div class="copy"><strong>${esc(item.title)}</strong><div class="meta">${item.repeat==="daily"?'<span class="repeat">↻ Daily</span>':""}${item.snoozed?"<span>Snoozed</span>":""}</div></div><button class="expand" aria-label="Reminder details">⌄</button><div class="details"><button data-action="edit">Edit</button><button data-action="snooze">Snooze 1h</button><button data-action="delete">Delete</button></div></article></div>`}
function render(){const now=new Date(),today=todayKey(),active=items.filter(x=>!x.completed),todays=active.filter(x=>todayKey(dt(x.dueAt))===today).sort((a,b)=>dt(a.dueAt)-dt(b.dueAt)),future=active.filter(x=>todayKey(dt(x.dueAt))>today).sort((a,b)=>dt(a.dueAt)-dt(b.dueAt));
 $("todayDate").textContent=new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"numeric",month:"long"}).format(now);$("thingsLeft").textContent=`${todays.length} ${todays.length===1?"thing":"things"} left`;$("todayEmpty").hidden=todays.length>0;
 $("todayList").innerHTML=todays.map(x=>card(x,!firstLoad&&!knownIds.has(x.id))).join("");$("upcomingCount").textContent=future.length;
 const groups=Map.groupBy?Map.groupBy(future,x=>todayKey(dt(x.dueAt))):future.reduce((m,x)=>(m.set(todayKey(dt(x.dueAt)),[...(m.get(todayKey(dt(x.dueAt)))||[]),x]),m),new Map());
 $("upcomingList").innerHTML=[...groups].map(([key,list])=>`<section class="date-group"><h3>${key===tomorrow()?"Tomorrow":dateLabel(dt(list[0].dueAt))}</h3>${list.map(x=>card(x,!firstLoad&&!knownIds.has(x.id))).join("")}</section>`).join("");knownIds=new Set(active.map(x=>x.id));firstLoad=false;bindSwipes();scheduleVisible(active)}

function watch(){unsubscribe?.();unsubscribe=onSnapshot(query(collection(db,"users",user.uid,"reminders"),orderBy("dueAt")),snap=>{items=snap.docs.map(d=>({id:d.id,...d.data()}));render()},e=>toast("Sync failed: "+e.message))}
function dateFromForm(){let day=$("daySelect").value,date=day==="today"?todayKey():day==="tomorrow"?tomorrow():$("customDate").value;if(!date)date=todayKey();return new Date(`${date}T${$("reminderTime").value||"19:00"}:00`)}
function openQuick(item){editingId=item?.id||"";$("quickForm").reset();$("daySelect").value="today";$("reminderTime").value="19:00";$("customDate").disabled=true;document.querySelectorAll(".chips button").forEach(x=>x.classList.remove("active"));if(item){const d=dt(item.dueAt),key=todayKey(d);$("reminderTitle").value=item.title;$("reminderTime").value=d.toTimeString().slice(0,5);$("dailyRepeat").checked=item.repeat==="daily";$("daySelect").value=key===todayKey()?"today":key===tomorrow()?"tomorrow":"custom";$("customDate").value=key;$("customDate").disabled=$("daySelect").value!=="custom"}$("quickDialog").showModal();setTimeout(()=>$("reminderTitle").focus(),80)}
$("addButton").onclick=()=>openQuick();$("closeQuick").onclick=()=>$("quickDialog").close();$("daySelect").onchange=()=>{$("customDate").disabled=$("daySelect").value!=="custom"};
document.querySelector(".chips").onclick=e=>{const b=e.target.closest("[data-preset]");if(!b)return;document.querySelectorAll(".chips button").forEach(x=>x.classList.toggle("active",x===b));const p=b.dataset.preset;if(p==="tonight"){$("daySelect").value="today";$("reminderTime").value="21:00"}if(p==="tomorrow-morning"){$("daySelect").value="tomorrow";$("reminderTime").value="08:00"}$("dailyRepeat").checked=p==="daily";$("customDate").disabled=true};
$("quickForm").onsubmit=async e=>{e.preventDefault();const title=$("reminderTitle").value.trim();if(!title)return;const data={title,dueAt:Timestamp.fromDate(dateFromForm()),repeat:$("dailyRepeat").checked?"daily":"none",completed:false,snoozed:false,updatedAt:serverTimestamp()};try{if(editingId)await updateDoc(doc(db,"users",user.uid,"reminders",editingId),data);else await addDoc(collection(db,"users",user.uid,"reminders"),{...data,createdAt:serverTimestamp()});$("quickDialog").close();toast(editingId?"Reminder updated":"Reminder added")}catch(err){toast("Could not save")}};

async function complete(id,el){const item=items.find(x=>x.id===id);if(!item)return;el?.querySelector(".reminder-card")?.classList.add("completing");if(item.repeat==="daily"){const next=dt(item.dueAt);next.setDate(next.getDate()+1);await addDoc(collection(db,"users",user.uid,"reminders"),{...item,dueAt:Timestamp.fromDate(next),completed:false,snoozed:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}setTimeout(()=>updateDoc(doc(db,"users",user.uid,"reminders",id),{completed:true,completedAt:serverTimestamp()}),330)}
async function snooze(id){const item=items.find(x=>x.id===id),due=new Date(Math.max(Date.now(),dt(item.dueAt).getTime())+3600000);await updateDoc(doc(db,"users",user.uid,"reminders",id),{dueAt:Timestamp.fromDate(due),snoozed:true,updatedAt:serverTimestamp()});toast("Snoozed for 1 hour")}
function listClick(e){const wrap=e.target.closest(".reminder-wrap");if(!wrap)return;const item=items.find(x=>x.id===wrap.dataset.id),action=e.target.closest("[data-action]")?.dataset.action;if(action==="edit")return openQuick(item);if(action==="snooze")return snooze(item.id);if(action==="delete")return confirm(`Delete “${item.title}”?`)&&deleteDoc(doc(db,"users",user.uid,"reminders",item.id));if(!e.target.closest("button"))wrap.querySelector(".reminder-card").classList.toggle("expanded")}
$("todayList").onclick=listClick;$("upcomingList").onclick=listClick;
function bindSwipes(){document.querySelectorAll(".reminder-wrap").forEach(w=>{const c=w.querySelector(".reminder-card");let start=0,dx=0;c.addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;start=e.clientX;c.setPointerCapture(e.pointerId)});c.addEventListener("pointermove",e=>{if(!start)return;dx=Math.max(-105,Math.min(105,e.clientX-start));c.style.transform=`translateX(${dx}px)`});c.addEventListener("pointerup",()=>{if(dx>72)complete(w.dataset.id,w);else if(dx<-72)snooze(w.dataset.id);c.style.transform="";start=dx=0})})}

async function requestNotifications(){if(!("Notification"in window))return toast("Notifications are not supported here");const p=await Notification.requestPermission();$("notifyButton").classList.toggle("enabled",p==="granted");toast(p==="granted"?"Notifications enabled":"Notification permission not granted");if(p==="granted")scheduleVisible(items.filter(x=>!x.completed))}
$("notifyButton").onclick=requestNotifications;
async function scheduleVisible(list){if(Notification.permission!=="granted"||!registration?.active)return;registration.active.postMessage({type:"SCHEDULE_REMINDERS",items:list.map(x=>({id:x.id,title:x.title,dueAt:dt(x.dueAt).getTime()}))})}
if("serviceWorker"in navigator){registration=await navigator.serviceWorker.register("service-worker.js",{scope:"./"});await navigator.serviceWorker.ready}
$("notifyButton").classList.toggle("enabled",window.Notification?.permission==="granted");
$("signIn").onclick=async()=>{try{$("authError").textContent="";await signInWithPopup(auth,new GoogleAuthProvider())}catch(e){$("authError").textContent=e.message}};
await auth.authStateReady();user=auth.currentUser;if(!user){$("authGate").hidden=false;auth.onAuthStateChanged(u=>{if(!u)return;user=u;$("authGate").hidden=true;watch()})}else watch();
